INSERT INTO `phrasesF` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(335, 12, 'Is it raining? No.', 'ฝนตกไหมคะ ไม่ตกค่ะ', 'Fŏhn dtòk mái khá? Mâi dtòk khâ', 'rain - fall - or not - polite particle? not - fall - polite particle', '', 'f12_2'),
(336, 12, 'Is it tasty? Yes.', 'อร่อยไหมคะ อร่อยค่ะ', 'À-ròy mái khá? À-ròy khâ', 'tasty - or not - polite particle? tasty - polite particle', '', 'f12_3'),
(337, 12, 'Was it expensive? No.', 'แพงไหมคะ ไม่แพงค่ะ', 'Phaaeng mái khá? Mâi phaaeng khâ', 'expensive - or not - polite particle? not - expensive - polite particle', '', 'f12_4'),
(338, 12, 'You''re going shopping, right? Yes.', 'คุณกำลังจะไปซื้อของใช่ไหมคะ ใช่ค่ะ', 'Khun gamlang-jà bpai séu kăwng châi mái khá? Châi khâ', 'you - about to - go - buy - stuff - yes - or no - polite particle? yes - polite particle', 'We use ''châi mái'' when there is an assumption which needs confirmation. ', 'f12_5'),
(339, 12, 'Your mother is Thai, right? No.', 'แม่เป็นคนไทยใช่ไหมคะ ไม่ใช่ค่ะ', 'Mâe bpen khon Thai châi mái khá? Mâi-châi khâ', 'mother - is - person - Thai - yes - or no - polite particle? no - polite particle', '', 'f12_6'),
(340, 12, 'He''s your boyfriend, isn''t he? No!', 'เขาเป็นแฟนคุณไม่ใช่หรอคะ ไม่ใช่ค่ะ!', 'Khăo bpen faen khun mâi-châi răw khá? Mâi-châi khâ', 'he - is - boyfriend - you - no - question word - polite particle? no - polite particle', 'The expression ''mâi châi răw'' is similar to ''châi mái''.', 'f12_7'),
(341, 12, 'You didn''t tell him, did you? Yes (I did).', 'คุณไม่ได้บอกเขาใช่ไหมคะ ฉันบอกแล้วค่ะ', 'Khun mâi dâi bòrk khăo châi mái khá? Chăn bòrk láew khâ', 'you - not - did - tell - him - yes - or no - polite particle? I - tell - past action marker - polite particle', '', 'f12_8'),
(342, 12, 'Are you going or not? Yes.', 'คุณจะไปหรือเปล่า ไปค่ะ', 'Khun jà bpai rĕuu bplàao? Bpai khâ', 'you - future marker - go - or - not? go - polite particle', 'The term ''rĕuuu bplàao'' expects a straight answer.', 'f12_9'),
(343, 12, 'Is that enough? No.', 'พอแล้วหรือยังคะ ยังค่ะ', 'Phaaw láew rĕuu yang khá? Yang khâ', 'enough - already - or - not yet - polite particle? not yet - polite particle', 'The term ''láew rĕuu yang'' means something like ''already or not yet?''. ''Láew'' is often omitted.', 'f12_10'),
(344, 12, 'Has your older sister come home yet? Yes.', 'พี่สาวคุณมาถึงบ้านหรือยังคะ ถึงแล้วค่ะ', 'Phîi săo khun maa thĕung bâan (láew) rĕuu yang khá? Thĕung láew khâ', 'older sibling - girl - you - come - arrive - home - (already) - or - not yet - polite particle? arrive - already - polite particle', '', 'f12_11'),
(345, 12, 'What''s the time?', 'กี่โมงแล้วคะ', 'Gìi mohng láew khá?', 'how many - hour - already - polite particle', '', 'f12_12'),
(346, 12, 'What''s this?', 'อันนี้คืออะไรคะ', 'An níi kheu à-rai khá?', 'item - this - is - what - polite particle?', '', 'f12_13'),
(347, 12, 'What''s his name?', 'เขาชื่ออะไรคะ', 'Khăo chêu à-rai khá?', 'he - called - what - polite particle', '', 'f12_14'),
(348, 12, 'Who am I speaking with? (On the phone)', 'ฉันกำลังพูดอยู่กับใครคะ', 'Chăn gamlang phôot yùu gùp krai khá?', 'I - currently - speak - currently - with - who - polite particle?', '', 'f12_15'),
(349, 12, 'Whose is this? It''s mine.', 'นี้ของใครคะ ของฉันค่ะ', 'Níi kăwng krai khá? Kăwng chăn khâ', 'this - belonging to - who - polite particle? belonging to - me - polite particle', '', 'f12_16'),
(350, 12, 'Which one do you want?', 'คุณอยากได้อันไหนคะ', 'Khun yàak dâi an năi khá?', 'you - want - receive - piece - which - polite particle?', 'The word ''dâi'' has various uses. In this case it means ''get'' or ''receive''.', 'f12_17'),
(351, 12, 'Where is the nearest sky train station?', 'สถานีรถไฟฟ้าไหนที่ใกล้ที่สุดคะ', 'Sà-thăa-nii rót fai fáa năi thîi glâi thîi-sùt khá? ', 'station - vehicle - fire - sky - which - that - near - most - polite particle?', '', 'f12_18'),
(352, 12, 'Where were you born?', 'คุณเกิดที่ไหนคะ', 'Khun gèrt thîi năi khá?', 'you - born - place - which - polite particle', '', 'f12_19'),
(353, 12, 'Where''s my phone?', 'โทรศัพท์ฉันอยู่ไหนคะ', 'Thoh-rá-sàp chăn yùu năi khá?', 'phone - me - situated - where - polite particle?', '', 'f12_20'),
(354, 12, 'When is he coming?', 'เขาจะมากี่โมงคะ', 'Khăo jà maa gìi mohng khá?', 'he - future marker - come - how many - hour - polite particle?', '', 'f12_21'),
(355, 12, 'When did you arrive?', 'คุณมาถึงกี่โมงคะ', 'Khun maa thĕung gìi mohng khá?', 'you - come - arrive - how many - hour - polite particle?', '', 'f12_22'),
(356, 12, 'What day does school start?', 'เปิดเทอมวันไหนคะ', 'Bpѐrt theerm wan năi khá?', 'open - term - day - which - polite particle?', '', 'f12_23'),
(357, 12, 'When are you going to tell him?', 'คุณจะบอกเขาเมื่อไรคะ', 'Khun jà bòrk khăo mêuua-rai khá?', 'you - future marker - tell - him - when - polite particle?', 'The term ''mêuua-rai'' is common when not requesting a specific time or date.', 'f12_24'),
(358, 12, 'Why did you come late?', 'ทำไมมาสายคะ', 'Tham-mai maa săai khá?', 'why - come - late - polite particle?', '', 'f12_25'),
(359, 12, 'Why didn''t you tell me?', 'ทำไมคุณไม่บอกฉันคะ', 'Tham-mai khun mâi bòrk chăn khá?', 'why - you - not - tell - me - polite particle?', '', 'f12_26'),
(360, 12, 'How did you get here?', 'คุณมายังไงคะ', 'Khun maa yang-ngai khá?', 'you - come - how - polite particle?', 'The term ''yang-ngai'' is an informal pronunciation of ''yang-rai'', meaning ''how'' or ''in what way''.', 'f12_27'),
(361, 12, 'What do you think?', 'คุณคิดว่ายังไงคะ / คุณคิดยังไงคะ', 'Khun khít wâh yang-ngai khá? / Khun khít yang-ngai khá?', 'you - think - that - how - polite particle? / you - think - how - polite particle?', '', 'f12_28'),
(362, 12, 'How many people are coming for dinner?', 'มีคนมาทานข้าวเย็นด้วยกันทั้งหมดกี่คนคะ', 'Mii khon maa thaan khâao-yen dûay gan tháng-mòht gìi khon khá?', 'have - person - come - eat - dinner - together  - with each other - altogether - how many - person - polite particle?', '', 'f12_29'),
(363, 12, 'How many children do you have?', 'คุณมีลูกกี่คนคะ', 'Khun mii lûuk gìi khon khá?', 'you - have - child - how many - classifier for people - polite particle?', '', 'f12_30'),
(364, 12, 'How much is this?', 'อันนี้เท่าไหร่คะ', 'An níi thâo rai khá?', 'item - this - equal to - what - polite particle?', 'How much? questions for which the answer may be numerically quantified may be formed with ''thâo rai'' or ''gìi ...''.', 'f12_31'),
(365, 12, 'How heavy is it?', 'หนักเท่าไหร่คะ', 'Nák thâo rai khá?', 'heavy - equal to - what - polite particle?', '', 'f12_32'),
(366, 12, 'How far is Chiang Mai from Bangkok?', 'เชียงใหม่ไกลจากกรุงเทพฯแค่ไหน', 'Chiiang-mài glai jàak groong-thâehp khâe năi? ', 'chiang mai - far - from - bangkok - to the extent of - which?', 'How much? questions which do not necessarily expect a numerical response can be formed with ''khâe năi''.', 'f12_33'),
(367, 12, 'How well do you know him?', 'คุณรู้จักเขาดีแค่ไหนคะ', 'Khun rúu-jàk khăo dii khâe năi khá?', 'you - know - him - good - to the extent of - which - polite particle?', '', 'f12_34'),
(368, 13, 'I''m not going.', 'ฉันไม่ไปค่ะ', 'Chăn mâi bpai khâ', 'I - not - go - polite particle', 'Verbs and adjectives are generally negated by being preceded with ''mâi''.', 'f13_1'),
(369, 13, 'I don''t want it.', 'ฉันไม่อยากได้', 'Chăn mâi yàak dâi', 'I - not - want - get', 'The verb ''yàak'' must be followed by another verb.  When directed towards a thing, the verb ''dâi'' is used to mean ''get''.', 'f13_2'),
(370, 13, 'We don''t have a bathroom.', 'เราไม่มีห้องน้ำค่ะ', 'Rao mâi mii hâwng-náam khâ', 'we - not - have - bathroom - polite particle', '', 'f13_3'),
(371, 13, 'He doesn''t have a job.', 'เขาไม่มีงานทำค่ะ', 'Khăo mâi mii ngaan tum khâ', 'he - not - have - work - do - polite particle', '', 'f13_4'),
(372, 13, 'I''m not American.', 'ฉันไม่ได้เป็นคนอเมริกันค่ะ', 'Chăn mâi-dâi bpen khon À-meh-ríi-gan khâ', 'I - not  - am - person - American - polite particle', 'The verb ''bpen'' is negated with ''mâi dâi''. Sometimes ''mâi châi'' is used instead of ''mâi dâi bpen''.', 'f13_5'),
(373, 13, 'She is not my friend.', 'ผู้หญิงคนนั้นไม่ใช่เพื่อนฉันค่ะ', 'Phûu-yĭng khon nán mâi-châi phêuuan chăn khâ', 'woman - person classifier - that - not - friend - I -  polite particle', '', 'f13_6'),
(374, 13, 'That''s wrong.', 'ไม่ถูกค่ะ / ไม่ใช่ค่ะ', 'Mâi thùuk khâ / Mâi-châi khâ', 'not - correct - polite particle / no - polite particle', '', 'f13_7'),
(375, 13, 'It''s not easy.', 'ไม่ง่ายค่ะ', 'Mâi ngâai khâ', 'not - easy - polite particle', '', 'f13_8'),
(376, 13, 'It''s not enough.', 'ไม่พอค่ะ', 'Mâi phaaw khâ', 'not - enough - polite particle', '', 'f13_9'),
(377, 13, 'The house isn''t very big', 'บ้านไม่ค่อยใหญ่เท่าไหร่ค่ะ', 'Bâan mâi khâawy yài thâo-rai khâ', 'house - not - very much - big - very much - polite particle', '', 'f13_10'),
(378, 13, 'I don''t look after him', 'ฉันไม่ดูแลเขาค่ะ', 'Chăn mâi doo-lae khăo khâ', 'I - not - look after - him - polite particle', 'In the case of multiple verbs, usually the first verb is negated.', 'f13_11'),
(379, 13, 'I''m not making any comparisons.', 'ฉันไม่เปรียบเทียบค่ะ', 'Chăn mâi brìiap thîiap khâ', 'I - not - compare - compare - polite particle', '', 'f13_12'),
(380, 13, 'I can''t find it.', 'ฉันหาไม่เจอค่ะ', 'Chăn hăa mâi juuhr khâ', 'I - look for - not - find - polite particle', 'Where the second verb occurs as a result of the first, the second verb is negated.', 'f13_13'),
(381, 13, 'They haven''t arrived yet', 'พวกเขายังมาไม่ถึงค่ะ', 'Phûak khăo yang maa mâi thĕung khâ', 'group of - him - still - come - not - arrive - polite particle', '', 'f13_14'),
(382, 13, 'We don''t have enough time.', 'เรามีเวลาไม่พอค่ะ', 'Rao mii waeh-lah mâi phaaw khâ', 'we - have - time - not - enough - polite particle', '', 'f13_15'),
(383, 13, 'Nok didn''t watch the movie.', 'นกไม่ได้ดูหนังค่ะ', 'Nók mâi dâi doo năng khâ', 'Nok - not - did - see - film - polite particle', 'For most verbs, to form a past negative ''mâi dâi'' is placed before the verb.', 'f13_16'),
(384, 13, 'We didn''t buy the car.', 'เราไม่ได้ซื้อรถค่ะ', 'Rao mâi dâi séu rot khâ', 'we - not - did - buy - car - polite particle', '', 'f13_17'),
(385, 13, 'You don''t have to go.', 'ไม่ต้องไปก็ได้ค่ะ', 'Mâi dtôrng bpai gôr-dâi khâ', 'not - have to - go - ok - polite particle', '', 'f13_18'),
(386, 13, 'You must not go.', 'ห้ามไปค่ะ', 'Hâam bpai khâ', 'prohibited - go - polite particle', '', 'f13_19'),
(387, 13, 'You haven''t finished.', 'คุณยังทำไม่เสร็จนะคะ', 'Khun yang tham mâi sèt ná khâ', 'you - still - do - not - finish - softening particle - polite particle', '', 'f13_20'),
(388, 13, 'I haven''t eaten yet.', 'ฉันยังไม่ได้ทานข้าวค่ะ', 'Chăn yang mâi dâi thaan khâao khâ', 'I - still - not - did - eat - rice - polite particle', '', 'f13_21'),
(389, 13, 'I haven''t got my visa yet.', 'ฉันยังไม่ได้รับวีซ่าเลยค่ะ', 'Chăn yang mâi dâi ráp wii-sâa leeuy khâ', 'I - still - not - did - get - visa - at all - polite particle', '', 'f13_22'),
(390, 13, 'Buaa has never seen snow.', 'บัวยังไม่เคยเห็นหิมะมาก่อนเลยค่ะ', 'Buaa yang mâi ker-ee hĕn hì-má maa-gòrn leeuy khâ', 'Buaa - still - not - ever - see - snow - before - at all - polite particle', 'The word ''ker-ee'' has two uses. It can be used to talk about whether something has ever happened or not, and to talk about habitual actions in the past.', 'f13_23'),
(391, 13, 'Don''t touch it!', 'ห้ามจับ!', 'Hâam jàp!', 'prohibited - touch', '', 'f13_24'),
(392, 13, 'It''s impossible!', 'เป็นไปไม่ได้!', 'Bpen bpai mâi dâi!', 'to be able - go - not - can', '', 'f13_25'),
(393, 15, 'We''re going on holiday at the end of the year.', 'เราจะไปเที่ยวสิ้นปีนี้ค่ะ', 'Rao jà bpai thîaao sîn bpii níi khâ', 'we - future marker - go - trip - end - year - this - polite particle', 'The word ''jà'' implies a future action.', 'f15_1'),
(394, 15, 'When are you going to get a haircut?', 'คุณจะไปตัดผมเมื่อไหร่คะ', 'Khun jà bpai dtàt phŏhm mêuua-rai khá?', 'you - future marker - go - cut - hair - when - polite particle?', '', 'f15_2'),
(395, 15, 'Ning is not coming to school tomorrow.', 'หนิงจะไม่มาโรงเรียนพรุ่งนี้ค่ะ', 'Nĭng jà mâi maa rohng-riian phrûng-níi khâ', 'Ning - future marker - not - come - school - tomorrow - polite particle', '', 'f15_3'),
(396, 15, 'I''ll go to the market on the way home tomorrow.', 'ฉันจะไปตลาดพรุ่งนี้ก่อนกลับบ้านค่ะ', 'Chăn jà bpai dtà-làat phrûng-níi gòrn glàp bâan khâ', 'I - future marker - go - market - tomorrow - before - return - home - polite particle', '', 'f15_4'),
(397, 15, 'Mother is about to prepare food.', 'แม่กำลังจะทำอาหาร', 'Mâe gamlang-jà tham aa-hăan', 'mother - about to - make - food', 'The construction ''gamlang-jà'' is used to indicate that something is just about to happen.', 'f15_5'),
(398, 15, 'He''s just leaving/He''s already left.', 'เขาไปแล้วค่ะ', 'Khăo bpai láew khâ', 'he - go - past action marker - polite particle', 'The word ''láew'' indicates a past action, or something that is just happening.', 'f15_6'),
(399, 15, 'The restaurant''s shut.', 'ร้านอาหารปิดเเล้วค่ะ', 'Raan aa-hăan bpìt láew khâ.', 'shop - food - close - past action marker - polite particle', '', 'f15_7'),
(400, 15, 'Chompoo was not well this morning.', 'เมื่อเช้านี้ชมพูไม่สบายค่ะ', 'Mêuua cháao níi Chohm-phuu mâi sà-baai khâ', 'point in time - morning - this - Chompoo - not - well - polite particle', 'A past action may be implied by the context, such as when using a time or date.', 'f15_8'),
(401, 15, 'I went to Phuket last month.', 'ฉันไป เกาะภูเก็ต เมื่อเดือนที่แล้วค่ะ', 'Chăn bpai gàw phuu-gèt mêuua deuan thîi-láew khâ', 'I - go - island - Phuket - point in time - month - last - polite particle', '', 'f15_9'),
(402, 15, 'I didn''t buy it.', 'ฉันไม่ได้ซื้อค่ะ', 'Chăn mâi dâi séu khâ', 'I - not - did - buy - polite particle', 'Placing ''mâi dâi'' before a verb indicates a past action that did not happen.', 'f15_10'),
(403, 15, 'He didn''t tell me.', 'เขาไม่ได้บอกฉันนะคะ', 'Khăo mâi dâi bòrk chăn ná khâ', 'he - not - did - tell - me - softening particle - polite particle', '', 'f15_11'),
(404, 15, 'It''s used up.', 'หมดแล้วค่ะ', 'Mòht láew khâ', 'used up - already - polite particle', '', 'f15_12'),
(405, 15, 'They left a moment ago.', 'พวกเขาไปเมื่อสักครู่นี้เองค่ะ', 'Phûak-khăo bpai mêuua-sàk-khrûu níi aehng khâ', 'they - go - a moment ago - this - only - polite particle', '', 'f15_13'),
(406, 15, 'Have you finished your homework yet? Yes.', 'การบ้านเสร็จหรือยังคะ เสร็จแล้วค่ะ', 'Gaan bâan sèt (láew) rĕuu yang khá? Sèt láew khâ', 'task - home - finish - (already) - or - not yet - polite particle? finish - already - polite particle', '', 'f15_15'),
(407, 15, 'Has father come home yet? Not yet.', 'พ่อกลับมาบ้านหรือยังคะ ยังค่ะ', 'Phâaw glàp maa bâan rĕuu yang khá? Yang khâ', 'father - return - come - home - or - not yet - polite particle? not yet - polite particle', '', 'f15_16'),
(408, 15, 'Have you been to the doctor already? Yes.', 'ไปหาหมอมาหรือยังคะ ไปมาแล้วค่ะ', 'Bpai hăa mŏr maa rĕuu yang khá? Bpai maa láew khâ', 'go - visit - doctor - come back - or - not yet - polite particle? go - come back - already - polite particle', 'Using ''bpai'' and ''maa'' together in a sentence can imply a trip which has finished.', 'f15_17'),
(409, 15, 'Have you eaten yet? Yes.', 'ทานข้าวหรือยังคะ ทานแล้วค่ะ', 'Thaan khâao rĕuu yang khâ? Than láew khâ', 'eat - rice - (or) - not yet - polite particle? eat - already', '', 'f15_18'),
(410, 15, 'It''s still raining.', 'ฝนยังตกอยู่เลยค่ะ', 'Fŏhn yang dtòk yùu leuuy khâ', 'rain - still - fall - currently - exclamation - polite particle', '', 'f15_19'),
(411, 15, 'He''s still here.', 'เขายังอยู่ที่นี่ค่ะ', 'Khăo yang yùu thîi-nîi ná khâ', 'he - still - situated - here - softening particle - polite particle', '', 'f15_20'),
(412, 15, 'Waan is in a meeting now.', 'หวานกำลังประชุมอยู่ค่ะ', 'Wăan gamlang bprà-choom yùu khâ', 'Waan - currently - meeting - currently - polite particle', 'The construction ''gamlang .... yùu'' is used to talk about something that is currently happening or was happening. Either ''gamlang'' or yùu'' may be dropped.', 'f15_21'),
(413, 15, 'Older sister is watching TV.', 'พี่สาวกำลังดูทีวีอยู่ค่ะ', 'Phîi săo gamlang doo tee-wee yùu khâ', 'older sibling - girl - currently - watch - tv - currently - polite particle', '', 'f15_22'),
(414, 15, 'The dog is sleeping.', 'หมากำลังนอนอยู่ค่ะ', 'Măa gamlang norn yùu khâ', 'dog - currently - sleep - currently - polite particle', '', 'f15_23'),
(415, 15, 'He is waiting for the bus.', 'เขากำลังรอรถเมล์อยู่ค่ะ', 'Khăo gamlang raaw rót-maeh yùu khâ', 'he - currently - wait - bus - currently - polite particle', '', 'f15_24'),
(416, 15, 'We just returned from Japan.', 'เราเพิ่งกลับจากญี่ปุ่นมาค่ะ', 'Rao phêerng glàp jàak Yîi-bpun maa khâ', 'we - just - return - from - Japan - come - polite particle', 'The word ''phêerng'' can be used to indicate that something just happened.', 'f15_25'),
(417, 15, 'I only just found out.', 'ฉันเพิ่งรู้ค่ะ', 'Chăn phêerng róo khâ', 'I - recently - know - polite particle', '', 'f15_26'),
(418, 15, 'We used to go to the temple every week.', 'เราเคยไปวัดทุกอาทิตย์ค่ะ', 'Rao ker-ee bpai wát thúk aa-thít khâ', 'we - used to - go - temple - every - week - polite particle', 'The word ''ker-ee'' has two uses. It can be used to talk about whether something has ever happened or not, and to talk about habitual actions in the past.', 'f15_27'),
(419, 15, 'I''ve already seen it. (the movie)', 'ฉันเคยดูแล้วค่ะ', 'Chăn ker-ee doo láew khâ', 'I - already - watch - past action marker - polite particle', '', 'f15_28'),
(420, 15, 'Have you ever been to the Temple of the Emerald Buddha? Yes.', 'เคยไปวัดพระแก้วหรือยังคะ เคยแล้วค่ะ', 'Ker-ee bpai Wát Pra-Gâew rĕuu yang khá? Ker-ee láew khâ', 'ever - go - temple - emerald buddha - or - not yet? already - past action marker - polite particle', '', 'f15_29'),
(421, 15, 'I went there when I was a child', 'ฉันเคยไปตอนเด็กๆค่ะ', 'Chăn ker-ee bpai dtàawn dèk-dèk khâ', 'I - have already - go - at time period - children - polite particle', '', 'f15_30'),
(422, 15, 'I have been playing soccer since I was five.', 'ฉันเล่นฟุตบอลตั้งแต่อายุห้าขวบค่ะ', 'Chăn lên fút-baawn dtâng-dtàae aa-yúu hâa khùaap khâ', 'I - play - football - since - age - five - classifier for years of age - polite particle', '', 'f15_31'),
(423, 15, 'We stayed there for two months.', 'เราอยู่ที่นั่นมาสองเดือนแล้วค่ะ', 'Rao yùu thîi nán maa săawng deuan láew khâ', 'we - stay - at place - that - come - two - month - past action marker - polite particle ', '', 'f15_32'),
(424, 16, 'How much is this?', 'นี่ราคาเท่าไหร่คะ', 'Nîi raa-khaa thâo rai khá?', 'this - price - equal to - what - polite particle?', '', 'f16_1'),
(425, 16, 'How many baht?', 'กี่บาทคะ', 'Gìi bàht khá?', 'how many - baht - polite particle?', '', 'f16_2'),
(426, 16, 'How much per piece?', 'ชิ้นละเท่าไหร่คะ', 'Chín lá thâo rai khá?', 'piece - each - equal to - what - polite particle?', '', 'f16_3'),
(427, 16, 'How much per kilo?', 'โลละเท่าไหร่คะ', 'Loh lá thâo rai khá?', 'kilo - each - equal to - what - polite particle?', 'Thai uses many words from English with a Thai pronunciation. The English word ''kilo'' becomes ''gì-loh'' or just ''loh''.', 'f16_4'),
(428, 16, 'How much per metre?', 'เมตรละเท่าไหร่คะ', 'Mét lá thâo rai khá?', 'metre - each - equal to - what - polite particle?', '', 'f16_5'),
(429, 16, 'How much per day?', 'วันละเท่าไหร่คะ', 'Wan lá thâo rai khá?', 'day - each - equal to - what - polite particle?', '', 'f16_6'),
(430, 16, 'What do you want to buy?', 'คุณจะซื้ออะไรคะ', 'Khun jà séu à-rai khá?', 'you - want to - buy - what - polite particle?', 'The future marker ''jà'' in this case means ''want to''.', 'f16_7'),
(431, 16, 'I want to buy a skirt.', 'ฉันจะซื้อกระโปรง', 'Chăn jà séu grà-bprong.', 'I - want to -  buy - skirt', '', 'f16_8'),
(432, 16, 'Very expensive.', 'แพงมากเลยค่ะ', 'Phaaeng mâhk leeuy khâ', 'expensive - very - exclamation - polite particle', '', 'f16_9'),
(433, 16, 'Cheap.', 'ถูก', 'Thùuk.', '', '', 'f16_10'),
(434, 16, 'Can you reduce the price a bit? No!', 'ลดหน่อยได้ไหมคะ ไม่ได้!', 'Lóht nòy dâi mái khá? Mâi dâi!', 'reduce - a little - can - or not - polite particle? not - can!', '', 'f16_11'),
(435, 16, 'Do you have anything cheaper?', 'คุณมีอะไรถูกกว่านี้ไหมคะ', 'Khun mii à-rai thùuk gwàa níi mái khá?', 'you - have - anything - cheap - more than - this - or not - polite particle? ', '', 'f16_12'),
(436, 16, 'Do you have any more of these?', 'คุณมีแบบนี้อีกไหมคะ', 'Khun mii bàaep níi èek mái khá?', 'you - have - kind - this - more - or not - polite particle?', '', 'f16_13'),
(437, 16, 'Do you have any more sim cards?', 'คุณมีซิมโทรศัพท์ไหมคะ', 'Khun mii sim thoh-rá-sàp èek mái khá?', 'you - have - sim - phone - another - or not - polite particle?', '', 'f16_14'),
(438, 16, 'I''ll come back tomorrow.', 'ฉันจะกลับมาพรุ่งนี้ค่ะ', 'Chăn jà glàp maa phrûng-níi khâ', 'I - future marker - return - come - tomorrow - polite particle', '', 'f16_15'),
(439, 16, 'Do you take credit card?', 'คุณรับบัตรเครดิตไหมคะ', 'Khun ráp bàt khraeh-dìt mái khá?', 'you - accept - card - credit - or not - polite particle?', '', 'f16_16'),
(440, 16, 'I''ll take this one.', 'ฉันเอาอันนี้ค่ะ', 'Chăn ao an níi khâ', 'I - take - piece - this - polite particle', '', 'f16_17'),
(441, 16, 'I don''t like that one.', 'ฉันไม่ชอบอันนั้นเลยค่ะ', 'Chăn mâi chôrp an nán leeuy khâ', 'I - not - like - item - that - at all - polite particle', '', 'f16_18'),
(442, 16, 'I''ll take half a kilo.', 'ฉันเอาครึ่งกิโลค่ะ', 'Chăn ao khrêung gì-loh khâ', 'I - take - half - kilo - polite particle', '', 'f16_19'),
(443, 16, 'Two kilos of mandarins.', 'ส้มสองกิโล', 'Sôhm săawng gì-loh', 'orange - two - kilo', 'Thais tend to use the word ''sôhm'' for both oranges and mandarins.', 'f16_20'),
(444, 16, 'A metre of silk.', 'ผ้าไหมหนึ่งเมตร', 'Phâa-măi nèung mét', 'silk fabric - one - metre', '', 'f16_21'),
(445, 16, 'Classifier for items of clothing.', 'ตัว', 'Dtua', '', 'Thai has many classifiers or ''counting words'' which have no equivalent in English. When talking about a number of items we can use the construction ''item name + number + classifier''.', 'f16_22'),
(446, 16, 'Classifier for shoes and socks.', 'คู่', 'Khôu', '', '', 'f16_23'),
(447, 16, 'Classifier for books.', 'เล่ม', 'Lêm', '', '', 'f16_24'),
(448, 16, 'Classifier for pens.', 'ด้าม', 'Dâam', '', '', 'f16_25'),
(449, 16, 'Classifier for bottles', 'ขวด', 'Khùat', '', '', 'f16_26'),
(450, 16, 'Four pens', 'ปากกาสี่ด้าม', 'Bpàak-gaa sìi dâam', 'pen - four - classifier', '', 'f16_27'),
(451, 16, 'Two T-shirts.', 'เสื้อทีเชิร์ตสองตัว', 'Sêuua thii-chúrt săawng dtua', 'shirt - T-shirt - two - classifier', '', 'f16_28'),
(452, 16, 'Two books', 'หนังสือสองเล่ม', 'Năng-sĕu săawng lêm', 'book - two - classifier', '', 'f16_29'),
(453, 16, 'Can I have a receipt?', 'ฉันขอใบเสร็จด้วยนะคะ', 'Chăn kŏr bai-sèt dûay ná khâ', 'I - request - receipt - particle following a request - softening particle - polite particle', '', 'f16_30'),
(454, 16, 'I don''t want a bag.', 'ไม่เอาถุงค่ะ', 'Mâi ao thŏong khâ', 'not - take - bag - polite particle', 'This statement is very useful in Thailand since even single items and drinks will often be put in plastic bags by default.', 'f16_31'),
(455, 16, 'Do I pay now?', 'ให้ฉันจ่ายเงินเลยไหมคะ', 'Hâi chăn jàai ngern leeuy mái khá?', 'give - I - pay - money - at once - or not - polite particle?', '', 'f16_32'),
(456, 16, 'Where do I pay?', 'จ่ายเงินที่ไหนคะ', 'Jàai ngern thîi năi khá?', 'pay - money - at (place) - which - polite particle?', '', 'f16_33'),
(457, 16, 'I paid already.', 'ฉันจ่ายเงินแล้วค่ะ', 'Chăn jàai ngern láew khâ', 'I - pay - money - already - polite particle', '', 'f16_34'),
(458, 16, 'Are you still open?', 'ยังเปิดอยู่ไหมคะ', 'Yang bpèrt yùu mái khá? ', 'still - open - currently - or not - polite particle?', '', 'f16_35'),
(459, 16, 'What time do you close?', 'คุณปิดกี่โมงคะ', 'Khun bpìt gìi mohng khá?', 'you - close - how many - hour - polite particle?', '', 'f16_36'),
(460, 16, 'Where can I change money?', 'ฉันแลกเงินได้ที่ไหนคะ', 'Chăn lâaek ngern dâi thîi năi khá?', 'I - exchange - money - can - at (place) - which - polite particle?', '', 'f16_37'),
(461, 16, 'Do you change Vietnamese dong?', 'คุณรับแลกเงินเวียดนามไหมคะ', 'Khun ráp lâaek ngern Wîiat-naam mái khá?', 'you - accept - exchange - money - Vietnam - or not - polite particle?', '', 'f16_38'),
(462, 17, 'Retail shop', 'ร้านค้า', 'Ráan kháa', 'shop - trade', '', 'f17_1'),
(463, 17, 'Bookstore', 'ร้านหนังสือ', 'Ráan năng-sĕu', 'shop - book', '', 'f17_2'),
(464, 17, 'Restaurant', 'ร้านอาหาร', 'Ráan a-hăan', 'shop - food', '', 'f17_3'),
(465, 17, 'Department store', 'ห้างสรรพสินค้า', 'Hâang sàp-phá-sĭn-kháa', '', '', 'f17_4'),
(466, 17, 'Market', 'ตลาด', 'Dtà-làat', '', '', 'f17_5'),
(467, 17, 'Night market', 'ตลาดโต้รุ่ง', 'Dtà-làat dtôh-rôong', 'market - until dawn', 'Not all night markets will go all night, but this phrase is still used.', 'f17_6'),
(468, 17, 'Supermarket', 'ซุปเปอร์มาร์เก็ต', 'Sóop-bpuuhr-maa-get', '', '', 'f17_7'),
(469, 17, 'Shopping mall', 'ห้างสรรพสินค้า', 'Hâang sàp-phá-sĭn-kháa', '', '', 'f17_8'),
(470, 17, 'Bank', 'ธนาคาร', 'Thá-naa-kaan', '', '', 'f17_9'),
(471, 17, 'Post office', 'ไปรษณีย์', 'Bprai-sà-nii', '', '', 'f17_10'),
(472, 17, 'Pharmacy', 'ร้านขายยา', 'Ráan khăai yaa', 'shop - sell - medicine', '', 'f17_11'),
(473, 17, 'Soap', 'สบู่', 'Sà-bùu', '', '', 'f17_12'),
(474, 17, 'Laundry detergent / powder', 'น้ำยาซักผ้า / ผงซักฟอก', 'Nám yaa sák phâa / Phŏhng sák fâawk ', 'water - medicine - wash - clothes / powder - wash - purify', '', 'f17_13'),
(475, 17, 'Toothbrush', 'แปรงสีฟัน', 'Bpraaeng sĕe fan', 'brush - rub against - teeth', '', 'f17_14'),
(476, 17, 'Toothpaste', 'ยาสีฟัน', 'Yaa sĕe fan', 'medicine - rub against - teeth', '', 'f17_15'),
(477, 17, 'Shampoo', 'แชมพู', 'Chaem-phuu', '', '', 'f17_16'),
(478, 17, 'Mosquito repellent', 'ยากันยุง', 'Yaa gan yoong', 'medicine - prevent - mosquito', '', 'f17_17'),
(479, 17, 'Paper', 'กระดาษ', 'Gra-dàat', '', '', 'f17_18'),
(480, 17, 'Envelope, package', 'ซอง', 'Saawng', '', '', 'f17_19'),
(481, 17, 'Postage stamp', 'ไปรษณียากร', 'Bprai-sà-nii-yaa-gaawn', '', '', 'f17_20'),
(482, 17, 'Sunblock', 'ครีมกันแดด', 'Khreem gan dàaet', 'cream - protect against - sunshine', '', 'f17_21'),
(483, 17, 'Toilet paper', 'ทิชชู่', 'Thít-chûu', '', '', 'f17_22'),
(484, 17, 'Batteries', 'แบตเตอรี่ / ถ่าน', 'Bàaet-dtuuhr-rêe / thàan', '', '', 'f17_23'),
(485, 17, 'Band aids', 'พลาสเตอร์', 'Phlaas-dtûuhr', '', '', 'f17_24'),
(486, 17, 'Mobile phone', 'โทรศัพท์มือถือ', 'Thoh-rá-sàp meuu thĕuu', 'phone - hand - hold', '', 'f17_25'),
(487, 17, 'Laptop', 'แลปทอป / โน้ตบุ๊ก', 'Láaep-thaawp / Nóat-bóok', '', '', 'f17_26'),
(488, 17, 'Camera', 'กล้องถ่ายรูป', 'Glâawng thàai rûup', 'optical viewing device - take photo - image', '', 'f17_27'),
(489, 19, 'Cloth, fabric', 'ผ้า', 'Phâa', '', '', 'f19_1'),
(490, 19, 'Silk', 'ผ้าไหม', 'Phâa măi', 'material - silk', '', 'f19_2'),
(491, 19, 'Cotton', 'ผ้าฝ้าย', 'Phâa fâai', 'material - raw cotton', '', 'f19_3'),
(492, 19, 'Wood', 'ไม้', 'Máai', '', '', 'f19_4'),
(493, 19, 'Teak', 'ไม้สัก', 'Máai-sàk', '', '', 'f19_5'),
(494, 19, 'Precious stone', 'มณี', 'Má-nee', '', '', 'f19_6'),
(495, 19, 'Gold-leaf', 'แผ่นทอง', 'Phàen thaawng', 'sheet - gold', '', 'f19_7'),
(496, 19, 'Leather', 'หนัง', 'Năng', '', '', 'f19_8'),
(497, 19, 'Clothing', 'เสื้อผ้า', 'Sêuua phâa', 'upper garment - cloth, clothing', '', 'f19_9'),
(498, 19, 'T-shirt', 'เสื้อยืด', 'Sêuua yêuut', 'shirt - elastic', '', 'f19_10'),
(499, 19, 'Shirt, blouse', 'เสื้อ', 'Sêuua', '', '', 'f19_11'),
(500, 19, 'Skirt, dress', 'กระโปรง', 'Grà-bprohng', '', '', 'f19_12'),
(501, 19, 'Trousers', 'กางเกง', 'Gaang-gaeng', '', '', 'f19_13'),
(502, 19, 'Shorts', 'กางเกงขาสั้น', 'Gaang-gaeng khăa sân', 'trousers - leg - short', '', 'f19_14'),
(503, 19, 'Sweater', 'เสื้อกันหนาว', 'Sêuua gan năao', 'upper garment - prevent - cold', '', 'f19_15'),
(504, 19, 'Socks', 'ถุงเท้า', 'Thŏong tháao', 'bag - foot', '', 'f19_16'),
(505, 19, 'Hat', 'หมวก ', 'Mùaak', '', '', 'f19_17'),
(506, 19, 'Jacket', 'เสื้อแจ็กเก็ต', 'Sêuua jàek-gêt', 'upper garment - jacket', '', 'f19_18'),
(507, 19, 'Shoes, footwear', 'รองเท้า', 'Raawng tháao', 'support - foot', '', 'f19_19'),
(508, 19, 'Sandals', 'รองเท้าแตะ', 'Raawng tháao dtàe', 'support - foot - touch, feel', '', 'f19_20'),
(509, 19, 'Tailor', 'ช่างตัดเสื้อ', 'Châng dtàt sêuua', 'artisan - cut - garment', '', 'f19_21'),
(510, 19, 'What size?', 'ขนาดไหน / ไซส์ไหนคะ', 'Kha-nàat năi? / Sai năi khá?', 'size - which? / size - which - polite particle?', '', 'f19_22'),
(511, 19, 'Can I try it on?', 'ฉันขอลองได้ไหมคะ', 'Chăn kŏr laawng dâi mái khá?', ' I - request - try - can - or not - polite particle?', '', 'f19_23'),
(512, 19, 'It''s too big.', 'ใหญ่ไปค่ะ', 'Yài bpai khâ', 'big - go - polite particle', '', 'f19_24'),
(513, 19, 'It''s too small.', 'เล็กไปค่ะ', 'Lék bpai khâ', 'small - go - polite particle', '', 'f19_25'),
(514, 19, 'It''s too long.', 'ยาวไปค่ะ', 'Yaao bpai khâ', 'long - go - polite particle', '', 'f19_26'),
(515, 19, 'It''s too short.', 'สั้นไปค่ะ', 'Sún bpai khâ', 'short - go - polite particle', '', 'f19_27'),
(516, 19, 'Do you have anything bigger?', 'คุณมีไซส์ใหญ่กว่านี้ไหมคะ', 'Khun mii sai yài gwàa níi mái khá?', 'you - have - size - big - more than - this - or not - polite particle?', '', 'f19_28'),
(517, 19, 'Do you have any other colours?', 'คุณมีสีอื่นไหมคะ', 'Khun mii sĭi èuun mái khá?', 'you - have - colour - other - or not - polite particle?', '', 'f19_29'),
(518, 19, 'Will the colour fade/run?', 'สีจะตกไหมคะ', 'Sĭi jà dtòk mái khá?', 'colour - future marker - run/fade - or not - polite particle?', '', 'f19_30'),
(519, 22, 'Fruit', 'ผลไม้', 'Phŏn-lá-mái', '', '', 'f22_1'),
(520, 22, 'Apple', 'แอปเปิ้ล ', 'Aàep-bpûn', '', '', 'f22_2'),
(521, 22, 'Banana', 'กล้วย', 'Glûay', '', '', 'f22_3'),
(522, 22, 'Orange', 'ส้ม', 'Sôhm', '', '', 'f22_4'),
(523, 22, 'Mandarin', 'ส้มจีน', 'Sôhm-jiin', 'orange - China', '', 'f22_5'),
(524, 22, 'Tamarind', 'มะขาม', 'Má-khăam', '', '', 'f22_6'),
(525, 22, 'Musk melon', 'แตงไทย', 'Dtaaeng thai', '', '', 'f22_7'),
(526, 22, 'Pomelo', 'ส้มโอ', 'Sôhm oh', '', '', 'f22_8'),
(527, 22, 'Mango', 'มะม่วง', 'Má-mûaang', '', '', 'f22_9'),
(528, 22, 'Papaya', 'มะละกอ', 'Má-lá-gaaw', '', '', 'f22_10'),
(529, 22, 'Guava', 'ฝรั่ง', 'Fà-ràng', '', '', 'f22_11'),
(530, 22, 'Coconut', 'มะพร้าว', 'Má-phráao', '', '', 'f22_12'),
(531, 22, 'Pineapple', 'สับปะรด', 'Sàp-bpà-róht', '', '', 'f22_13'),
(532, 22, 'Durian', 'ทุเรียน', 'Thú-rian', '', '', 'f22_14'),
(533, 22, 'Jackfruit', 'ขนุน', 'Khà-nŏon', '', '', 'f22_15'),
(534, 22, 'Lime', 'มะนาว', 'Má-naao', '', '', 'f22_16'),
(535, 22, 'Vegetables', 'ผัก', 'Phàk', '', '', 'f22_17'),
(536, 22, 'Pumpkin', 'ฟักทอง', 'Fák-thaawng', '', '', 'f22_18'),
(537, 22, 'Mushroom', 'เห็ด', 'Hèt', '', '', 'f22_19'),
(538, 22, 'Chili', 'พริก', 'Phrík', '', '', 'f22_20'),
(539, 22, 'Red pepper', 'พริกแดง', 'Phrík daaeng', 'pepper - red', '', 'f22_21'),
(540, 22, 'Corn', 'ข้าวโพด', 'Khâao-phôht', '', '', 'f22_22'),
(541, 22, 'Pak-choy', 'ผักกวางตุ้ง', 'Phàk-gwaang-dtôong', '', '', 'f22_23'),
(542, 22, 'Holy basil', 'กระเพรา', 'Grà-phrao', '', 'Often shortened to ''gà-phrao''.', 'f22_24'),
(543, 22, 'Sweet basil / Thai basil', 'โหระพา', 'Hŏhr-rá-phaa', '', '', 'f22_25'),
(544, 22, 'Lemon basil', 'แมงลัก', 'Maaeng-lák', '', '', 'f22_26'),
(545, 22, 'Mint', 'สะระแหน่', 'Sà-rá-nàae', '', '', 'f22_27'),
(546, 22, 'Purple eggplant', 'มะเขือม่วง', 'Má-khĕuua mûaang', 'eggplant - purple', '', 'f22_28'),
(547, 22, 'Long eggplant', 'มะเขือยาว', 'Má-khĕuua yaao', 'eggplant - long', '', 'f22_29'),
(548, 22, 'Sweet potato', 'มันเทศ', 'Man thâet', 'potato - foreign', '', 'f22_30'),
(549, 22, 'Garlic', 'กระเทียม', 'Grà-thiiam', '', '', 'f22_31'),
(550, 22, 'Ginger', 'ขิง', 'Khĭing', '', '', 'f22_32'),
(551, 22, 'Lemongrass', 'ตะไคร้', 'Dtà-khrái', '', '', 'f22_33'),
(552, 23, 'Fish', 'ปลา', 'Bplaa', '', '', 'f23_1'),
(553, 23, 'Beef', 'เนื้อ', 'Neúua', '', '', 'f23_2'),
(554, 23, 'Chicken', 'ไก่', 'Gài', '', '', 'f23_3'),
(555, 23, 'Pork', 'หมู', 'Mŭu', '', '', 'f23_4'),
(556, 23, 'Mutton', 'แกะ', 'Gàe', '', '', 'f23_5'),
(557, 23, 'Shrimp/prawn', 'กุ้ง', 'Gôong', '', '', 'f23_6'),
(558, 23, 'Rice', 'ข้าว', 'Khâao', '', '', 'f23_7'),
(559, 23, 'Sticky rice', 'ข้าวเหนียว', 'Khâao niăao', 'rice - sticky', '', 'f23_8'),
(560, 23, 'Nuts/beans', 'ถั่ว', 'Thùaa', '', '', 'f23_9'),
(561, 23, 'Egg', 'ไข่', 'Khài', '', '', 'f23_10'),
(562, 23, 'Peanut', 'ถั่วลิสง', 'Thùaa-lí-sŏhng', '', '', 'f23_11'),
(563, 23, 'Tofu', 'เต้าหู้', 'Dtâo-hûu', '', '', 'f23_12'),
(564, 23, 'Coconut milk', 'กะทิ', 'Gà-thí', '', '', 'f23_13'),
(565, 23, 'Stir fry', 'ผัด', 'Phàt', '', '', 'f23_14'),
(566, 23, 'Boiled', 'ต้ม', 'Dtôhm', '', '', 'f23_15'),
(567, 23, 'Deep fried', 'ทอด', 'Thâawt', '', '', 'f23_16'),
(568, 23, 'Steamed', 'นึ่ง', 'Nêung', '', '', 'f23_17'),
(569, 23, 'Fish sauce', 'น้ำปลา', 'Náam bplaa', 'liquid - fish', '', 'f23_19'),
(570, 23, 'Shrimp paste', 'กะปิ', 'Gà-bpì', '', '', 'f23_20'),
(571, 23, 'A mix of lemongrass, chilli, galangal and Kaffir lime', 'ต้มยำ', 'Dtôhm yum', 'boil - mix', '', 'f23_18'),
(572, 23, 'Tom yum soup with prawn or shrimp', 'ต้มยำกุ้ง', 'Dtôhm yum gôong', 'boil - mix - shrimp / prawn', '', 'f23_37'),
(573, 23, 'Soup with chicken, coconut milk and galangal', 'ต้มข่าไก่', 'Dtôhm khàa gài', 'boil - galangal - chicken', '', 'f23_38'),
(574, 23, 'Green papaya salad', 'ส้มตำ', 'Sôhm-dtam', 'sour - pound with pestle', '', 'f23_21'),
(575, 23, 'Fried rice', 'ข้าวผัด', 'Khâao phàt', 'rice - fry', '', 'f23_22'),
(576, 23, 'Fried egg', 'ไข่ดาว', 'Khài daao', 'egg - star', '', 'f23_23'),
(577, 23, 'Steamed fish', 'ปลานึ่ง', 'Bplaa nêung', 'fish - steam', '', 'f23_24'),
(578, 23, 'Curry', 'แกง', 'Gaeng', '', '', 'f23_25'),
(579, 23, 'Green curry', 'แกงเขียวหวาน', 'Gaeng khĭaao wăan', 'curry - green - sweet', '', 'f23_26'),
(580, 23, 'Red curry', 'แกงเผ็ด', 'Gaeng phèt', 'curry - spicy hot', '', 'f23_27'),
(581, 23, 'Fish entrail soup', 'แกงไตปลา', 'Gaeng dtai bplaa', 'curry - kidney - fish', '', 'f23_35'),
(582, 23, 'Sour soup', 'แกงส้ม', 'Gaeng sôhm', 'curry - sour', 'Made with tamarind.', 'f23_36'),
(583, 23, 'Rice noodle soup', 'ก๋วยเตี๋ยวน้ำ', 'Gŭay-dtĕow náam', 'rice noodles - liquid', '', 'f23_28'),
(584, 23, 'Rice noodles without soup', 'ก๋วยเตี๋ยวแห้ง', 'Gŭay-dtĕow hâaeng', 'rice noodles - dry', '', 'f23_29'),
(585, 23, 'Soup with wide flat rice noodles', 'ก๋วยเตี๋ยวเส้นใหญ่', 'Gŭay-dtĕow sên yài', 'rice noodles - noodles - big', '', 'f23_30'),
(586, 23, 'Soup with medium size rice noodles', 'ก๋วยเตี๋ยวเส้นเล็ก', 'Gŭay-dtĕow sên lék', 'rice noodles - noodles - small', '', 'f23_31'),
(587, 23, 'Soup with vermicelli rice noodles', 'ก๋วยเตี๋ยวเส้นหมี่', 'Gŭay-dtĕow sên mèe', 'rice noodles - noodles - vermicelli', '', 'f23_32'),
(588, 23, 'Egg noodles', 'บะหมี่', 'Bà-mèe', '', '', 'f23_33'),
(589, 23, 'Thin rice noodles served with various toppings', 'ขนมจีน', 'Khà-nŏhm jiin', 'dessert - Chinese', '', 'f23_34'),
(590, 23, 'Chicken stir-fried in red curry paste', 'ไก่ผัดพริกแกง', 'Gài phàt prík gaeng', 'chicken - fry - chilli - curry', '', 'f23_39'),
(591, 23, 'Fried wide rice noodles with pak kana and soy sauce', 'ผัดซีอิ๊ว', 'Phàt see-íu', 'stir fried - soy sauce', '', 'f23_40'),
(592, 23, 'Spicy salad made with ground meat and herbs', 'ลาบ', 'Lâap', '', '', 'f23_41'),
(593, 23, 'Basil chicken with fried egg', 'ผัดกระเพราไก่ไข่ดาว', 'Phàt grà-phrao gài khài daao', 'stir fried - basil - chicken - egg - star', '', 'f23_42'),
(594, 23, 'Dessert / sweet item', 'ขนมหวาน', 'Khà-nŏhm wăan', 'dessert - sweet', '', 'f23_43'),
(595, 24, 'Drinking water', 'น้ำดื่ม', 'Náam dèum', 'water - drink', '', 'f24_1'),
(596, 24, 'Glass', 'แก้ว', 'Gâeo', '', '', 'f24_2'),
(597, 24, 'Cup', 'ถ้วย', 'Thûay', '', '', 'f24_3'),
(598, 24, 'Coffee', 'กาแฟ', 'Gaa-fae', '', '', 'f24_4'),
(599, 24, 'Black coffee', 'กาแฟดำ', 'Gaa-fae dam', 'coffee - black', '', 'f24_5'),
(600, 24, 'Ancient coffee', 'กาแฟโบราณ', 'Gaa-fae boh-raan', 'coffee - ancient', 'Strong filter coffee mixed with condensed milk and ice.', 'f24_6'),
(601, 24, 'Iced coffee with condensed milk and sugar', 'กาแฟเย็น', 'Gaa-fae yen', 'coffee - cold', '', 'f24_7'),
(602, 24, 'Cappuccino', 'คาปูชิโน่', 'Kha-pu-chi-nô', '', '', 'f24_16'),
(603, 24, 'Tea', 'น้ำชา', 'Náam chaa', 'liquid - tea', '', 'f24_8'),
(604, 24, 'Green Tea', 'ชาเขียว', 'Chaa kiăao', 'tea - green', '', 'f24_9'),
(605, 24, 'Iced green tea', 'ชาเขียวเย็น', 'Chaa kiăao yen', 'tea - green - cold', '', 'f24_10'),
(606, 24, 'Milk', 'น้ำนม', 'Náam nohm', 'liquid - milk', '', 'f24_11'),
(607, 24, 'Sugarcane juice', 'น้ำอ้อย', 'Náam âawy', 'liquid - sugarcane', '', 'f24_12'),
(608, 24, 'Fruit juice', 'น้ำผลไม้', 'Náam phŏn-lá-mái', 'liquid - fruit', '', 'f24_19'),
(609, 24, 'Smoothie', 'น้ำปั่น', 'Náam bpàn', 'liquid - spin / churn', '', 'f24_13'),
(610, 24, 'Fruit smoothie', 'น้ำผลไม้ปั่น', 'Náam phŏn-lá-mái bpàn', 'liquid - fruit - spin / churn', '', 'f24_14'),
(611, 24, 'Orange smoothie', 'ส้มปั่น', 'Sôhm bpàn', 'orange - spin / churn', '', 'f24_15'),
(612, 24, 'Ice', 'น้ำแข็ง', 'Náam khăeng', 'water - hard', '', 'f24_18'),
(613, 24, 'Alcohol', 'เหล้า', 'Lâo', '', '', 'f24_17'),
(614, 24, 'Beer', 'เบียร์', 'Bia', '', '', 'f24_20'),
(615, 24, 'Elephant beer', 'เบียร์ช้าง ', 'Bia cháang', 'beer - elephant', '', 'f24_21'),
(616, 24, 'Whiskey', 'วิสกี้', 'Whís-gêe', '', '', 'f24_22'),
(617, 25, 'Can I see a menu?', 'ฉันขอดูเมนูหน่อยได้ไหมคะ', 'Chăn kŏr duu menu nòy dâi mái khá?', 'I - request - see - menu - softening particle - can - or not - polite particle? ', '', 'f25_1'),
(618, 25, 'Can I sit here?', 'ขอนั่งที่นี่ได้ไหมคะ', 'Kŏr nâng thîi-nîi dâi mái khá?', 'request - sit - here - can - or not - polite particle?', '', 'f25_2'),
(619, 25, 'Not spicy thanks.', 'ไม่เผ็ด', 'Mâi phèt', 'not - spicy', '', 'f25_3'),
(620, 25, 'Can you add some egg?', 'ขอเพิ่มไข่หน่อยได้ไหมคคะ', 'Kŏr phêerm khài nòy dâi mái khá?', 'request - add - egg - softening particle - can - or not - polite particle?', '', 'f25_4'),
(621, 25, 'Can I have another bowl of rice?', 'ขอข้าวเพิ่มอีกถ้วยได้ไหมคะ', 'Kŏr khâao phêerm èek thûuay dâi mái khá?', 'request - rice - more - another - cup - can - or not - polite particle', '', 'f25_5'),
(622, 25, 'Can we have some water please?', 'ขอน้ำหน่อยได้ไหมคะ', 'Kŏr náam nòy dâi mái khá?', 'request - water - softening particle - can - or not - polite particle?', '', 'f25_6'),
(623, 25, 'Can we have five coffees?', 'ขอกาแฟห้าแก้วได้ไหมคะ', 'Kŏr gaa-fae hâa gâeo dâi mái khá?', 'request - coffee - five - cup - can - or not - polite particle?', '', 'f25_7'),
(624, 25, 'Can we have two plates of fish laap and one green papaya salad.', 'ขอลาบปลา 2 จานกับส้มตำ 1 จานได้ไหมคะ', 'Kŏr lâap bplaa sŏng jaan gàp sôhm-dtam nèung jaan dâi mái khá?', 'request - laap - fish - two - plate - with - papaya salad - one - plate - can - or not - polite particle?', '', 'f25_8'),
(625, 25, 'Without sugar.', 'ไม่ใส่น้ำตาล', 'Mâi sài náam-dtaan', 'not - put - sugar', '', 'f25_9'),
(626, 25, 'Without ice.', 'ไม่ใส่น้ำแข็ง', 'Mâi sài náam khăeng', 'not - put - water - hard', '', 'f25_10'),
(627, 25, 'That''s enough.', 'พอแล้ว', 'Phaaw láew.', 'enough - already', '', 'f25_11'),
(628, 25, 'Just a little.', 'นิดเดียว', 'Nít diaao', 'little - alone', '', 'f25_12'),
(629, 25, 'Can I have the bill please?', 'เช็คบิลด้วยค่ะ', 'Chek-bin dûay khâ', 'bill - particle used at the end of a request - polite particle', '', 'f25_13'),
(630, 25, 'Can we pay separately?', 'เราจะแบ่งกันจ่ายได้ไหมคะ', 'Rao jà bàeng gan jàai dâi mái khá?', 'we - want to - divide - separate - pay - can - or not - polite particle?', '', 'f25_14'),
(631, 25, 'Takeaway', 'ใส่กล่อง', 'Sài glàawng', 'put - takeaway container', '', 'f25_15'),
(632, 25, 'Eat here', 'ทานที่นี่', 'Thaan thîi-nîi', 'eat - here', '', 'f25_16'),
(633, 25, 'What''s good here?', 'ที่นี่อะไรอร่อยคะ', 'Thîi-nîi à-rai à-ròi khá?', 'here - what - tasty - polite particle?', '', 'f25_17'),
(634, 25, 'Do you have any vegetarian food?', 'มีอาหารเจไหมคะ', 'Mii aa-hăan jaeh mái khá?', 'have - food - vegetarian - or not - polite particle?', 'The word ''jaeh'' means free from animal products, including eggs and milk. It is the most commonly understood word for ''vegetarian'' since many Thais eat this way during the vegetarian festival in October. Dairy products are uncommon in Thailand, but you can ask for egg to be added if you wish.', 'f25_18'),
(635, 25, 'Is this vegetarian?', 'อาหารนี้เจไหมคะ', 'Aa-hăan níi jaeh mái khá?', 'food - this - vegetarian - or not - polite particle?', '', 'f25_19'),
(636, 25, 'I don''t eat meat.', 'ฉันไม่ทานเนื้อสัตว์ค่ะ', 'Chăn mâi thaan néuua sàt khâ', 'I - not - eat - flesh - animal - polite particle', '', 'f25_20'),
(637, 25, 'I only eat fish.', 'ฉันทานแต่ปลาค่ะ', 'Chăn thaan dtàae bplaa khâ', 'I - eat - only - fish - polite particle', '', 'f25_21'),
(638, 25, 'I don''t eat seafood', 'ฉันไม่ทานอาหารทะเลค่ะ', 'Chăn mâi thaan aa-hăan thá-laeh khâ', 'I - not - eat - food - sea - polite particle', '', 'f25_22'),
(639, 25, 'Does this have egg in it?', 'อาหารจานนี้ใส่ไข่ไหมคะ', 'Aa-hăan jaan níi sài khài mái khá?', 'food - dish - this - put - egg - or not - polite particle?', '', 'f25_23'),
(640, 25, 'I''m allergic to nuts.', 'ฉันแพ้ถั่วค่ะ', 'Chăn pháae thùaa khâ ', 'I - allergic to - nuts - polite particle', '', 'f25_24'),
(641, 25, 'I''m allergic to milk.', 'ฉันแพ้นมค่ะ', 'Chăn pháae nom khâ', 'I - allergic to - milk - polite particle', '', 'f25_25');