INSERT INTO `phrasesM` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(634, 25, 'Is this vegetarian?', 'อาหารนี้เจไหมครับ', 'Aa-hăan níi jaeh mái khráp?', 'food - this - vegetarian - or not - polite particle?', '', 'm25_19'),
(635, 25, 'I don''t eat meat.', 'ผมไม่ทานเนื้อสัตว์ครับ', 'Phŏhm mâi thaan néuua sàt khráp', 'I - not - eat - flesh - animal - polite particle', '', 'm25_20'),
(636, 25, 'I only eat fish.', 'ผมทานแต่ปลาครับ', 'Phŏhm thaan dtàae bplaa khráp', 'I - eat - only - fish - polite particle', '', 'm25_21'),
(637, 25, 'I don''t eat seafood', 'ผมไม่ทานอาหารทะเลครับ', 'Phŏhm mâi thaan aa-hăan thá-laeh khráp', 'I - not - eat - food - sea - polite particle', '', 'm25_22'),
(638, 25, 'Does this have egg in it?', 'อาหารจานนี้ใส่ไข่ไหมครับ', 'Aa-hăan jaan níi sài khài mái khráp?', 'food - dish - this - put - egg - or not - polite particle?', '', 'm25_23'),
(639, 25, 'I''m allergic to nuts.', 'ผมแพ้ถั่วครับ', 'Phŏhm pháae thùaa khráp ', 'I - allergic to - nuts - polite particle', '', 'm25_24'),
(640, 25, 'I''m allergic to milk.', 'ผมแพ้นมครับ', 'Phŏhm pháae nom khráp', 'I - allergic to - milk - polite particle', '', 'm25_25'),
(641, 26, 'Are you hungry? Very hungry.', 'คุณหิวไหมครับ หิวมากครับ', 'Khun hĭu mái khráp? Hĭu mâak khráp.', 'you - hungry - or not - polite particle? hungry - very - polite particle', '', 'm26_1'),
(642, 26, 'Thirsty', 'หิวน้ำ', 'Hĭu náam', 'hungry (for) - water / liquid', '', 'm26_2'),
(643, 26, 'It''s very delicious.', 'อร่อยมากเลยครับ', 'À-ròi mâak leeuy khráp', 'tasty - very - exclamation - polite particle', '', 'm26_3'),
(644, 26, 'I''m full.', 'ผมอิ่มแล้วครับ', 'Phŏhm ìm láew khráp', 'I - full - already - polite particle', '', 'm26_4'),
(645, 26, 'I''m not full yet.', 'ผมยังไม่อิ่มครับ', 'Phŏhm yang mâi ìm khráp', 'I - still - not - full - polite particle', '', 'm26_5'),
(646, 26, 'Do you like Thai food? I like some Thai food.', 'คุณชอบอาหารไทยไหมครับ ผมชอบบางอย่างครับ', 'Kun chôrp aa-hăan Thai mái khráp? Phŏhm chôrp baang yàang khráp', 'you - like - food - Thai - or not - polite particle? I - like - some - type - polite particle', '', 'm26_7'),
(647, 26, 'Breakfast', 'อาหารเช้า', 'Aa-hăan cháao', 'food - morning', '', 'm26_8'),
(648, 26, 'Lunch', 'อาหารเที่ยง', 'Aa-hăan thîang', 'food - noon', '', 'm26_9'),
(649, 26, 'Dinner', 'อาหารเย็น', 'Aa-hăan yen', 'food - early evening', '', 'm26_10'),
(650, 26, 'Have a snack', 'กินเล่น', 'Gin lên', 'eat - play', '', 'm26_11'),
(651, 26, 'Restaurant', 'ร้านอาหาร', 'Ráan aa-hăan', 'shop - food', '', 'm26_12'),
(652, 26, 'Classifier for cups', 'ถ้วย', 'Thûay', '', '', 'm26_13'),
(653, 26, 'Dish / plate', 'จาน', 'Jaan', '', '', 'm26_14'),
(654, 26, 'Spoon', 'ช้อน', 'Cháawn', '', '', 'm26_15'),
(655, 26, 'Is it spicy? A little.', 'อันนี้เผ็ดไหมครับ นิดหน่อยครับ', 'An níi phèt mái khráp? Nít-nòy khráp', 'item - this - spicy - or not - polite particle? a little bit - polite particle', '', 'm26_6'),
(656, 26, 'Is it sweet?', 'อันนี้หวานไหมครับ', 'An níi wăan mái khráp?', 'item - this - sweet - or not - polite particle?', '', 'm26_16'),
(657, 26, 'Dessert / sweet item', 'ขนมหวาน', 'Khà-nŏhm wăan', 'dessert - sweet', '', 'm26_17'),
(658, 26, 'Sour', 'เปรี้ยว', 'Bprîaao', '', '', 'm26_18'),
(659, 26, 'Salty', 'เค็ม', 'Khem', '', '', 'm26_19'),
(660, 26, 'Hot (temperature)', 'ร้อน', 'Rórn', '', '', 'm26_20'),
(661, 26, 'Cold (food, drink)', 'เย็น', 'Yen', '', '', 'm26_21'),
(662, 27, 'Is there a guesthouse nearby?', 'มีเกสต์เฮาส์แถวนี้ไหมครับ', 'Mii gàeht-háao thăaeo níi mái khráp?', 'is there - guesthouse - area - this - or not - polite particle?', '', 'm27_1'),
(663, 27, 'I''m looking for a cheap hotel.', 'ผมกำลังหาโรงแรมถูกๆอยู่ครับ', 'Phŏhm gamlang hăa rohng-raem tòok tòok yùu khráp', 'I - currently - look for - hotel - cheap - cheap - currently - polite particle', '', 'm27_2'),
(664, 27, 'Can you recommend a good place to stay?', 'ช่วยแนะนำที่พักดีๆหน่อยได้ไหมครับ', 'Chûay náe-nam thîi-phák dii dii nòy dâi mái khráp?', 'help - recommend -  accommodation - good - good - softening particle - can - or not?', '', 'm27_3'),
(665, 27, 'Are there any home stays around here?', 'มีโฮมสเตย์แถวนี้ไหมครับ', 'Mii hohm-sa-tay thăaeo níi mái khráp?', 'is there - homestay - area - this - or not - polite particle?', '', 'm27_4'),
(666, 27, 'Do you have any rooms available?', 'มีห้องว่างไหมครับ', 'Mii hâawng wâang mái khráp?', 'have - room - available - or not - polite particle?', '', 'm27_5'),
(667, 27, 'We booked online.', 'เราจองผ่านอินเตอร์เน็ตแล้วครับ', 'Rao jaawng phàan in-thuuhr-nét láew khráp ', 'we - book - via - internet - already - polite particle', '', 'm27_6'),
(668, 27, 'Single room', 'ห้องเดี่ยว', 'Hâawng dìaao', 'room - single', '', 'm27_7'),
(669, 27, 'Double room', 'ห้องคู่', 'Hâawng khûu', 'room - couple', '', 'm27_8'),
(670, 27, 'Twin room', 'ห้องทวิน', 'Hâawng săwng dtiiang', 'room - two - bed', '', 'm27_9'),
(671, 27, 'Dorm', 'หอพัก', 'Hăaw phák', 'hall - rest', '', 'm27_10'),
(672, 27, 'How many people?', 'กี่คนครับ', 'Gìi khon khráp?', 'how many - people - polite particle', '', 'm27_11'),
(673, 27, 'How many nights?', 'กี่คืนครับ?', 'Gìi kheuun khráp?', 'how many - night - polite particle?', '', 'm27_12'),
(674, 27, 'Two people, one night.', 'สองคน หนึ่งคืน', 'Săawng khon nèung kheuun', 'two - people - one - night', '', 'm27_13'),
(675, 27, 'How much per night?', 'คืนละกี่บาทครับ', 'Kheuun lá gìi bàat khráp?', 'night - each - how many - baht - polite particle?', '', 'm27_14'),
(676, 27, 'How much per week?', 'อาทิตย์ละกี่บาทครับ', 'Aa-thít lá gìi bàat khráp?', 'week - each - how many - baht - polite particle?', '', 'm27_15'),
(677, 27, 'Room with a fan', 'ห้องมีพัดลม', 'Hâawng mii phát-lohm', 'room - have - fan', '', 'm27_16'),
(678, 27, 'Room with air conditioning', 'ห้องมีแอร์', 'Hâawng mii aae', 'room - have - air conditioning', '', 'm27_17'),
(679, 27, 'Do you want air conditioning?', 'คุณต้องการห้องที่มีแอร์ไหมครับ', 'Khun dtâwng-gaan hâwng thîi mii aae mái khráp?', 'you - want - room - that - have - air conditioning - or not - polite particle?', '', 'm27_18'),
(680, 27, 'Do you have wifi?', 'คุณมีWIFIไหมครับ', 'Khun mii wi-fi mái khráp?', 'you - have - wifi - or not - polite particle?', '', 'm27_19'),
(681, 27, 'Wifi password', 'รหัสWIFI', 'Rá-hàt wi-fi', 'code - wifi', '', 'm27_20'),
(682, 27, 'Is there hot water (showers)?', 'มีเครื่องทำน้ำอุ่นไหมครับ', 'Mii khrêuuang tham náam òon mái khráp?', 'is there - machine - make - water - heat - or not - polite particle?', '', 'm27_21'),
(683, 27, 'Can I see the room?', 'ผมขอดูห้องหน่อยได้ไหมครับ', 'Phŏhm kŏr doo hâawng nòy dâi mái khráp?', 'I - request - see - room - softening particle - can - or not - polite particle?', '', 'm27_22'),
(684, 27, 'Can I see another room?', 'ผมขอดูห้องอื่นหน่อยได้ไหมครับ', 'Phŏhm kŏr doo hâawng èuun nòy dâi mái khráp?', 'I - request - see - room - another - softening particle - can - or not - polite particle?', '', 'm27_23'),
(685, 27, 'I would like a cleaner room.', 'ผมขอห้องที่สะอาดกว่านี้ได้ไหมครับ', 'Phŏhm kŏr hâawng thîi sà-àat gwàa níi dâi mái khráp?', 'I - request - room - that - clean - more than - this -  can - or not - polite particle?', '', 'm27_24'),
(686, 27, 'Bigger', 'ใหญ่กว่า', 'Yài gwàa', 'big - more than', '', 'm27_25'),
(687, 27, 'Quiter', 'เงียบกว่า', 'Ngîiap gwàa', 'quiet - more than', '', 'm27_26'),
(688, 27, 'Cheaper', 'ถูกกว่า', 'Thùuk gwàa', 'cheap - more than', '', 'm27_27'),
(689, 27, 'Room with a bathroom', 'ห้องที่มีห้องน้ำ', 'Hâawng thîi mii hâawng-náam ', 'room - that - have - bathroom', '', 'm27_28'),
(690, 27, 'This room smells like smoke.', 'ห้องนี้มีกลิ่นควัน', 'Hâawng níi mii glìn khwan', 'room - this - have - smell - smoke', '', 'm27_29'),
(691, 27, 'Can I open the window?', 'ผมเปิดหน้าต่างได้ไหมครับ', 'Phŏhm bpèrt nâa-dtàang dâi mái khráp?', 'I - open - window - can - or not - polite particle?', '', 'm27_30'),
(692, 27, 'Can I move to another room?', 'ผมขอย้ายไปห้องอื่นได้ไหมครับ', 'Phŏhm kŏr yáai bpai hâawng èuun dâi mái khráp?', 'I - request - transfer - go - room - another - can - or not - polite particle', '', 'm27_31'),
(693, 27, 'Can I have another blanket?', 'ขอผ้าห่มเพิ่มได้ไหมครับ', 'Kŏr phâa-hòhm phêerm dâi mái khráp?', 'request - blanket - add - can - or not - polite particle?', '', 'm27_32'),
(694, 27, 'Can we have an extra bed?', 'ขอเตียงเสริมได้ไหมครับ', 'Kŏr dtiiang sĕerm dâi mái khráp?', 'request - bed - add - can - or not - polite particle?', '', 'm27_33'),
(695, 27, 'I''ll take it.', 'ผมจะเอาอันนี้ครับ', 'Phŏhm jà ao an-níi khráp', 'I - want to - take - this one - polite particle', '', 'm27_34'),
(696, 27, 'I want to go and look at some other places.', 'ผมจะไปหาที่อื่น', 'Phŏhm jà bpai hăa thîi èuun', 'I - want to - go - look for - place - another', '', 'm27_35'),
(697, 27, 'I''d like to stay another night.', 'ผมจะอยู่อีกคืน', 'Phŏhm jà yùu èek kheuun', 'I - want to - stay - another - night', '', 'm27_36'),
(698, 27, 'Can I leave my bags here?', 'ผมขอฝากกระเป๋าไว้ที่นี้ได้ไหมครับ', 'Phŏhm kŏr fàak grà-bpăo wái thîi-níi dâi mái khráp?', 'I - request - leave - bag - for future - here - can - or not - polite particle?', 'One usage of the word ''wái'' is to imply that something will happen in the future or is being done for the future. ', 'm27_37'),
(699, 27, 'Where can I change money?', 'ผมจะแลกเงินได้ที่ไหนครับ', 'Phŏhm jà lâek ngern dâi thîi năi khráp?', 'I - future marker - exchange - money - can - at (place) - which - polite particle?', '', 'm27_38'),
(700, 27, 'Is there a laundry service?', 'มีบริการซักรีดไหมครับ', 'Mii baaw-rí-gaan sák rêet mái khráp', 'is there - service - wash (clothes) - iron - or not - polite particle?', '', 'm27_39'),
(701, 27, 'I left my key in the room.', 'ผมลืมกุญแจไว้ในห้องครับ', 'Phŏhm leuum goon-jaae wái nai hâawng khráp', 'I - forget - key - put - in - room - polite particle', '', 'm27_40'),
(702, 28, 'Car', 'รถยนต์', 'Rót yohn', 'vehicle - motorised', '', 'm28_1'),
(703, 28, 'Drive', 'ขับ', 'Khàp', '', '', 'm28_2'),
(704, 28, 'Bicycle', 'จักรยาน', 'Jàk-grà-yaan', '', 'Usually pronouned ''jàk-gà-yaan''.', 'm28_3'),
(705, 28, 'Go by bicycle', 'ไปโดยจักรยาน', 'Bpai dooy jàk-grà-yaan', 'go - by means of - bicycle', '', 'm28_4'),
(706, 28, 'Walk', 'เดิน', 'Deun', '', '', 'm28_5'),
(707, 28, 'Taxi', 'แท็กซี่', 'Tháek-sîi', '', '', 'm28_6'),
(708, 28, 'How much to go to Victory Monument?', 'ไปอนุสาวรีย์ชัยสมรภูมิกี่บาทครับ', 'Bpai à-noo-săa-wá-ree chai sà-măaw-rá-phuum gìi bàat khráp?', 'go - monument - victory - battlefield - how many - baht - polite particle?', '', 'm28_7'),
(709, 28, 'Take me to Hua Lumphong station, please.', 'ช่วยพาผมไปสถานีหัวลำโพงหน่อยครับ', 'Chûay phaa phŏhm bpai sà-thăa-nii hŭaa lam-phong nòy khráp', 'help - take - me - go - station - Hua Lumphong - softening particle - polite particle', '', 'm28_8'),
(710, 28, 'Please put the meter on.', 'ช่วยกดมิเตอร์ด้วยนะครับ', 'Chûay gòht míi-dteu dûay ná khráp', 'help - press - meter - request particle - softening particle - polite particle', '', 'm28_10'),
(711, 28, 'How long will it take?', 'ใช้เวลานานแค่ไหนครับ?', 'Chái waeh-laa naan khâae năi khráp?', 'use - time - long time - to the extent of - which - polite particle?', '', 'm28_11'),
(712, 28, 'Stop here.', 'หยุดตรงนี้ครับ', 'Yòot dtrohng-níi khráp', 'stop - right here - polite particle', '', 'm28_12'),
(713, 28, 'I''ll be back in a moment.', 'เดี๋ยวมารับ / แป๊บหนึ่งรับ', 'Dĭaao maa khráp / Bpáaep nèung khráp', 'a moment - come - polite particle / for a moment - one - polite particle', '', 'm28_13'),
(714, 28, 'My friend is coming.', 'เพื่อนผมกำลังจะมาครับ', 'Phêuuan phŏhm gamlang-jà maa khráp ', 'friend - I - about to - come - polite particle', '', 'm28_14'),
(715, 28, 'Bus', 'รถเมล์  ', 'Rót-maey', '', '', 'm28_15'),
(716, 28, 'Two-row minibus', 'รถสองแถว', 'Rót săawng thăew', 'vehicle - two - row', '', 'm28_16'),
(717, 28, 'Coach', 'รถทัวร์', 'Rót thuaa', 'vehicle - tour', '', 'm28_17'),
(718, 28, 'Bus station', 'สถานีรถประจำทาง', 'Sà-thăa-nii rót bprà-jam thaang', 'station - vehicle - regular - way', '', 'm28_18'),
(719, 28, 'Bus stop', 'ป้ายรถเมล์', 'Bpâai rót-maey', 'vehicle stop - bus', '', 'm28_19'),
(720, 28, 'Bus number', 'สาย', 'Săai', '', '', 'm28_20'),
(721, 28, 'Go by bus', 'ไปโดยรถเมล์', 'Bpai dooy rót-maey', 'go - by means of - bus', '', 'm28_21'),
(722, 28, 'Take bus number 51.', 'ขึ้นรถเมล์สายห้าสิบเอ็ดครับ', 'Khêun rót-maey săai hâa-sìp-èt khráp', 'board - bus - number - fifty one - polite particle', '', 'm28_22'),
(723, 28, 'Ticket', 'ตั๋ว', 'Dtŭa', '', '', 'm28_23'),
(724, 28, 'One way', 'เที่ยวเดียว', 'Thîaao diaao', 'trip - single', '', 'm28_24'),
(725, 28, 'Return', 'ไป-กลับ', 'Bpai glàp', 'go - return', '', 'm28_25'),
(726, 28, 'Where can I buy a ticket?', 'ผมซื้อตั๋วได้ที่ไหนครับ', 'Phŏhm séuu dtŭa dâi thîi năi khráp?', 'I - buy - ticket - can - at place - which - polite particle?', '', 'm28_26'),
(727, 28, 'Do you go to Nonthaburi?', 'คุณไปนนทบุรีไหมครับ', 'Khun bpai Nohn-thá-bòo-ree mái khráp?', 'you - go - Nonthaburi - or not - polite particle?', '', 'm28_27'),
(728, 28, 'What time will the next bus to Satun leave?', 'รถเมล์ไปสตูลคันต่อไปออกกี่โมงครับ', 'Rót-maey bpai Sà-dtuun khan dtàaw-bpai àawk gìi mohng khráp?', 'bus - go - Satun - classifier - next - exit - how many - hour - polite particle?', '', 'm28_28'),
(729, 28, 'Does it stop for dinner?', 'รถจะหยุดสำหรับอาหารเย็นไหมครับ', 'Rót jà yòot săm-ràp aa-hăan-yen mái khráp?', 'vehicle - future marker - stop - for the purpose of - dinner - or not - polite particle?', '', 'm28_29'),
(730, 28, 'How much will it cost to bring my bicycle?', 'เอารถจักรยานขึ้นคิดเงินเท่าไหร่ครับ', 'Ao rót jàk-gàa-yaan khêun khít ngern thâo rai khráp?', 'bring - vehicle - bicycle - board - calculate - money - equal to - what - polite particle?', '', 'm28_30'),
(731, 28, 'It hasn''t come yet.', 'มันยังไม่มาครับ', 'Mun yang mâi maa khráp', 'it - still - not - come - polite particle', '', 'm28_31'),
(732, 28, 'It''s going to arrive late.', 'มันจะมาสายครับ', 'Mun jà maa săai khráp', 'it - future marker - come - late - polite particle', '', 'm28_32'),
(733, 29, 'Boat', 'เรือ', 'Reuua', '', '', 'm29_1'),
(734, 29, 'Ferry', 'เรือเฟอร์รี่', 'Reuua fuh-rîi', 'boat - ferry', '', 'm29_2'),
(735, 29, 'Go by boat', 'ไปทางเรือ', 'Bpai thaang reuua', 'go - way - boat', '', 'm29_3'),
(736, 29, 'Book a seat on the boat', 'จองตั๋วขึ้นเรือ', 'Jaawng dtŭa khêun reuua', 'book - ticket - board - boat', '', 'm29_4'),
(737, 29, 'Jetty/harbor', 'ท่าเรือ', 'Thâa reuua', 'pier - boat', '', 'm29_5'),
(738, 29, 'Train', 'รถไฟ', 'Rót fai', 'vehicle - fire', '', 'm29_6'),
(739, 29, 'Sky train', 'รถไฟฟ้า', 'Rót-fai fáa', 'train - sky', '', 'm29_7'),
(740, 29, 'Train station', 'สถานีรถไฟ', 'Sà-thăa-nii rót-fai', 'station - train', '', 'm29_8'),
(741, 29, 'Is there a BTS station near here?', 'มีสถานีรถไฟฟ้าแถวนี้ไหมครับ', 'Mii sà-thăa-nii rót-fai fáa thăaeo níi mái khráp?', 'is there - station - train - sky - area - this - or not - polite particle?', '', 'm29_9'),
(742, 29, 'Platform', 'ชานชาลา', 'Chaan-chaa-làa', '', '', 'm29_10'),
(743, 29, 'Carriage', 'ตู้โดยสาร', 'Dtûu dooy-săan', 'train compartment - travel as a passenger', '', 'm29_11'),
(744, 29, 'First class sleeper', 'เตียงนอนชั้นหนึ่ง', 'Dtiiang norn chán nèung', 'berth - sleep - class - one', '', 'm29_12'),
(745, 29, 'Second class sleeper', 'เตียงนอนชั้นสอง', 'Dtiiang norn chán săawng', 'berth - sleep - class -two', '', 'm29_13'),
(746, 29, 'Second class seat', 'ที่นั่งชั้นสอง', 'Thîi nâng chán săawng', 'place - sit - class - two', '', 'm29_14'),
(747, 29, 'Upper bunk', 'เตียงบน', 'Dtiiang bohn', 'berth - top', '', 'm29_15'),
(748, 29, 'Lower bunk', 'เตียงล่าง', 'Dtiiang lâang', 'berth - below', '', 'm29_16'),
(749, 29, 'Get on the train', 'ขึ้นรถไฟ', 'Khêun rót-fai', 'ascend - train', '', 'm29_17'),
(750, 29, 'Get off at Siam square', 'ลงที่สยามสแคว', 'Long thîi Sà-yăam Sà-khwaae', 'descend - at - Siam Square', '', 'm29_18'),
(751, 29, 'Which platform for the train to Chiang Mai?', 'รถไฟไปเชียงใหม่ขึ้นชานชาลาไหนครับ', 'Rót-fai bpai Chiiang Mài khêun chaan-chaa-làa năi khráp?', 'train - go - Chiang Mai - get on - platform - which - polite particle?', '', 'm29_19'),
(752, 29, 'When is the next train to Ubon Ratchatani?', 'รถไฟขบวนต่อไปที่จะไปอุบลฯจะออกกี่โมงครับ', 'Rót-fai khà-buaan dtàaw-bpai thîi jà bpai Òo-bohn (Râat-chá-thaa-nee) jà àawk gìi mohng khráp?', 'train - classifier - next - that - future marker - go - Ubon (Ratchatani) - future marker - leave - how many - hour - polite particle?', 'It is common to use only the first word of certain major cities.', 'm29_20'),
(753, 29, 'What time does it get to Sisaket?', 'ถึงศรีสะเกษกี่โมงครับ', 'Thĕung Sii-sàa-gèt gìi mohng khráp?', 'arrive - Sisaket - how many - hour - polite particle?', '', 'm29_21'),
(754, 29, 'How long does it take?', 'ใช้เวลานานแค่ไหน', 'Chái waeh-laa naan khâae năi?', 'use - time - long time - to the extent of - which?', '', 'm29_22'),
(755, 29, 'Is there a luggage carriage?', 'มีตู้เก็บสัมภาระไหมครับ', 'Mii dtûu gèp săm-phaa-ráa mái khráp?', 'is there - carriage - store - luggage - or not - polite particle?', '', 'm29_23'),
(756, 29, 'I want to go to Mo Chit station.', 'ผมจะไปสถานีหมอชิตครับ', 'Phŏhm jà bpai sa-thăa-nii măaw-chít khráp', 'I - want to - go - station - mo chit - polite particle', '', 'm29_24'),
(757, 29, 'What station is this?', 'นี่สถานีอะไรครับ', 'Níi sà-thăa-nii à-rai khráp?', 'this - station - what - polite particle?.', '', 'm29_25'),
(758, 29, 'Airplane', 'เครื่องบิน', 'Khrêuang bin', 'machine - fly', '', 'm29_26'),
(759, 29, 'Airport', 'สนามบิน', 'Sà-năam bin', 'field - fly', '', 'm29_27'),
(760, 29, 'Suvarnabhumi airport', 'สนามบินสุวรรณภูมิ', 'Sà-năam-bin Sòo-wan-ná-phum', 'airport - Suvarnabhumi', '', 'm29_28'),
(761, 29, 'Terminal', 'อาคาร', 'Aa-khaan', 'building', '', 'm29_29'),
(762, 29, 'Arrival', 'ขาเข้า', 'Khăa khâo', 'journey - enter', '', 'm29_30'),
(763, 29, 'Departure', 'ขาออก', 'Khăa àawk', 'journey - exit', '', 'm29_31'),
(764, 29, 'Gate 21', 'ประตูยี่สิบเอ็ด', 'Bprà-dtuu yîi sìp èt', 'gate - place - twenty one', '', 'm29_32'),
(765, 29, 'What time is your flight?', 'เที่ยวบินคุณกี่โมงครับ', 'Thîaao bin khun gìi mohng khráp?', 'trip - fly - you - how many - hour - polite particle?', '', 'm29_33'),
(766, 30, 'Place of interest, place to visit', 'ที่เที่ยว', 'Thîi thîaao', 'place - trip', '', 'm30_1'),
(767, 30, 'Excuse me, where is the supermarket?''', 'ขอโทษนะครับ ซุปเปอร์มาเก็ตอยู่ไหนแถวไหนครับ', 'Kŏr-thôt ná khráp, sóop-bpuuhr-maa-gèt yùu thăaeo năi khráp?', 'excuse me - softening particle - polite particle - supermarket - situated - area - which - polite particle?', '', 'm30_2'),
(768, 30, 'Is there a post office around here?', 'มีไปรษณีย์แถวนี้ไหมครับ', 'Mii bprai-sà-nee thăaeo níi mái khráp?', 'is there - post office - area - this - or not - polite particle?', '', 'm30_3'),
(769, 30, 'Which way to Sukhothai?', 'สุโขทัยไปทางไหนครับ', 'Sòo-khŏh-thai bpai thaang năi khráp?', 'Sukhothai - go - way - which - polite particle?', '', 'm30_4'),
(770, 30, 'I''m looking for the ferry terminal', 'ผมกำลังหาท่าขึ้นเรืออยู่ครับ', 'Phŏhm gamlang hăa thâa khêun reuua yùu khráp', 'I - currently - look for - jetty - board - boat - currently - polite particle', '', 'm30_5'),
(771, 30, 'Can you show me on the map?', 'ชี้ให้ผมดูบนแผนที่ได้ไหมครับ', 'Chée hâi phŏhm doo bon phăaen-thîi dâi mái khráp?', 'indicate place - give - me - see - on - map - can - or not - polite particle?', 'The verbs ''hâi .... doo'' together mean ''show''.', 'm30_6'),
(772, 30, 'Go straight', 'ตรงไป', 'Dtrohng bpai', 'straight - go', '', 'm30_7'),
(773, 30, 'Go to the end of the road', 'ไปสุดถนน', 'Bpai sòot thà-nŏn', 'go - end - road', '', 'm30_8'),
(774, 30, 'Turn right', 'เลี้ยวขวา', 'Liáao khwăa', 'turn - right', '', 'm30_9'),
(775, 30, 'Turn left', 'เลี้ยวซ้าย', 'Liáao sáai', 'turn - left', '', 'm30_10'),
(776, 30, 'Turn left on Sukhumvit Road', 'เลี้ยวซ้ายที่ถนนสุขุมวิท', 'Liáao sáai thîi thà-nŏn sòo-khŏom-wít', 'turn - left - at - road - Sukhumvit', '', 'm30_11'),
(777, 30, 'Go through the intersection', 'ผ่านแยกไป', 'Phàan yâek bpai', 'pass by - intersection - go', '', 'm30_12'),
(778, 30, 'Go until you see the petrol station, then turn right', 'ตรงไปจนถึงปั๊มน้ำมันแล้วเลี้ยวขวา', 'Dtrohng bpai john thĕung bpám náam-man láew liáao khwăa', 'straight - go - until - arrive - pump - petrol - next - turn - right', '', 'm30_13'),
(779, 30, 'Go straight ahead, turn left at the traffic lights.', 'ตรงไป เลี้ยงซ้ายหลังผ่านไฟจราจร', 'Dtrohng bpai, liáao sáai lăng phàan fai jà-raa-jawn', 'straight - go, turn - left - behind - pass by - light - traffic', '', 'm30_14'),
(780, 30, 'Turn right after the temple.', 'เลี้ยวขวาหลังผ่านวัด', 'Liáao khwăa lăng phàan wát', 'turn - right - behind - pass by - temple', '', 'm30_15'),
(781, 30, 'Take sawng-thaew number 3', 'นั่งสองแถวเบอร์สาม', 'Nâng săawng thăew ber săam', 'sit - two - rows - number - three', '', 'm30_16'),
(782, 30, 'It''s over there.', 'อยู่ทางโน้น', 'Yùu thaang nóhn', 'situated - way - there', '', 'm30_17'),
(783, 30, 'Go back that way.', 'กลับไปทางโน้น', 'Glàp bpai thaang nóhn', 'return - go - way - there', '', 'm30_18'),
(784, 30, 'On the left', 'อยู่ด้านซ้าย', 'Yùu dtâan sáai', 'situated - side - left', '', 'm30_19'),
(785, 30, 'In front of', 'ข้างหน้า', 'Khâang nâa', 'in the direction of - forward', '', 'm30_20'),
(786, 30, 'Behind', 'หลัง', 'Lăng', '', '', 'm30_21'),
(787, 30, 'Next to', 'ถัดจาก', 'Thàt jàak', 'next - from', '', 'm30_22'),
(788, 30, 'On the corner', 'อยู่ตรงหัวมุม', 'Yùu dtrohng hŭa-moom', 'situated - at - corner', '', 'm30_23'),
(789, 30, 'Opposite', 'ตรงข้าม', 'Dtrohng khâam', 'at - opposite', '', 'm30_24'),
(790, 30, 'Close', 'ใกล้', 'Glâi', '', '', 'm30_25'),
(791, 30, 'Far', 'ไกล', 'Glai', '', '', 'm30_26'),
(792, 30, 'Lane', 'ซอย', 'Soi', '', '', 'm30_27'),
(793, 30, 'Road', 'ถนน', 'Thà-nŏn', '', '', 'm30_28'),
(794, 30, 'Highway', 'ทางหลวง', 'Thaang lŭaang', 'way - royal', '', 'm30_29'),
(795, 30, 'Village', 'หมู่บ้าน', 'Mùu-bâan', '', '', 'm30_30'),
(796, 30, 'City', 'เมือง', 'Meuuang', '', '', 'm30_31'),
(797, 30, 'Area', 'พื้นที่', 'Phéuun thîi', '', '', 'm30_32'),
(798, 30, 'Province', 'จังหวัด', 'Jang-wàt', '', '', 'm30_33'),
(799, 30, 'What road is this?', 'นี่ถนนอะไรครับ', 'Nîi thà-nŏn à-rai khráp?', 'this - road - what - polite particle?', '', 'm30_34'),
(800, 30, 'What village is this?', 'นี่หมู่บ้านอะไรครับ', 'Nîi mùu-bâan à-rai khráp?', 'this - village - what - polite particle?', '', 'm30_35'),
(801, 30, 'How far is it?', 'ไกลแค่ไหนครับ', 'Glai khâae năi khráp?', 'far - to the extent of - which - polite particle?', '', 'm30_36'),
(802, 30, 'Upstairs', 'ข้างบน', 'Khâang bon', 'in the direction of - above', '', 'm30_37'),
(803, 30, 'Downstairs', 'ข้างล่าง', 'Khâang lâang', 'in the direction of - below', '', 'm30_38'),
(804, 30, 'Entrance', 'ทางเข้า', 'Thaang khâo', 'way - enter', '', 'm30_39'),
(805, 30, 'Exit', 'ทางออก', 'Thaang àawk', 'way - exit', '', 'm30_40'),
(806, 30, 'It''s a ten minute walk.', 'ใช้เวลาเดินสิบนาที', 'Chái waeh-laa deun sìp naa-thii', 'use - time - walk - ten - minute', '', 'm30_41'),
(807, 30, 'It''s possible to walk.', 'สามารถเดินได้', 'Săa-mâat deun dâi', 'capable - walk - can', '', 'm30_42'),
(808, 30, 'Traffic jam', 'รถติด', 'Rót dtìt', 'vehicle - stuck', '', 'm30_43'),
(809, 30, 'Where can I rent a motorbike?', 'เช่ามอเตอร์ไซค์ได้ที่ไหน', 'Châo mor-dtuhr-sai dâi thîi năi?', 'rent - motorbike - can - place - where?', '', 'm30_44'),
(810, 31, 'Beach', 'ชายหาด', 'Chai hàat', 'edge - beach', '', 'm31_1'),
(811, 31, 'Sea', 'ทะเล', 'Thá-laeh', '', '', 'm31_2'),
(812, 31, 'Mountain, hill', 'ภูเขา', 'Phuu khăo', '', '', 'm31_3'),
(813, 31, 'Hill', 'เนินเขา', 'Neern khăo', '', '', 'm31_4'),
(814, 31, 'Forest/jungle', 'ป่า', 'Bpàa', '', '', 'm31_5'),
(815, 31, 'Trail', 'ทางดิน / ทางเดิน', 'Thaang din / Thaang deun', 'way - dirt / way - walk', '', 'm31_6'),
(816, 31, 'Rice field', 'นาข้าว', 'Naa khâao', 'rice paddy - rice', '', 'm31_7'),
(817, 31, 'Cave', 'ถ้ำ ', 'Thâm', '', '', 'm31_8'),
(818, 31, 'River', 'แม่น้ำ', 'Mâe náam', 'mother - water', '', 'm31_9'),
(819, 31, 'River mouth', 'ปากเเม่น้ำ', 'Bpàak mâe-náam', 'mouth - river', '', 'm31_10'),
(820, 31, 'Lake', 'ทะเลสาบ', 'Thá-laeh sàap', 'sea - lake', '', 'm31_11'),
(821, 31, 'Waterfall', 'น้ำตก', 'Náam dtòk', 'water - fall', '', 'm31_12'),
(822, 31, 'Fishing', 'ตกปลา', 'Dtòk bplaa', 'to fish - fish', '', 'm31_13'),
(823, 31, 'Scuba diving, diving', 'ดำน้ำ', 'Dam náam', 'dive, submerge - water', '', 'm31_14'),
(824, 31, 'Hiking - mountain', 'ปีนเขา', 'Bpeen khăo', 'climb - hill', '', 'm31_15'),
(825, 31, 'Hiking - forest', 'เดินป่า', 'Deun bpàa', 'walk - forest', '', 'm31_17'),
(826, 31, 'Guide', 'ไกด์', 'Gái', '', '', 'm31_18'),
(827, 31, 'Mosquito net', 'มุ้ง', 'Móong', '', '', 'm31_19'),
(828, 31, 'Cycling', 'ปั่นจักรยาน', 'Bpàn jàk-graa-yaan', 'spin - bicycle', '', 'm31_16'),
(829, 32, 'Family', 'ครอบครัว', 'Khrâawp khruaa', '', '', 'm32_1'),
(830, 32, 'Mother', 'แม่', 'Mâe', '', '', 'm32_2'),
(831, 32, 'Father', 'พ่อ', 'Phâaw', '', '', 'm32_3'),
(832, 32, 'Parents', 'พ่อแม่', 'Phâaw-mâe', '', '', 'm32_4'),
(833, 32, 'Son', 'ลูกชาย', 'Lûuk chaai', 'child - male', '', 'm32_5'),
(834, 32, 'Daughter', 'ลูกสาว', 'Lûuk săo', 'child - female', '', 'm32_6'),
(835, 32, 'Siblings', 'พี่น้อง', 'Phîi náwng', 'older sibling - younger sibling', 'These kinship terms are also commonly used to refer to others outside the scope of the family, usually preceding the name of the person.', 'm32_7'),
(836, 32, 'Older sister', 'พี่สาว', 'Phîi săo', 'older sibling - female', '', 'm32_8'),
(837, 32, 'Older brother', 'พี่ชาย', 'Phîi chaai', 'older sibling - male', '', 'm32_9'),
(838, 32, 'Younger sister', 'น้องสาว', 'Náwng săo', 'younger sibling - female', '', 'm32_10'),
(839, 32, 'Younger brother', 'น้องชาย', 'Náwng chaai', 'younger sibling - male', '', 'm32_11'),
(840, 32, 'Husband (formal)', 'สามี', 'Săa-mii', '', '', 'm32_12'),
(841, 32, 'Husband (informal)', 'ผัว', 'Phŭa', '', '', 'm32_13'),
(842, 32, 'Wife (formal)', 'ภรรยา', 'Phan-rá-yaa', '', '', 'm32_14'),
(843, 32, 'Wife (informal)', 'เมีย', 'Mia', '', '', 'm32_15'),
(844, 32, 'Paternal grandfather', 'ปู่', 'Bpùu', '', '', 'm32_16'),
(845, 32, 'Paternal grandmother', 'ย่า', 'Yâa', '', '', 'm32_17'),
(846, 32, 'Maternal grandfather', 'ตา', 'Dtaa', '', '', 'm32_18'),
(847, 32, 'Maternal grandmother', 'ยาย', 'Yaai', '', '', 'm32_19'),
(848, 32, 'Elder sister of parent', 'ป้า', 'Bpâa', '', '', 'm32_20'),
(849, 32, 'Elder brother of parent', 'ลุง', 'Loong', '', '', 'm32_21'),
(850, 32, 'Younger sister or brother of mother', 'น้า', 'Náa', '', '', 'm32_22'),
(851, 32, 'Elder sister or brother of father', 'อา', 'Aa', '', '', 'm32_23'),
(852, 32, 'How many children do you have?', 'คุณมีลูกกี่คนครับ', 'Khun mii lûuk gìi khon khráp?', 'you - have - child - how many - person classifier - polite particle?', '', 'm32_24'),
(853, 32, 'One son and two daughters.', 'ลูกชายหนึ่งคนและลูกสาวสองคน', 'Lûuk chaai nèung khon láe lûuk săo săawng khon', 'son - one - person classifier - and - daughter - two - person classifier', '', 'm32_25'),
(854, 33, 'Female', 'หญิง', 'Yĭng', '', '', 'm33_1'),
(855, 33, 'Male', 'ชาย', 'Chaai', '', '', 'm33_2'),
(856, 33, 'Woman', 'ผู้หญิง', 'Phûu yĭng', 'person - female', '', 'm33_3'),
(857, 33, 'Man', 'ผู้ชาย', 'Phûu chaai', 'person - male', '', 'm33_4'),
(858, 33, 'Boy', 'เด็กผู้ชาย', 'Dèk phûu chaai', 'child - person - male', '', 'm33_5'),
(859, 33, 'Girl', 'เด็กผู้หญิง', 'Dèk phûu yĭng', 'child - person - female', '', 'm33_6'),
(860, 33, 'Friend', 'เพื่อน', 'Phêuan', '', '', 'm33_7'),
(861, 33, 'Neighbour', 'เพื่อนบ้าน', 'Phêuan bâan', 'friend - house', '', 'm33_8'),
(862, 33, 'Boyfriend/girlfriend', 'แฟน', 'Faen', '', '', 'm33_9'),
(863, 33, 'Sweetheart', 'ที่รัก', 'Thîi rák', 'that - love', '', 'm33_10'),
(864, 33, 'Female friend', 'เพื่อนหญิง', 'Phêuan yĭng', 'friend - female', '', 'm33_11'),
(865, 33, 'Male friend', 'เพื่อนชาย', 'Phêuan chaai', 'friend - male', '', 'm33_12'),
(866, 33, 'Foreigner', 'ชาวต่างชาติ', 'Chaao dtàang châat', 'people - different - nation', '', 'm33_13'),
(867, 33, 'Caucasian foreigner', 'ฝรั่ง', 'Fà-ràng', '', 'The word ''fà-ràng'' is usually used to refer to white foreigners and ''chaao dtàang châat'' means foreigner in general', 'm33_14'),
(868, 33, 'Professional', 'มืออาชีพ', 'Meuu aa-chêep', 'hand - occupation', '', 'm33_15'),
(869, 33, 'University student', 'นักศึกษามหาวิทยาลัย', 'Nák sèuk-săa má-hăa-wít-thá-yaa-lai', 'person who - study (above school) - university', '', 'm33_16'),
(870, 33, 'School student', 'นักเรียน', 'Nák rian', 'person who - study (school level)', '', 'm33_17'),
(871, 33, 'Teacher', 'ครู', 'Khruu', '', '', 'm33_18'),
(872, 33, 'Business person', 'นักธุรกิจ', 'Nák thóo-ráa-gìt', 'person who - business', '', 'm33_19'),
(873, 33, 'Tourist', 'นักท่องเที่ยว', 'Nák thâawng thîaao', 'person who - wander - trip', '', 'm33_20'),
(874, 33, 'Doctor', 'หมอ', 'Mŏr', '', '', 'm33_21'),
(875, 33, 'Nurse', 'พยาบาล', 'Phá-yaa-baan', '', '', 'm33_22'),
(876, 33, 'Rice farmer', 'ชาวนา', 'Chaao naa', 'person - rice farm', '', 'm33_23'),
(877, 33, 'Vegetable farmer', 'ชาวไร่', 'Chaao râi', 'person - farm', '', 'm33_24'),
(878, 33, 'Mechanic', 'ช่างเครื่อง', 'Châng krêuuang', 'mechanic / engineer - machine', '', 'm33_25'),
(879, 33, 'Taxi driver', 'คนขับแท็กซี่', 'Khon khàp tháek-sîi', 'person classifier - drive - taxi', '', 'm33_26'),
(880, 33, 'Fisherman', 'ชาวประมง', 'Chaao bprà-mohng', 'person - to fish', '', 'm33_27'),
(881, 33, 'Police person', 'ตำรวจ', 'Dtam rùat', '', '', 'm33_28'),
(882, 33, 'Politician', 'นักการเมือง', 'Nák gaan-meuuang', 'professional - politics', '', 'm33_29'),
(883, 33, 'Sportsperson, athlete', 'นักกีฬา', 'Nák gi-laa', 'professional - sport', '', 'm33_30'),
(884, 33, 'Musician', 'นักดนตรี', 'Nák don-dtrii', 'professional - music', '', 'm33_31'),
(885, 33, 'Chef/cook', 'พ่อครัว / กุ๊กทำอาหาร', 'Phâaw khruaa / Góok tham aa-hăan', 'father - kitchen / cook - make - food', '', 'm33_32'),
(886, 33, 'Labourer', 'กรรมกร', 'Gam-má-gaawn', '', '', 'm33_33'),
(887, 34, 'Beautiful', 'สวย', 'Sŭay', '', '', 'm34_1'),
(888, 34, 'Handsome', 'หล่อ', 'Làw', '', '', 'm34_2'),
(889, 34, 'Thin', 'ผอม', 'Phăwm', '', '', 'm34_3'),
(890, 34, 'Fat, big', 'อ้วน', 'Oûan', '', '', 'm34_4'),
(891, 34, 'Tall', 'สูง', 'Sŏung', '', '', 'm34_5'),
(892, 34, 'Short', 'เตี้ย', 'Dtîia', '', '', 'm34_6'),
(893, 34, 'Cute', 'น่ารัก', 'Nâa-rák', 'loveable', '', 'm34_7'),
(894, 34, 'Lazy', 'ขี้เกียจ', 'Khîi-gìat', '', '', 'm34_8'),
(895, 34, 'Hardworking', 'ขยัน', 'Khà-yăn', '', '', 'm34_9'),
(896, 34, 'Shy', 'ขี้อาย', 'Khîi-ai', '', '', 'm34_10'),
(897, 34, 'Friendly', 'เป็นมิตร', 'Bpen mít', 'is - friend', '', 'm34_11'),
(898, 34, 'Naughty', 'ซน', 'Sohn', '', '', 'm34_12'),
(899, 34, 'Kindhearted', 'ใจดี', 'Jai dii', 'heart - good', '', 'm34_13'),
(900, 34, 'Unkind', 'ใจดำ', 'Jai dam', 'heart - black', '', 'm34_14'),
(901, 34, 'Single', 'โสด', 'Sòht', '', '', 'm34_15'),
(902, 34, 'Married', 'แต่งงานแล้ว', 'Dtàeng-ngaan láew', 'marry - past action marker', '', 'm34_16'),
(903, 34, 'Calm', 'ใจเย็น', 'Jai yen', 'heart - cool', '', 'm34_17'),
(904, 34, 'Smart', 'ฉลาด', 'Chà làat', '', '', 'm34_18'),
(905, 34, 'Crazy', 'บ้า', 'Bâa', '', '', 'm34_19'),
(906, 34, 'What sort of person is he?', 'เขาเป็นคนยังไงครับ', 'Khăo bpen khon yang-ngai khráp?', 'he - is - person - how - polite particle?', '', 'm34_20'),
(907, 34, 'Kindhearted person', 'คนใจดี', 'Khon jai-dii', 'person - kind', '', 'm34_21'),
(908, 34, 'Is he kind? Yes, very.', 'เขาใจดีไหมครับ ใช่ เขาใจดีมากครับ', 'Khăo jai-dii mái khráp? Châi, khăo jai-dii mâak khráp', 'he - kindhearted - or not - polite particle? - yes - he - kindhearted - very - polite particle', '', 'm34_22'),
(909, 34, 'She wears glasses.', 'เธอใส่แว่น', 'Thuuhr sài wâaen', 'she - wear - glasses', '', 'm34_23'),
(910, 34, 'Your baby is cute.', 'ลูกของคุณน่ารัก', 'Lûuk kăwng khun nâa-rák', 'child - belonging to - you - cute', '', 'm34_24'),
(911, 34, 'I am more shy than you.', 'ผมขี้อายมากกว่าคุณ', 'Phŏhm khîi-ai mâak gwàa khun', 'I - shy - very - more than - you', '', 'm34_25'),
(912, 34, 'He is taller than me.', 'เขาสูงกว่าผม', 'Khăo sŏung gwàa phŏhm.', 'he - tall - more than - me', '', 'm34_26'),
(913, 34, 'Who is the prettiest girl in your class?', 'ใครสวยที่สุดในห้องของคุณครับ', 'Khrai sŭay thîi-sòot nai hâawng kăwng khun khráp?', 'who - beautiful - most - in - room - of - you - polite particle?', '', 'm34_27'),
(914, 35, 'Happy', 'ดีใจ', 'Dii jai', 'good - heart', '', 'm35_1'),
(915, 35, 'Sad / upset', 'เสียใจ', 'Sĭa jai', 'spoiled - heart', '', 'm35_2'),
(916, 35, 'Fine', 'สบายดี', 'Sà-baai-dii', '', '', 'm35_3'),
(917, 35, 'Tired', 'เหนื่อย', 'Nèuuay', '', '', 'm35_4'),
(918, 35, 'Bored', 'เบื่อ', 'Bùea', '', '', 'm35_5'),
(919, 35, 'Excited', 'ตื่นเต้น', 'Dtèuun dtên', 'scare - dance/throb', '', 'm35_6'),
(920, 35, 'Angry', 'โกรธ', 'Gròht', '', '', 'm35_7'),
(921, 35, 'Interested', 'สนใจ', 'Sŏn-jai', '', '', 'm35_8'),
(922, 35, 'Offended', 'เจ็บใจ', 'Jèp jai', 'hurt - heart', '', 'm35_9'),
(923, 35, 'How do you feel?', 'คุณรู้สึกอย่างไรครับ', 'Khun rúu-sèuk yaang-rai khráp?', 'you - feel - how - polite particle?', '', 'm35_10'),
(924, 35, 'I''m tired.', 'ผมเหนื่อย', 'Phŏhm nèuuay', 'I - tired', '', 'm35_11'),
(925, 35, 'You look sad.', 'คุณดูเสียใจ', 'Khun duu sĭa-jai', 'you - look - sad', '', 'm35_12'),
(926, 35, 'Why is he angry?', 'เขาโกรธเพราะอะไรเหรอครับ', 'Khăo gròht phráw à-rai rŭuhr khráp?', 'he - angry - because - what - question particle - polite particle', '', 'm35_13'),
(927, 35, 'She''s angry that Chalerm is drunk', 'เธอโกรธที่เฉลิมเมาเหล้า', 'Thuuhr gròht thîi Chà-lĕerm mao lâo', 'she - angry - that - Chalerm - intoxicated - alcohol', '', 'm35_14'),
(928, 35, 'What do you think?', 'คุณคิดอย่างไรครับ?', 'Khun khít yaang-rai khráp?', 'you - think - how - polite particle?', '', 'm35_15'),
(929, 35, 'I think it''s a good idea.', 'ผมคิดว่ามันเป็นความคิดที่ดีนะครับ', 'Phŏhm khít wâh mun bpen khwaam khít thîi dii ná khráp', 'I - think - that - it - is - particle which converts a verb into a noun - think - that (is) - good - softening particle - polite particle', 'The word ''khwaam'' converts a verb or adjective into a noun. In this case ''khít'' (think) becomes ''idea''.', 'm35_16'),
(930, 35, 'I think you should apologise to Gaew because she looks upset.', 'ผมคิดว่าคุณควรไปขอโทษแก้วนะครับ เพราะแก้วดูเสียใจมาก', 'Phŏhm khít wâh khun khuaan bpai kŏr-thôt Gâew ná khráp, phráw Gâew duu sĭa-jai mâak', 'I - think - that - you - should - go - apologise - Gaew - softening particle - polite particle - because - Gaew - look - upset - very', '', 'm35_17'),
(931, 35, 'He told me not to complain so that no one will lose face.', 'เขาบอกผมว่าผมไม่ควรบ่นเพราะจะได้ไม่มีใครเสียหน้า', 'Khăo bòrk phŏhm wâh phŏhm mâi khuaan bòhn phráw jà-dâi mâi mii khrai sĭa nâa', 'he - tell - me - that - I - not - should - complain - because - will be able to - not - have - anyone - spoil - face', '', 'm35_18'),
(932, 35, 'I think that he did a good job.', 'ผมคิดว่าเขาทำงานดี', 'Phŏhm khít wâh khăo tum-ngaan dii', 'I - think - that - he - work - good', '', 'm35_19'),
(933, 35, 'When shall we go?', 'เราจะไปเมื่อไหร่ดีครับ', 'Rao jà bpai mêua-rai dii khráp?', 'we - future marker - go - when - good - polite particle?', 'We can put the word ''dii'' after a question word to ask for advice or opinion.', 'm35_20'),
(934, 35, 'I agree.', 'ผมเห็นด้วย', 'Phŏhm hĕn dûay', 'I - see - also', '', 'm35_21'),
(935, 35, 'I disagree.', 'ผมไม่เห็นด้วย', 'Phŏhm mâi hĕn dûay', 'I - not - see - also', '', 'm35_22'),
(936, 35, 'It doesn''t matter.', 'มันไม่สำคัญ', 'Mun mâi săm-khan', 'it - not - important', '', 'm35_23'),
(937, 35, 'I don''t know', 'ผมไม่รู้', 'Phŏhm mâi rúu', 'I - not - know', '', 'm35_24'),
(938, 35, 'I don''t mind', 'ผมไม่คิดมาก', 'Phŏhm mâi khít mâak', 'I - not - think - much', '', 'm35_25'),
(939, 35, 'I hope that you will understand.', 'ผมหวังว่าคุณจะเข้าใจ', 'Phŏhm wăng wâh khun jà khâo-jai', 'I - hope - that - you - will - understand', '', 'm35_26'),
(940, 37, 'Watch a movie', 'ดูหนัง', 'Duu năng', 'watch - film', '', 'm37_1'),
(941, 37, 'Listen to music', 'ฟังเพลง', 'Fang phleng', 'listen - song', '', 'm37_2'),
(942, 37, 'Watch a play', 'ดูการแสดง', 'Duu gaan-sà-daaeng', 'watch - performance', '', 'm37_3'),
(943, 37, 'Dance(verb)', 'เต้นรำ', 'Dtên-ram', '', '', 'm37_4'),
(944, 37, 'Lyrics', 'เนื้อเพลง', 'Néua plehng', 'lyrics - song', '', 'm37_5'),
(945, 37, 'Play guitar', 'เล่นกีต้าร์', 'Lên gii-dtâa', 'play - guitar', '', 'm37_6'),
(946, 37, 'Do you like singing?', 'คุณชอบร้องเพลงไหมครับ', 'Khun chôrp rórng phleng mái khráp?', 'you - like - sing - song - or not - polite particle?', '', 'm37_7'),
(947, 37, 'Who is your favourite singer?', 'คุณชอบนักร้องคนไหนครับ', 'Khun chôrp nák-rórng khon năi khráp?', 'you - like - singer - person classifier - which - polite particle?', '', 'm37_8'),
(948, 37, 'Traditional Thai music', 'เพลงไทยเดิม', 'Phleng Thai deerm', 'song - Thai - original', '', 'm37_9'),
(949, 37, 'Pop music', 'เพลงป๊อป', 'Phleng bpóp', 'song - pop', '', 'm37_10'),
(950, 37, 'Traditional dance', 'รำไทย', 'Ram Thai', '', '', 'm37_11'),
(951, 37, 'Play sport', 'เล่นกีฬา', 'Lên gi-laa', 'play - sport', '', 'm37_12'),
(952, 37, 'Play football', 'เล่นฟุตบอล', 'Lên fút-baawn', 'play - football', '', 'm37_13'),
(953, 37, 'Badminton', 'แบดมินตัน', 'Bàaet-min-dtan', '', '', 'm37_14'),
(954, 37, 'Volleyball', 'วอลเลย์บอล', 'Wah-lî-baawn', '', '', 'm37_15'),
(955, 37, 'Basketball', 'บาสเก็ตบอล', 'Bàas-gèt-baawn', '', '', 'm37_16'),
(956, 37, 'Handball', 'แฮนด์บอล', 'Haaen-baawn', '', '', 'm37_17'),
(957, 37, 'Thai boxing', 'มวยไทย', 'Muay Thai', '', '', 'm37_18'),
(958, 37, 'Kite flying', 'ว่าว', 'Wâao', 'kite', '', 'm37_19'),
(959, 37, 'Thai chess', 'หมากรุก', 'Màak-róok', '', '', 'm37_20'),
(960, 37, 'Sepak takraw', 'ตะกร้อ', 'Dta-grâw', '', '', 'm37_21'),
(961, 37, 'Watch a football match', 'ดูเกมส์ฟุตบอล', 'Duu gaehm fút-baawn', 'watch - game - football', '', 'm37_22'),
(962, 37, 'Do you like volleyball?', 'คุณชอบเล่นวอลเลย์บอลไหม', 'Khun chôrp lên wah-lî-baawn mái?', 'you - like - play - volleyball - or not?', '', 'm37_23'),
(963, 37, 'Do you know how to swim?', 'คุณว่ายน้ำเป็นไหม', 'Khun wâi náam bpen mái?', 'you - swim - water - know how to - or not?', '', 'm37_24'),
(964, 37, 'Do you want to play badminton?', 'คุณอยากเล่นแบดมินตันไหม', 'Khun yàak lên bàaet-min-dtan mái?', 'you - want - play - badminton - or not?', '', 'm37_25'),
(965, 37, 'Athlete/sports player', 'นักกีฬา', 'Nák gi-laa', 'professional - sport', '', 'm37_26'),
(966, 37, 'Sports team', 'ทีมกีฬา', 'Theem gi-laa', 'team - sport', '', 'm37_27'),
(967, 39, 'Temple', 'วัด', 'Wát', '', '', 'm39_1'),
(968, 39, 'Forest temple', 'วัดป่า', 'Wát bpàa', 'temple - forest', '', 'm39_2'),
(969, 39, 'Temple meeting hall', 'ศาลา', 'Săa-laa', '', '', 'm39_3'),
(970, 39, 'Monk', 'พระสงฆ์ ', 'Phrá'' sŏhng', '', '', 'm39_4'),
(971, 39, 'Novice monk', 'เณร / สามเณร', 'Naehn / Săam-má-naehn', '', '', 'm39_5'),
(972, 39, 'Nun', 'แม่ชี', 'Mâe chii', 'mother - nun', '', 'm39_6'),
(973, 39, 'Lord Buddha', 'พระพุทธองค์', 'Phrá'' phút-thá ohng', 'god - Buddha - classifier', '', 'm39_7'),
(974, 39, 'Buddhism', 'ศาสนาพุทธ', 'Sàat-sà-năa phút', 'religion - Buddha', '', 'm39_8'),
(975, 39, 'Buddhist person', 'ชาวพุทธ', 'Chaao phút', 'person - Buddhist', '', 'm39_9'),
(976, 39, 'Offering of food to a monk', 'ใส่บาตร', 'Sài bàat', 'put in - bowl carried by monks', '', 'm39_10'),
(977, 39, 'Buddhist precept', 'ศีล', 'Sĭin', '', '', 'm39_11'),
(978, 39, 'To observe Buddhist precepts', 'ถือศีล', 'Thĕuu sĭin', 'to hold a belief - religious precept', '', 'm39_12'),
(979, 39, 'Sacred', 'ศักดิ์สิทธิ์', 'Sàk-sìt', '', '', 'm39_13'),
(980, 39, 'Merit, moral goodness', 'คุณธรรม', 'Khoon-ná tham', 'merit - moral goodness', '', 'm39_14'),
(981, 39, 'Meditation', 'สมาธิ', 'Sà-maa-thí', '', '', 'm39_15'),
(982, 39, 'Forbidden', 'ต้องห้าม', 'Dtôrng hâam', 'must - to forbid', '', 'm39_16'),
(983, 39, 'Buddha image', 'พระพุทธรูป', 'Phrá'' phút thá rûup', 'god - Buddha - shape / form', '', 'm39_17'),
(984, 39, 'Stupa', 'เจดีย์', 'Jaeh-dee', '', '', 'm39_18'),
(985, 39, 'Community of monks', 'สังฆมณฑล', 'Săng-khá mohn-tohn', 'religious - circle', '', 'm39_19'),
(986, 39, 'Sermon, moral discourse', 'ธรรมีกถา', 'Thum-mee-gà-thăa', '', '', 'm39_20'),
(987, 39, 'Make merit', 'ทำบุญ', 'Tham boon', 'do - merit', '', 'm39_25'),
(988, 39, 'Go around a stupa', 'เวียนเทียน', 'Wiian thiian', 'go around - candle', 'It is common practice to go around a stupa three times when visiting a temple.', 'm39_26'),
(989, 39, 'Mosque', 'มัสยิด', 'Mát-sà-yít', '', '', 'm39_21'),
(990, 39, 'Muslim worship', 'ละหมาด', 'Lá-màat', '', '', 'm39_22'),
(991, 39, 'The Koran', 'อัลกุระอ่าน', 'An-gòo-rá-aan', '', '', 'm39_23'),
(992, 39, 'Church', 'โบสถ์', 'Bòht', '', '', 'm39_24'),
(993, 40, 'Children''s Day', 'วันเด็ก', 'Wan dèk', 'day - child', 'Second Saturday in January.', 'm40_1'),
(994, 40, 'Makha Bucha', 'มาฆบูชา', 'Maa-khá Buu-chaa', 'third lunar month - worship', 'The day when 1250 of the Lord Buddha''s disciples spontaneously gathered to hear him preach. Usually falls in February or March.', 'm40_2'),
(995, 40, 'Water festival', 'สงกรานต์', 'Sŏhng-graan', '', 'Thai New Year, April 13-15, when everyone is doused with water.', 'm40_3'),
(996, 40, 'Rocket festival, Isan', 'ประเพณีบุญบั้งไฟ', 'Bprà-phaeh-nee boon bâng-fai', 'custom - merit - rocket', 'Held in May to encourage the Gods to send rain.', 'm40_4'),
(997, 40, 'Buddhist holy day', 'วันพระ', 'Wan phrá', '', '', 'm40_5'),
(998, 40, 'Visakha Bucha', 'วันวิสาขบูชา', 'Wan Wí-săa-khà Buu-chaa', 'day - full moon day - worship', 'Commemorates three important events in the life of the Lord Buddha - his birth, enlightenment and death - which all occurred on the full moon day of the sixth lunar month. Occurs in May/June.', 'm40_6'),
(999, 40, 'Asahna Bucha', 'วันอาสาฬหบูชา', 'Wan Aa-săan-hà Buu-chaa', 'day - full moon day of eight lunar month - worship', 'The day when the Lord Buddha delivered his first sermon. Usually in July or August.', 'm40_7'),
(1000, 40, 'Khao Phansa', 'เข้าพรรษา', 'Khâo phan-săa', 'enter - rainy season', 'The day after Asahna Bucha. Marks the start of the three month Buddhist retreat period.', 'm40_8'),
(1001, 40, 'Candle Festival, Ubon Ratchatani', 'ประเพณีแห่เทียนพรรษา', 'Bprà-phaeh-nee hàae thiian phan-săa', 'custom - parade - candle - rainy season', 'Held in July.', 'm40_9'),
(1002, 100, 'Queen''s Birthday and Mother''s Day', 'วันแม่', 'Wan mâe', 'day - mother', 'Held on August 12', 'm40_10'),
(1003, 40, 'Awk Phansa', 'ออกพรรษา', 'Àawk phan-săa ', 'exit - rainy season', 'The end of the rainy season and Buddhist retreat period, occurring in September or October.', 'm40_11'),
(1004, 40, 'Loi Krathong', 'ลอยกระทง', 'Loi grà-thohng', 'set afloat - ceremonial basket', 'Wish making festival where candles are floated on water inside special baskets. Held in November.', 'm40_12'),
(1005, 100, 'King''s Birthday and Father''s Day', 'วันพ่อ', 'Wan phâaw', 'day - father', 'Held on December 5.', 'm40_13'),
(1006, 40, 'Birthday', 'วันเกิด', 'Wan gèut', 'day - birth', '', 'm40_14'),
(1007, 40, 'When is your birthday?', 'วันเกิดคุณวันไหนครับ', 'Wan gèut khun wan năi khráp?', 'day - birth - you - day - which - polite particle?', '', 'm40_15'),
(1008, 41, 'Doctor', 'หมอ', 'Mŏr', '', '', 'm41_1'),
(1009, 41, 'Nurse', 'พยาบาล', 'Phá-ya-baan', '', '', 'm41_2'),
(1010, 41, 'Dentist', 'หมอฟัน', 'Mŏr fan', 'doctor - teeth', '', 'm41_3'),
(1011, 41, 'Medicine/drug', 'ยา', 'Yaa', '', '', 'm41_4'),
(1012, 41, 'Prescription', 'ใบสั่งยา', 'Bai sàng yaa', 'sheet - order - medicine', '', 'm41_5'),
(1013, 41, 'Inject', 'ฉีด', 'Chìit', '', '', 'm41_6'),
(1014, 41, 'Hospital', 'โรงพยาบาล', 'Rohng phá-ya-baan', 'building - administer treatment', 'The hospital is the first port of call in Thailand, whether it’s a small injury or a serious sickness. It’s rare to find a GP clinic in Thailand. Hospitals in Thailand accept both emergency and non-emergency patients.', 'm41_7'),
(1015, 41, 'Health centre', 'สถานีอนามัย', 'Sà-thăa-nii à-naa-mai', 'station - health', '', 'm41_8'),
(1016, 41, 'Disease', 'โรค', 'Rôhk', '', '', 'm41_9'),
(1017, 41, 'Infected', 'ติดเชื้อ', 'Dtìt chéuua', 'contract disease - germ', '', 'm41_10'),
(1018, 41, 'Wound, cut', 'แผล', 'Phlăe', '', '', 'm41_11'),
(1019, 41, 'Stomach ache', 'ปวดท้อง', 'Bpùat thórng', 'ache - stomach/belly', '', 'm41_12'),
(1020, 41, 'Headache', 'ปวดหัว', 'Bpùat hŭa', 'ache - head', '', 'm41_13'),
(1021, 41, 'Back ache', 'ปวดหลัง', 'Bpùat lăng', 'ache - back', '', 'm41_14'),
(1022, 41, 'Ear ache', 'ปวดหู', 'Bpùat hŭu', 'ache - ear', '', 'm41_15'),
(1023, 41, 'Sore foot', 'เจ็บเท้า', 'Jèp tháao', 'pain - foot', '', 'm41_17'),
(1024, 41, 'Sore hand', 'มือเจ็บ', 'Meuu jèp', 'hand - pain', '', 'm41_18'),
(1025, 41, 'Pregnant', 'ท้อง', 'Thórng', 'belly', '', 'm41_19'),
(1026, 41, 'Does that hurt?', 'เจ็บไหม', 'Jèp mái?', 'pain - or not?', '', 'm41_16'),
(1027, 41, 'It hurts a little.', 'เจ็บนิดหน่อย', 'Jèp nít-nòy', 'pain - a little', '', 'm41_22'),
(1028, 41, 'It hurts a lot.', 'เจ็บมาก', 'Jèp mâak', 'pain - a lot', '', 'm41_23'),
(1029, 41, 'Where does it hurt?', 'เจ็บตรงไหน', 'Jèp dtrong năi?', 'pain - at - where', '', 'm41_20'),
(1030, 41, 'It hurts here.', 'เจ็บตรงนี้', 'Jèp dtrong níi ', 'pain - at - this', '', 'm41_21'),
(1031, 41, 'Symptom(s)', 'อาการ', 'Aa-gaan', '', '', 'm41_24'),
(1032, 41, 'Have a fever', 'เป็นไข้', 'Bpen khâi', 'suffer from - fever', '', 'm41_25'),
(1033, 41, 'Have a cold', 'เป็นหวัด', 'Bpen wàt', 'suffer from - cold', '', 'm41_26'),
(1034, 41, 'Have the flu', 'เป็นไข้หวัด', 'Bpen khâi wàt', 'suffer from - fever - cold', '', 'm41_27'),
(1035, 41, 'Dizzy', 'เวียนหัว', 'Wian hŭa', 'to circle around - head', '', 'm41_28'),
(1036, 41, 'Feel faint', 'เป็นลม', 'Bpen lom', 'to be afflicted with - air, wind', '', 'm41_29'),
(1037, 41, 'Vomit', 'อาเจียน', 'Aa-jian', '', '', 'm41_30'),
(1038, 41, 'Cough', 'ไอ', 'Ai', '', '', 'm41_31'),
(1039, 41, 'Diarrhoea', 'ท้องเสีย', 'Thórng sĭa', 'stomach - spoiled, not working', '', 'm41_32'),
(1040, 41, 'Traditional Thai massage', 'นวดไทย', 'Nûaat Thai', '', '', 'm41_33'),
(1041, 41, 'Go to see the doctor', 'ไปหาหมอ', 'Bpai hăa mŏr', 'go - visit - doctor', '', 'm41_34'),
(1042, 41, 'I need to see a doctor.', 'ผมต้องไปหาหมอ', 'Phŏhm dtôrng bpai hăa mŏr', 'I - need to - go - visit - doctor', '', 'm41_35'),
(1043, 41, 'Where is the nearest health centre?', 'สถานีอนามัยใกล้ที่สุดอยู่ไหนครับ', 'Sà-thăa-nii à-naa-mai glâi thîi-sòot yùu năi khráp?', 'station - health - close - most - situated - where - polite particle?', '', 'm41_36'),
(1044, 41, 'Are you feeling better?', 'คุณรู้สึกดีขึ้นไหมครับ', 'Khun rúu-sèuk dii khêun mái khráp?', 'you - feel - good - increase - or not - polite particle?', '', 'm41_37'),
(1045, 41, 'The doctor gave me some medicine.', 'หมอให้ยาผมมาครับ', 'Mŏr hâi yaa phŏhm maa khráp', 'doctor - give - medicine - me - marker to indicate continuity from the past - polite particle', '', 'm41_38'),
(1046, 41, 'I think you should get a massage.', 'ผมคิดว่าคุณควรไปนวดนะครับ', 'Phŏhm khít wâh khun khuaan bpai nûaat ná khráp', 'I - think - that - you - should - go - massage - softening particle - polite particle', '', 'm41_39');
