INSERT INTO `phrasesF` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(1, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'ปา ป่า ป้า ป๊า ป๋า', 'Bpaa bpàa bpâa bpáa bpăa', 'throw - forest - aunt - dad - dad ', 'The mid-tone is spoken at in the middle of your vocal range. It may fall slightly at the end. The low tone is spoken at a constant or slightly falling pitch starting lower than normal speech. The falling tone starts high and then falls to a low pitch. The high tone is spoken at the top of your vocal range, rising slightly and then falling slightly. The rising tone starts low, falls slightly and then rises to a high pitch.', 'f1_1'),
(2, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'เกา เก่า เก้า เก๊า เก๋า', 'Gao gào gâo gáo găo', 'scratch - old - nine - gout - excellent', '', 'f1_2'),
(3, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'ตู ตู่ ตู้ ตู๊ ตู๋', 'Dtuu dtùu dtûu dtúu dtŭu', 'myself - assume or feign ownership - cabinet / compartment - timbered - alternate spelling of ตู้', '', 'f1_3'),
(4, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'อา อ่า อ้า อ๊า อ๋า', 'Aa àa âa áa ăa', 'younger sibling of father - decorate - word used as interjection - no meaning - no meaning', '', 'f1_4'),
(5, 1, 'Rising tone - low tone - falling tone', 'ขา ข่า ข้า', 'Khăa khàa khâa', 'leg - galangal - attendant', '', 'f1_5'),
(6, 1, 'Mid tone - falling tone - high tone', 'ไร ไร่ ไร้', 'Rai râi rái', 'suffix indicating a question about quantity - unit of land - devoid of', '', 'f1_6'),
(7, 1, 'Mid tone - falling tone - high tone', 'นา น่า น้า', 'Naa nâa náa', 'rice field - various meanings - younger brother or sister of mother', '', 'f1_7'),
(8, 1, 'Mid tone - falling tone - high tone', 'ไช ใช่ ใช้', 'Chai châi chái', 'pierce a hole - yes - to use', '', 'f1_8'),
(9, 1, 'He eats rice', 'เขากินข้าว', 'Khăo gin khâao', 'he - eat - rice', '', 'f1_9'),
(10, 1, 'Grandmother takes medicine', 'คุณย่ากินยา', 'Khun yâa gin yaa', 'title of respect - maternal grandmother - eat - medicine', '', 'f1_10'),
(11, 1, 'Grandfather collects crabs', 'คุณปู่จับปู', 'Khun bpùu jàp bpuu', 'title of respect - paternal grandfather - catch - crab', '', 'f1_11'),
(12, 1, 'Take aunt to the forest', 'พาป้าไปป่า', 'Phaa bpâa bpai bpàa', 'take - aunt - go - forest', '', 'f1_12'),
(13, 1, 'A dog and a horse are coming', 'หมาและม้าจะมา', 'Măa lae máa jà maa', 'dog - and - horse - future marker - come', '', 'f1_13'),
(14, 1, 'I bought a tiger shirt that has four colours', 'ซื้อเสื้อลายเสือมีสี่สี', 'Séu sêua laai sĕua mii sìi sĭi', 'buy - shirt - pattern - tiger - have - four - colour', '', 'f1_14'),
(15, 2, 'Female polite particle', 'ค่ะ', 'Khâ', '', 'Particle used by female speakers at the end of a sentence for politeness, as a response when their name is called, and during a conversation to indicate agreement. Pronounced with different tones depending on the context. Thai has many particles which have no equivalent in English. They are generally used to indicate politeness or imply a question.', 'f2_1'),
(16, 2, 'Male polite particle', 'ครับ', 'Khráp/Kháp', '', 'Particle used by male speakers at the end of a sentence for politeness, as a reponse when their name is called, and during conversation to indicate agreement. ''Kr'' sounds are often shortened to ''K'' in Bangkok speech.', 'f2_2'),
(17, 2, 'General greeting', 'สวัสดีค่ะ', 'Sà-wàt-dìi khâ', '', 'Can be used at any time of day. Can also be used for goodbye.', 'f2_3'),
(18, 2, 'Are you well?', 'สบายดีไหมคะ', 'Sà-baai dii mái khá?', 'well - good - or not - polite particle', '', 'f2_4'),
(19, 2, 'Yes, I''m well', 'สบายดีค่ะ', 'Sà-baai dii khâ', 'well - good - polite particle', '', 'f2_5'),
(20, 2, 'I''m not well', 'ฉันไม่ค่อยสบายค่ะ', 'Chăn mâi khôi sà-baai khâ', 'I - not - quite - well - polite particle', '', 'f2_6'),
(21, 2, 'And you?', 'คุณล่ะคะ', 'Kun lâ khá?', 'you - question particle - polite particle', '', 'f2_7'),
(22, 2, 'Good luck', 'โชคดีนะคะ', 'Chôhk dii ná khâ', 'luck - good - softening particle - polite particle', '', 'f2_8'),
(23, 2, 'What''s your name?', 'คุณชื่ออะไรคะ', 'Khun chêu à-rai khá?', 'you - name - what - polite particle?', '', 'f2_9'),
(24, 2, 'Do you have a nickname?', 'คุณมีชื่อเล่นไหมคะ', 'Khun mii chêu-lên mái khá?', 'you - have - nickname - or not - polite particle?', 'Thai people often have long names but the nick name is always short and is used by most people in everyday life.', 'f2_10'),
(25, 2, 'Nice to meet you.', 'ยินดีที่ได้รู้จักค่ะ', 'Yin dee thîi dâi rúu-jàk khâ', 'feel pleased - good - to - can - know - polite particle', '', 'f2_11'),
(26, 2, 'See you later', 'พบกันใหม่ค่ะ', 'Phóp gan mài khâ', 'meet - together - again - polite particle', '', 'f2_12'),
(27, 2, 'Where are you from?', 'คุณมาจากไหนคะ', 'Khun maa jàak năi khá?', 'you - come - from - where - polite particle', '', 'f2_13'),
(28, 2, 'Where are you going?', 'คุณจะไปไหนคะ', 'Khun jà bpai năi khá?', 'you - future marker - go - where - polite particle?', '', 'f2_14'),
(29, 2, 'Excuse me, sorry', 'ขอโทษค่ะ', 'Kŏr thôt khâ', 'request - punishment / blame - polite particle', '', 'f2_15'),
(30, 2, 'Have you eaten?', 'กินข้าวหรือยังคะ', 'Gin khâao (láew) rĕuu yang khá?', 'eat - rice - (already) - or - not yet - polite particle?', 'Thais take great care to ensure that everyone has eaten, so this question is very common.', 'f2_16'),
(31, 2, 'No problem/You''re welcome/it''s alright', 'ไม่เป็นไรค่ะ', 'Mâi bpen rai khâ', 'not - is - anything - polite particle', '', 'f2_17'),
(32, 2, 'That''s fine.', 'ดีแล้วค่ะ', 'Dii láew khâ', 'good - already - polite particle', '', 'f2_18'),
(33, 2, 'That''s correct.', 'ถูกต้องค่ะ', 'Thùuk dtông khâ', 'correct - must - polite particle', '', 'f2_19'),
(34, 2, 'Come and eat!', 'มากินข้าวกัน', 'Maa gin khâao gan', 'come - eat - rice - together', 'Thai people always invite you to join their meal if you’re visiting their home.', 'f2_20'),
(35, 2, 'Thank you', 'ขอบคุณค่ะ', 'Khàwp khun khâ', 'thank - you - polite particle', '', 'f2_21'),
(36, 2, 'Please', 'กรุณา', 'Gàa-róo-naa', '', '', 'f2_22'),
(37, 2, 'Just a moment.', 'สักครู่', 'Sàk khrûu', 'just - a short moment', '', 'f2_23'),
(38, 2, 'Do you understand?', 'เข้าใจไหมคะ', 'Khâo jai mái khá?', 'enter - heart/mind - or not - polite particle', '', 'f2_24'),
(39, 2, 'I understand.', 'ฉันเข้าใจ', 'Chăn khâo jai', 'I - enter - heart/mind', '', 'f2_25'),
(40, 2, 'I don''t understand.', 'ฉันไม่เข้าใจ', 'Chăn mâi khâo jai', 'I - not - enter - heart/mind', '', 'f2_26'),
(41, 2, 'Pardon? (please repeat)', 'อะไรนะคะ', 'À-rai ná khá?', 'what - softening particle - polite particle', 'The particle ''ná'' is added to the end of a sentence to soften it.', 'f2_27'),
(42, 2, 'Can you please speak more slowly', 'ช่วยพูดช้าๆหน่อยนะคะ', 'Chûay phût chá chá nòi ná khâ', 'help - speak - slow - slow - a little - softening particle - polite particle', '', 'f2_28'),
(43, 2, 'Can you please say that again.', 'ช่วยพูดอีกครั้งได้ไหมคะ', 'Chûay phût èek khráng dâi mái khá?', 'help - speak - another - instance - can - or not - polite particle?', '', 'f2_29'),
(44, 2, 'You can speak Thai!', 'คุณพูดไทยได้!', 'Khun phût Thai dâi!', 'you - speak - Thai - can!', '', 'f2_30'),
(45, 2, 'I can speak a little Thai.', 'ฉันพูดไทยได้นิดหน่อยค่ะ', 'Chăn phût Thai dâi nít-nòy khâ', 'I - speak - Thai - can - a little bit - polite particle', '', 'f2_31'),
(46, 2, 'I can''t speak Thai.', 'ฉันพูดไทยไม่ได้', 'Chăn phût Thai mâi dâi.', 'I - speak - Thai - not - can - polite particle', '', 'f2_32'),
(47, 2, 'What is this?', 'นี่คืออะไรคะ', 'Nîi kheu à-rai khá?', 'this - is - what - polite particle?', '', 'f2_33'),
(48, 2, 'What do you call this in Thai?', 'อันนี้ภาษาไทยเรียกว่าอะไรคะ', 'An-níi pha-săa Thai rîak wâa à-rai khá?', 'item - this - language - Thai - called - that - what - polite particle', '', 'f2_34'),
(49, 2, 'I like it', 'ฉันชอบ', 'Chăn chôrp', 'I - like', '', 'f2_35'),
(50, 2, 'I don''t like it', 'ฉันไม่ชอบ', 'Chăn mâi chôrp', 'I - not - like', '', 'f2_36'),
(51, 2, 'I don''t know.', 'ฉันไม่รู้', 'Chăn mâi róo.', 'I - not - know', '', 'f2_37'),
(52, 2, 'That''s great!', 'ดีมาก / เยี่ยม', 'Dii mâak!', 'good - very', '', 'f2_38'),
(53, 2, 'What are you doing?', 'คุณทำอะไรอยู่คะ', 'Khun tham à-rai yùu khá?', 'you - do - what - currently - polite particle?', '', 'f2_39'),
(54, 2, 'How old are you?', 'คุณอายุเท่าไหร่คะ', 'Khun aa-yúu thâo rai khá?', 'you - age - equal to - what - polite particle?', '', 'f2_40'),
(55, 2, 'No thanks', 'ไม่ค่ะ ขอบคุณนะคะ', 'Mâi khâ, khàwp khun ná khâ', 'no - polite particle - thank - you - softening particle - polite particle', '', 'f2_41'),
(56, 2, 'Help me!', 'ช่วยด้วย!', 'Chûay dûay!', 'help - particle used at the end of a request', '', 'f2_42'),
(57, 2, 'Do you have a bathroom?', 'มีห้องน้ำไหมคะ', 'Mii hâwng náam mái khá?', 'have - room - water - or not - polite particle?', '', 'f2_43'),
(58, 3, 'Wake up', 'ตื่น', 'Dtèuun', '', '', 'f3_1'),
(59, 3, 'Take a bath/shower', 'อาบน้ำ', 'Àap náam', 'bathe - water', '', 'f3_2'),
(60, 3, 'Brush teeth', 'แปรงฟัน', 'Bpraaeng fan', 'brush - tooth', '', 'f3_3'),
(61, 3, 'Comb hair', 'หวีผม', 'Wĭi phŏm', 'comb - hair', '', 'f3_4'),
(62, 3, 'Get dressed', 'แต่งตัว', 'Dtàeng dtua', 'dress - oneself', '', 'f3_5'),
(63, 3, 'Wash clothes', 'ซักผ้า', 'Sák phâa', 'wash - clothes', '', 'f3_6'),
(64, 3, 'Work', 'ทำงาน', 'Tham ngaan', 'do - work', '', 'f3_7'),
(65, 3, 'Prepare food', 'ทำอาหาร', 'Tham a-hăan', 'make - food', '', 'f3_8'),
(66, 3, 'Eat', 'กิน / ทาน', 'Gin / thaan', '', '', 'f3_9'),
(67, 3, 'Drink', 'ดื่ม / กิน', 'Dèum / gin', '', '', 'f3_10'),
(68, 3, 'Go home', 'กลับบ้าน', 'Glàp bâan', 'return - home', '', 'f3_11'),
(69, 3, 'Do the housework', 'ทำงานบ้าน', 'Tham ngaan bâan', 'do - work - home', '', 'f3_12'),
(70, 3, 'Play sport', 'เล่นกีฬา', 'Lên gi-laa', 'play - sport', '', 'f3_13'),
(71, 3, 'Watch TV', 'ดูทีวี', 'Doo thii-wii', 'look at - tv', '', 'f3_14'),
(72, 3, 'Go to sleep', 'ไปนอน', 'Bpai norn', 'go - sleep', '', 'f3_15'),
(73, 4, 'Sunny', 'แดดออก', 'Dàaet àawk', 'sunshine - go out (from the sun)', '', 'f4_1'),
(74, 4, 'Raining', 'ฝนตก', 'Fŏhn dtòk', 'rain - fall', '', 'f4_2'),
(75, 4, 'Cloudy', 'มีเมฆ', 'Mii mâehk', 'have - cloud', '', 'f4_3'),
(76, 4, 'Overcast, might rain', 'ครึ้มฟ้าครึ้มฝน', 'Khréum fáa khréum fŏhn', 'dark, dense - sky - dark, dense - rain', '', 'f4_4'),
(77, 4, 'Windy', 'ลมแรง', 'Lohm raaeng', 'wind - strong', '', 'f4_5'),
(78, 4, 'Hot', 'ร้อน', 'Rórn', '', '', 'f4_6'),
(79, 4, 'Cold', 'หนาว', 'Năao', '', '', 'f4_7'),
(80, 4, 'Humid', 'ชื้น', 'Chéuun', '', '', 'f4_8'),
(81, 4, 'Flood', 'น้ำท่วม', 'Náam thûaam', 'water - flood', '', 'f4_9'),
(82, 4, 'Storm', 'พายุ', 'Phaa-yúu', '', '', 'f4_10'),
(83, 4, 'Thunderstorm', 'พายุฟ้าคะนอง', 'Phaa-yúu fáa khá-nawng', 'storm - sky - thunder', '', 'f4_11'),
(84, 4, 'Drought', 'แห้งแล้ง', 'Hâaeng láaeng', 'dry - dry', '', 'f4_12'),
(85, 4, 'What''s the weather like?', 'อากาศเป็นอย่างไรบ้างคะ', 'Aa-gàat bpen yàang-rai bâang khá?', 'weather - is - how - some - polite particle?', '', 'f4_13'),
(86, 4, 'It''s hot and humid.', 'ร้อนชื้น', 'Rórn chéuun', 'hot - humid', '', 'f4_14'),
(87, 4, 'Is it going to rain?', 'ฝนกำลังจะตกใช่ไหมคะ', 'Fŏhn gamlang-jà dtòk châi-mái khá?', 'rain - about to - fall - yes or no - polite particle', '', 'f4_15'),
(88, 4, 'It might rain in the afternoon.', 'ฝนน่าจะตกตอนบ่ายนี้นะคะ', 'Fŏhn nâa jà dtòk dtaawn bàai níi ná khâ', 'rain - prefix indicating probability - future marker - fall - during - afternoon - this - softening particle - polite particle', '', 'f4_16'),
(89, 4, 'It''s too hot to play soccer.', 'อากาศร้อนเกินไปที่จะเล่นฟุตบอล', 'Aa-gàat rórn gern-bpai thîi jà lên fút-baawn', 'weather - hot - excessive - to - future marker - play - football', 'The expression ''gern bpai'' is similar to ''too''. Thai has a limited number of final consonant sounds. The letter ''L'' (ล) is pronounced ''N'' at the end of a syllable, hence ''foot-baawn''.', 'f4_17'),
(90, 4, 'It''s cold today.', 'วันนี้อากาศหนาวค่ะ', 'Wan níi aa-gàat năao khâ.', 'day - this - weather - cold - polite particle', '', 'f4_18'),
(91, 4, 'It''s hot, isn''t it?', 'อากาศร้อนเนอะ', 'Aa-gàat rórn núh?', 'weather - hot - particle requesting confirmation', '', 'f4_19'),
(92, 4, 'It''s raining hard.', 'ฝนตกหนัก', 'Fŏhn dtòk nàk', 'rain - fall - heavy', '', 'f4_20'),
(93, 4, 'Cool season', 'ฤดูหนาว', 'Réu-doo năao', 'season - cold', 'The word ''หน้า'' (nâa) can also be used for ''season''.', 'f4_21'),
(94, 4, 'Rainy season', 'ฤดูฝน', 'Réu-doo fŏhn', 'season - rain', '', 'f4_22'),
(95, 4, 'Hot season', 'ฤดูร้อน', 'Réu-doo rórn', 'season - hot', '', 'f4_23'),
(96, 4, 'We will plant the rice in the rainy season', 'เราจะปลูกข้าวในฤดูฝน', 'Rao jà bplùuk khâao nai réu-doo fŏhn', 'we - future marker - plant - rice - in - season - rain', '', 'f4_24'),
(97, 5, 'Chiang Rai', 'เชียงราย', 'Chiiang Raai', '', '', 'f5_1'),
(98, 5, 'Mae Hong Son', 'แม่ฮ่องสอน', 'Mâae Hâawng Săawn', '', '', 'f5_2'),
(99, 5, 'Chiang Mai', 'เชียงใหม่', 'Chiiang Mài', '', '', 'f5_3'),
(100, 5, 'Sukhothai', 'สุโขทัย', 'Sòo-khŏh-thai', '', '', 'f5_4'),
(101, 5, 'Ayuthaya', 'อยุธยา', 'À-yóot-thá-yaa', '', '', 'f5_5'),
(102, 5, 'Kanchanaburi', 'กาญจนบุรี', 'Gaan-jà-na-bòo-ree', '', '', 'f5_6'),
(103, 5, 'Bangkok', 'กรุงเทพฯ', 'Grung-thâep', '', 'The actual name of Bangkok is extremely long and many people cannot remember it. The character ''ฯ'' is called ''pai yan noi'' and indicates an abbreviation. ', 'f5_7'),
(104, 5, 'Hua Hin', 'หัวหิน', 'Hŭaa Hĭn', '', '', 'f5_8'),
(105, 5, 'Chumphon', 'ชุมพร', 'Choom-phaawn', '', '', 'f5_9'),
(106, 5, 'Koh Tao', 'เกาะเต่า', 'Gàw Dtào', 'island - turtle', '', 'f5_10'),
(107, 5, 'Koh Pha Ngan', 'เกาะพะงัน', 'Gàw Phá Ngan', '', '', 'f5_11'),
(108, 5, 'Koh Samui', 'เกาะสมุย', 'Gàw Sà-mŭi', '', '', 'f5_12'),
(109, 5, 'Surat Thani', 'สุราษฎร์ธานี', 'Sòo-râat-tha-nee', '', '', 'f5_13'),
(110, 5, 'Khao Sok National Park', 'อุทยานแห่งชาติเขาสก', 'Òot-thá-yaan hàeng-châat Khăo Sòhk', 'park - national - Khao sok', '', 'f5_14'),
(111, 5, 'Krabi', 'กระบี่', 'Grà-bèe', '', 'May be shortened to ''Gà-bèe''.', 'f5_15'),
(112, 5, 'Phuket', 'ภูเก็ต', 'Phuu-gèt', '', '', 'f5_16'),
(113, 5, 'Satun', 'สตูล', 'Sà-dtuun', '', '', 'f5_17'),
(114, 5, 'Country', 'ประเทศ', 'Bprà-thêt', '', 'It is common to use this word before the country name when referring to a country.', 'f5_18'),
(115, 5, 'Australia', 'ออสเตรเลีย', 'Aús-tre-lia', '', '', 'f5_19'),
(116, 5, 'Canada', 'แคนาดา', 'Khae-naa-daa', '', '', 'f5_20'),
(117, 5, 'China', 'จีน', 'Jiin', '', '', 'f5_21'),
(118, 5, 'France', 'ฝรั่งเศส', 'Fà-ràng-sèt', '', 'The word ''fà-ràng'' is used to refer to any white foreigner.', 'f5_22'),
(119, 5, 'Germany', 'เยอรมัน', 'Ye-ra-man', '', '', 'f5_23'),
(120, 5, 'India', 'อินเดีย', 'In-diia', '', '', 'f5_24'),
(121, 5, 'Japan', 'ญี่ปุ่น', 'Yîi-bpùn', '', '', 'f5_25'),
(122, 5, 'Laos', 'ลาว', 'Laao', '', '', 'f5_26'),
(123, 5, 'Malaysia', 'มาเลเซีย', 'Maa-laeh-siia', '', '', 'f5_27'),
(124, 5, 'Myanmar', 'พม่า', 'Phá-mâa', '', '', 'f5_28'),
(125, 5, 'New Zealand', 'นิวซีแลนด์', 'Niu-see-laen', '', '', 'f5_29'),
(126, 5, 'Russia', 'รัสเซีย', 'Rát-siia', '', '', 'f5_30'),
(127, 5, 'Spain', 'สเปน', 'Sà-pen', '', '', 'f5_31'),
(128, 5, 'United Kingdom', 'อังกฤษ', 'Ang-krìt', '', '', 'f5_32'),
(129, 5, 'USA', 'อเมริกา', 'Àa-meh-ríi-gaa', '', '', 'f5_33'),
(130, 5, 'Vietnam', 'เวียดนาม', 'Wîiat-naam', '', '', 'f5_34'),
(131, 5, 'I''m Australian', 'ฉันเป็นคนออสเตรเลียค่ะ', 'Chăn bpen khon Aús-tre-lia khâ', 'I - am - person - Australia - polite particle', '', 'f5_35'),
(132, 5, 'She''s French', 'เธอเป็นคนฝรั่งเศสค่ะ', 'Thuuhr bpen khon Fà-ràng-sèt khâ', 'she - is - person - France - polite particle', '', 'f5_36'),
(133, 5, 'I''ve just come from Laos.', 'ฉันเพิ่งกลับมาจากประเทศลาวค่ะ', 'Chăn phêerng glàp maa jàak bprà-thêt Laao khâ', 'I - just - return - come - from - Laos - polite particle', '', 'f5_37'),
(134, 5, 'Language', 'ภาษา', 'Pha-săa', '', '', 'f5_38'),
(135, 5, 'I speak Japanese.', 'ฉันพูดภาษาญี่ปุ่นค่ะ', 'Chăn phût pha-săa Yîi-bpùn khâ', 'I - speak - language - Japan - polite particle', '', 'f5_39'),
(136, 6, 'Black', 'สีดำ', 'Sĭi dam', '', '', 'f6_1'),
(137, 6, 'White', 'สีขาว', 'Sĭi khăao', '', '', 'f6_2'),
(138, 6, 'Sky blue', 'สีฟ้า', 'Sĭi fáa', 'colour - sky', '', 'f6_3'),
(139, 6, 'Navy blue', 'สีน้ำเงิน', 'Sĭi nám ngern', 'colour - water - silver', '', 'f6_4'),
(140, 6, 'Green', 'สีเขียว', 'Sĭi khiăao', '', '', 'f6_5'),
(141, 6, 'Red', 'สีแดง', 'Sĭi daaeng', '', '', 'f6_6'),
(142, 6, 'Orange', 'สีส้ม', 'Sĭi sôhm', '', '', 'f6_7'),
(143, 6, 'Pink', 'สีชมพู', 'Sĭi chom-pou', '', '', 'f6_8'),
(144, 6, 'Brown', 'สีน้ำตาล', 'Sĭi náam-dtaan', 'colour - sugar', '', 'f6_9'),
(145, 6, 'Purple', 'สีม่วง', 'Sĭi mûang', '', '', 'f6_10'),
(146, 6, 'Yellow', 'สีเหลือง', 'Sĭi lĕuang', '', '', 'f6_11'),
(147, 6, 'Dark colour', 'สีเข้ม / สีแก่', 'Sĭi khêm / Sĭi gàae', '', '', 'f6_12'),
(148, 6, 'Dark green', 'สีเขียวเข้ม / สีเขียวแก่', 'Sĭi khiăao khêm / Sĭi khiăao gàae', '', '', 'f6_13'),
(149, 6, 'Light colour', 'สีอ่อน', 'Sĭi àawn', '', '', 'f6_14'),
(150, 6, 'A white car', 'รถยนต์สีขาว', 'Róht yohn sĭi khăao', '', '', 'f6_15'),
(151, 6, 'Yellow Shirt', 'เสื้อเหลือง', 'Sêuua lĕuang', 'shirt - yellow', '', 'f6_16'),
(152, 6, 'Do you have this in red?', 'คุณมีแบบนี้แต่เป็นสีแดงไหมคะ', 'Khun mii bàaep níi dtàae bpen sĭi daaeng mái khá?', 'you - have - style - this - but - be - colour - red - or not - polite particle?', '', 'f6_17'),
(153, 6, 'Today it''s lucky to wear green.', 'วันนี้โชคดีที่ใส่สีเขียวค่ะ', 'Wan níi chôhk dii thîi sài sĭi khiăao khâ', 'day - this - luck - good - to - put on - colour - green - polite particle', 'The word ''thîi'' can have a variety of meanings including  ''at'', ''that'', ''which'' and ''for''. In Thailand each day of the week has a lucky and unlucky colour, a tradition based on Hindu mythology.', 'f6_18'),
(154, 7, 'Dog', 'หมา', 'Măa', '', '', 'f7_1'),
(155, 7, 'Cat', 'แมว', 'Maeo', '', '', 'f7_2'),
(156, 7, 'Elephant', 'ช้าง', 'Cháang', '', 'The elephant is a symbol of Thailand as they were used historically to fight against invaders. It is believed that elephants saved Thailand from colonisation.', 'f7_3'),
(157, 7, 'Monkey', 'ลิง', 'Ling', '', '', 'f7_4'),
(158, 7, 'Tiger', 'เสือ', 'Sĕua', '', '', 'f7_5'),
(159, 7, 'Snake', 'งู', 'Nguu', '', '', 'f7_6'),
(160, 7, 'Mosquito', 'ยุง', 'Yung', '', '', 'f7_7'),
(161, 7, 'Insect, bug', 'แมลง', 'Máa-laaeng', '', '', 'f7_8'),
(162, 7, 'Ant', 'มด', 'Móht', '', '', 'f7_9'),
(163, 7, 'Red ant', 'มดแดง', 'Móht daaeng', 'ant - red', '', 'f7_10'),
(164, 7, 'Fire ant', 'มดคันไฟ', 'Móht khan fai', 'ant - itch - fire', '', 'f7_11'),
(165, 7, 'Frog', 'กบ ', 'Gòhp', '', 'It is common in Thailand for people to eat frogs. Live frogs are sold at many fresh markets.', 'f7_12'),
(166, 7, 'Mouse / Rat', 'หนู ', 'Nŭu', '', 'Rats are sometimes grilled and eaten with rice, especially in rural Isan.', 'f7_13'),
(167, 7, 'Fish', 'ปลา', 'Bplaa', '', '', 'f7_14'),
(168, 7, 'Pig', 'หมู', 'Mŭu', '', '', 'f7_15'),
(169, 7, 'Water buffalo', 'ควาย ', 'Khwaai', '', 'Buffaloes were traditionally used for rice farming, a practice which is still common in poorer areas. The buffalo is associated with lack of intelligence when used to describe a person.', 'f7_16'),
(170, 7, 'Bird', 'นก ', 'Nók', '', '', 'f7_17'),
(171, 7, 'Chicken', 'ไก่', 'Gài', '', '', 'f7_18'),
(172, 7, 'Duck', 'เป็ด ', 'Bpèt', '', '', 'f7_19'),
(173, 7, 'Pet', 'สัตว์เลี้ยง', 'Sàt líiang', 'animal - look after', '', 'f7_20'),
(174, 7, 'There are snakes in the rice fields.', 'มีงูยู่ในนาข้าวค่ะ', 'Mii nguu yùu nai naa khâao khâ', 'there are - snake - situated - in - field - rice - polite particle', '', 'f7_21'),
(175, 7, 'There are a lot of elephants in Surin.', 'ที่สุรินทร์มีช้างเยอะ', 'Thîi Sòo-rin mii cháang yúh', 'at - Surin - there are - elephant - many', '', 'f7_22'),
(176, 7, 'We have a dog for security.', 'เรามีหมาเพื่อรักษาความปลอดภัยค่ะ', 'Rao mii măa phêuua rák-săa khwaam bplàawt phai khâ ', 'we - have - dog - for the purpose of - take care - prefix which converts adjective or verb into  a noun - free from - harm - polite particle', '', 'f7_23'),
(177, 7, 'There are a lot of mosquitoes in the rainy season.', 'ยุงเยอะในช่วงฤดูฝน', 'Yung yúh nai chûaang réu-doo fŏhn', 'mosquito - many - in - period - season - rain', '', 'f7_24'),
(178, 8, '0', 'ศูนย์', 'Sǔun', '', 'Thai has its own characters for numbers but they are rarely used in everyday writing. They can be found on Thai bank notes. The character for ''zero'' is ''๐''.', 'f8_1'),
(179, 8, '1, 2, 3, 4,5 ', 'หนึ่ง, สอง, สาม, สี่, ห้า', 'Nèung, săawng, săam, sìi, hâa', '', 'Thai characters ๑, ๒, ๓, ๔, ๕', 'f8_2'),
(180, 8, '6, 7, 8, 9, 10', 'หก, เจ็ด, แปด, เก้า, สิบ', 'Hòk, jèt, bpàet, gâao, sìp', '', 'Thai characters ๖, ๗, ๘, ๙, ๑๐', 'f8_3'),
(181, 8, '11', 'สิบเอ็ด', 'Sìp-èt', '', '', 'f8_4'),
(182, 8, '12', 'สิบสอง', 'Sìp-săawng', '', '', 'f8_5'),
(183, 8, '13', 'สิบสาม', 'Sìp-săam', '', '', 'f8_6'),
(184, 8, '14', 'สิบสี่', 'Sìp-sìi', '', '', 'f8_7'),
(185, 8, '15', 'สิบห้า', 'Sìp-hâa', '', '', 'f8_8'),
(186, 8, '16', 'สิบหก', 'Sìp-hòk', '', '', 'f8_9'),
(187, 8, '17', 'สิบเจ็ด', 'Sìp-jèt', '', '', 'f8_10'),
(188, 8, '18', 'สิบแปด', 'Sìp-bpàet', '', '', 'f8_11'),
(189, 8, '19', 'สิบเก้า', 'Sìp-gâao', '', '', 'f8_12'),
(190, 8, '20', 'ยี่สิบ', 'Yîi-sìp', '', '', 'f8_13'),
(191, 8, '21', 'ยี่สิบเอ็ด', 'Yîi-sìp-èt', '', '', 'f8_14'),
(192, 8, '22', 'ยี่สิบสอง', 'Yîi-sìp-săawng', '', '', 'f8_15'),
(193, 8, '30', 'สามสิบ', 'Săam-sìp', '', '', 'f8_16'),
(194, 8, '31', 'สามสิบเอ็ด', 'Săam-sìp-èt', '', '', 'f8_17'),
(195, 8, '40', 'สี่สิบ', 'Sìi-sìp', '', '', 'f8_18'),
(196, 8, '80', 'แปดสิบ', 'Bàet-sìp', '', '', 'f8_19'),
(197, 8, '100', 'หนึ่งร้อย / ร้อยหนึ่ง', 'Nèung-róoi / Róoi-nèung', '', 'Sometimes pronounced ''lóoi''', 'f8_20'),
(198, 8, '134', 'หนึ่งร้อยสามสิบสี่', 'Nèung-róoi săam-sìp-sìi', '', '', 'f8_21'),
(199, 8, '300', 'สามร้อย', 'Săam róoi', '', '', 'f8_22'),
(200, 8, '1000', 'หนึ่งพัน', 'Nèung-phan', '', '', 'f8_23'),
(201, 8, '2000', 'สองพัน', 'Sŏng-phan', '', '', 'f8_24'),
(202, 8, '10,000', 'หนึ่งหมื่น', 'Nèung-mèun', '', '', 'f8_25'),
(203, 8, '50,000', 'ห้าหมื่น', 'Hâa-mèun', '', '', 'f8_26'),
(204, 8, '100,000', 'หนึ่งแสน', 'Nèung-săen', '', '', 'f8_27'),
(205, 8, '600,000', 'หกแสน', 'Hòk-săen', '', '', 'f8_28'),
(206, 8, '1,000,000', 'หนึ่งล้าน', 'Nèung-láan', '', '', 'f8_29'),
(207, 9, 'Minute', 'นาที', 'Naa-thii', '', '', 'f9_1'),
(208, 9, 'Hour', 'ชั่วโมง', 'Chûaa-mohng', '', '', 'f9_2'),
(209, 9, 'Day', 'วัน', 'Wan', '', '', 'f9_3'),
(210, 9, 'Week', 'อาทิตย์ / สัปดาห์', 'Aa-thít / Sàp-daa', '', '', 'f9_4'),
(211, 9, 'Month', 'เดือน', 'Deuan', '', '', 'f9_5'),
(212, 9, 'Year', 'ปี', 'Bpii', '', '', 'f9_6'),
(213, 9, 'Today', 'วันนี้', 'Wan níi', '', '', 'f9_7'),
(214, 9, 'Tomorrow', 'พรุ่งนี้', 'Phrûng-níi', '', '', 'f9_8'),
(215, 9, 'Yesterday', 'เมื่อวาน', 'Mêua wan', '', '', 'f9_9'),
(216, 9, 'This week', 'อาทิตย์นี้ / สัปดาห์นี้', 'Aa-thít níi / Sàp-daa níi', 'week - this', '', 'f9_10'),
(217, 9, 'Next week', 'อาทิตย์หน้า / สัปดาห์หน้า', 'Aa-thít nâa / Sàp-daa nâa', 'week - next', '', 'f9_11'),
(218, 9, 'Last week', 'อาทิตย์ที่แล้ว / สัปดาห์ที่แล้ว', 'Aa-thít thîi-láew / Sàp-daa thîi-láew', 'week - previous', '', 'f9_12'),
(219, 9, 'Next month', 'เดือนหน้า', 'Deuan nâa', 'month - next', '', 'f9_13'),
(220, 9, 'Last month', 'เดือนที่แล้ว', 'Deuan thîi-láew', 'month - previous', '', 'f9_14'),
(221, 9, 'Last year', 'ปีที่แล้ว', 'Bpii thîi-láew', 'year - previous', '', 'f9_15'),
(222, 9, 'Right now', 'เดี๋ยวนี้', 'Dĭiao níi', 'moment - this', '', 'f9_16'),
(223, 9, 'In a moment', 'อีกสักครู่', 'Èek dĭiao', 'another/more - moment', '', 'f9_17'),
(224, 9, 'Just a moment ago', 'เมื่อครู่นี้', 'Mêua khrûu níi', 'point in time - a short moment - this', '', 'f9_18'),
(225, 9, 'You''re early', 'คุณมาเร็วจัง', 'Khun maa reo jang', 'you - come - fast - really', '', 'f9_19'),
(226, 9, 'He came late', 'เขามาช้าค่ะ', 'Khăo maa cháa khâ', 'he - come - slow/late - polite particle', '', 'f9_20'),
(227, 9, 'Come home late', 'กลับบ้านช้า', 'Glàp bâan cháa', 'return - home - slow/late', '', 'f9_21'),
(228, 9, 'Later on, afterwards', 'หลังจาก', 'Lăng jàak', 'behind - from', '', 'f9_22'),
(229, 9, 'Morning', 'เช้า', 'Cháao', '', '', 'f9_23'),
(230, 9, 'Afternoon', 'บ่าย', 'Bàai', '', '', 'f9_24'),
(231, 9, 'Evening', 'เย็น', 'Yen', '', '', 'f9_25'),
(232, 9, 'Night', 'กลางคืน', 'Glaang kheun', 'in the centre of - night', '', 'f9_26'),
(233, 9, 'In the early evening', 'ตอนเย็น', 'Dtawn yen', 'at (time of day) - early evening', '', 'f9_27'),
(234, 9, 'At night', 'ในเวลากลางคืน', 'Nai waeh-lah glaang-kheun', 'in - time - night', '', 'f9_28'),
(235, 9, 'This morning', 'เช้านี้', 'Cháao níi', 'morning - this', '', 'f9_29'),
(236, 9, 'Last night', 'เมื่อคืน', 'Mêua kheun', 'point in time - night', '', 'f9_30'),
(237, 9, 'All day', 'ตลอดวัน', 'Dtà-làwt wan', 'throughout - day', '', 'f9_31'),
(238, 9, 'What''s the time?', 'ตอนนี้กี่โมงคะ', 'Dtàwn níi gìi mohng khá?', 'moment - this - how many - hour - polite particle?', '', 'f9_32'),
(239, 9, '12am midnight', 'เที่ยงคืน', 'Thîiang kheun', '12:00 - night', '', 'f9_33'),
(240, 9, '2am', 'ตีสอง', 'Dtee săawng', 'after midnight - two', 'From 1AM to 5AM, use the word “dtee” followed by the hour.', 'f9_34'),
(241, 9, '4:30am', 'ตีสี่ครึ่ง', 'Dtee sìi khrêung', 'after midnight - four - half', '', 'f9_35'),
(242, 9, '5am', 'ตีห้า', 'Dtee hâa', 'after midnight - five', '', 'f9_36'),
(243, 9, '6am', 'หกโมงเช้า', 'Hòhk mohng cháao', 'six - hour - morning', 'From 6AM to 11AM, use the hour followed by “mohng cháao”. ', 'f9_37'),
(244, 9, '7am', 'เจ็ดโมงเช้า / หนึ่งโมงเช้า', 'Jèt mohng cháao / Nèung mohng cháao', 'seven - hour - morning / one - hour - morning', 'From 7AM to 11AM, some people count 7AM as 1, 8AM as 2 and so on. This comes from the tradition of the temples sounding a drum once at 7AM, twice at 8AM etc.', 'f9_38'),
(245, 9, '8am', 'แปดโมงเช้า / สองโมงเช้า ', 'Bpàet mohng cháao / Săawng mohng cháao', 'eight - hour - morning / two - hour - morning', '', 'f9_39'),
(246, 9, '10:15am', 'สิบโมงสิบห้า / สี่โมงสิบห้า', 'Sìp mohng sìp-hâa  / Sìi mohng sìp-hâa', 'ten - hour  - fifteen / four - hour - fifteen', 'You do not say ''cháao'' when including minutes past the hour.', 'f9_40'),
(247, 9, '12pm', 'เที่ยง', 'Thîiang', 'noon', '', 'f9_41'),
(248, 9, '12:45pm', 'เที่ยงสี่สิบห้า', 'Thîiang sìi sìp hâa', 'noon - forty-five', '', 'f9_42'),
(249, 9, '1pm', 'บ่ายโมง', 'Bàai mohng', 'afternoon - hour', '', 'f9_43'),
(250, 9, '2pm', 'บ่ายสองโมง', 'Bàai săawng mohng', 'afternoon - two - hours', 'From 1PM to 4PM, use the word “bàai” followed by the hour, then “mohng”.', 'f9_44'),
(251, 9, '4pm', 'สี่โมงเย็น / บ่ายสี่โมง', 'Sìi mohng yen / Bàai sìi mohng', 'four - hour - early evening / afternoon - four - hour', 'Late afternoon / early evening is known as ''yen''. 4PM may be ''bàai'' or ''yen''.', 'f9_45'),
(252, 9, '5:15pm', 'ห้าโมงสิบห้า', 'Hâa mohng sìp-hâa', 'five - hour - fifteen', 'For 5PM and 6PM use the hour followed by ''mohng yen''. If there are mintues you can omit ''yen''.', 'f9_46'),
(253, 9, '7pm', 'หนึ่งทุ่ม / ทุ่มหนึ่ง ', 'Nèung thûm / Thûm nèung', 'one - evening / evening - one', 'ทุ่ม (Thûm) means ''evening''. The evening hours follow a similar convention to the morning, with 7PM being 1, 8PM being 2 and so on until 11PM. However, unlike the morning there tends to be just this one system.', 'f9_47'),
(254, 9, '7:30pm', 'ทุ่มครึ่ง / หนึ่งทุ่มครึ่ง', 'Thûm khrêung / Nèung thûm khrêung', 'evening - half / one - evening - half', '', 'f9_48'),
(255, 9, '8:20pm', 'สองทุ่มยี่สิบ', 'Săawng thûm yîi-sìp ', 'two - evening - twenty', '', 'f9_49'),
(256, 9, '9pm', 'สามทุ่ม ', 'Săam thûm', 'three - evening', '', 'f9_50'),
(257, 9, '11:25pm', 'ห้าทุ่มยี่สิบห้า', 'Hâa thûm yîi-sìp-hâa', 'five - evening - twenty-five', '', 'f9_51'),
(258, 9, 'How long have you been married?', 'คุณแต่งงานกี่ปีมาแล้วคะ', 'Khun dtàeng-ngaan gìi bpii maa láew khá? ', 'you - married - how many - year - come - already - polite particle?', '', 'f9_52'),
(259, 9, 'I have been in Thailand a long time.', 'ฉันอยู่เมืองไทยนานแล้วค่ะ', 'Chăn yùu me-ung Thai nahn láew khâ', 'I - stay - country - Thai - long time - already - polite particle', '', 'f9_53'),
(260, 9, 'How long does it take to get to Ayutthaya by train?', 'ไปอยุธยาโดยรถไฟใช้เวลานานเท่าไหร่คะ', 'Bpai À-yóot-thá-yaa dooy rót fai chái waeh-lah naan thâo-rai khá?', 'go - Ayutthaya - by - train - use - time - long time - how much - polite particle?', '', 'f9_54'),
(261, 10, 'I/me (female speaker)', 'ฉัน', '(di-)chăn', '', 'The prefix ''di'' is used in formal speech and writing only. ''Chăn'' is also sometimes used by males in a personal setting. Thais will often use their nickname when referring to themselves. Parents will usually use the words for mother or father when referring to themselves in a family setting.', 'f10_1'),
(262, 10, 'I/me (male speaker)', 'ผม', 'Pŏm', '', '', 'f10_2'),
(263, 10, 'We/us', 'เรา', 'Rao', '', 'Can also mean ''I/me'' in an informal setting.', 'f10_3'),
(264, 10, 'You (singular and plural)', 'คุณ', 'Kun', '', 'Thais often use names or kinship terms instead of ''kun''.', 'f10_4'),
(265, 10, 'You (familiar)', 'ตัวเอง', 'Dtuaa aeng', 'self - oneself', '', 'f10_5'),
(266, 10, 'He/him, she/her', 'เขา', 'Khăo', '', 'Often pronounced ''kháo''. This pronunciation is also used by young people to mean ''I/me''.', 'f10_6'),
(267, 10, 'You (informal), she/her', 'เธอ', 'Thuuhr', '', 'It is more common to use the person''s name when referring to a female.', 'f10_7'),
(268, 10, 'They/them (male/female)', 'พวกเขา', 'Phûak khăo', 'group of - him', '', 'f10_8'),
(269, 10, 'They/them (female)', 'พวกเธอ', 'Phûak thuuhr', 'group of - her', '', 'f10_9'),
(270, 10, 'You/him/her/they/them (for people of high status)', 'ท่าน', 'Tûn', '', '', 'f10_10'),
(271, 10, 'It', 'มัน', 'Mun', '', 'Used for animals as well as objects.', 'f10_11'),
(272, 10, 'Please give it to Mr Komgrit.', 'ช่วยเอามาให้คุณคมกริต', 'Chûay ao maa hâi khun Komgrit ', 'help - take to - give - title of respect - Komgrit', 'The words ''ao maa'' together mean ''take to''.', 'f10_12'),
(273, 10, 'Teacher, I have finished.', 'คุณครู เสร็จแล้วค่ะ', 'Khun khruu, sèt láew khâ.', 'title of respect - teacher - finish -  past tense marker - polite particle', 'It is common to omit pronouns if the context makes it obvious.', 'f10_13'),
(274, 10, 'Oneself / yourself / himself / herself', 'ตัว', 'Dtuaa', '', '', 'f10_14'),
(275, 10, 'Go and get dressed!', 'ไปแต่งตัว!', 'Bpai dtàeng dtuaa', 'go - dress - yourself', '', 'f10_15'),
(276, 10, 'Take care of yourself', 'ดูแลตัวเองด้วยนะคะ', 'Doo-lae dtuaa-aeng dûay ná khâ', 'look after - yourself - request particle - softening particle - polite particle', '', 'f10_16'),
(277, 10, 'Each other / one another / together', 'กัน', 'Gun', '', '', 'f10_17'),
(278, 10, 'Father and mother love each other.', 'พ่อแม่รักกันค่ะ', 'Phâaw mâe rúk gun khâ', 'father - mother - love - each other - polite particle', '', 'f10_18'),
(279, 10, 'Belonging to', 'เป็นของ', 'Bpen kăwng', '', '', 'f10_19'),
(280, 10, 'Whose car is that? It''s Mum''s.', 'นั่นรถของใครคะ ของแม่ค่ะ', 'Nân róht kăwng krai khá? Kăwng mâe khâ', 'that - car - belonging to - who - polite particle? belonging to - mother - polite particle', '', 'f10_20'),
(281, 10, 'Your dress is pretty.', 'กระโปรงของคุณสวยค่ะ', 'Grà-bprohng kăwng khun sŭay khâ', 'dress - belonging to - you - pretty - polite particle', '', 'f10_21'),
(282, 10, 'How much is this?', 'นี่ราคาเท่าไหร่คะ', 'Nîi raa-khaa thâo rai khá?', 'this - price - equal to - what - polite particle?', '', 'f10_22'),
(283, 10, 'This table is bigger than that one.', 'โต๊ะตัวนี้ใหญ่กว่าโต๊ะตัวนั้น', 'Dtó dtuaa níi yài gwàa dtó dtuaa nán', 'table - classifier - this - big - more than - table - classifier - that', '', 'f10_23'),
(284, 10, 'Has anyone finished?', 'มีใครเสร็จยังคะ', 'Mii krai sèt yang khá?', 'is there - anyone - finish - yet - polite particle?', '', 'f10_24'),
(285, 10, 'There''s no one here.', 'ไม่มีใครอยู่ที่นี่เลยค่ะ', 'Mâi mii krai yùu thîi nîi leuuy khâ', 'not - exist - anyone - situated - place - this - at all - polite particle', '', 'f10_25'),
(286, 10, 'Do you know anyone who can play the guitar?', 'คุณรู้จักใครที่เล่นกีต้าร์เป็นไหมคะ', 'Khun rúu-jàk krai thîi lên gii-dtâa bpen mái khá?', 'you - know - anyone - that - play - guitar - know how to - or not - polite particle?', '', 'f10_26'),
(287, 10, 'There''s nothing good on TV.', 'ทีวีไม่มีอะไรดูเลย', 'Thii-wii mâi mii à-rai duu leuuy', 'tv - not - have - anything - watch - at all', '', 'f10_27'),
(288, 10, 'I want to buy something to take home.', 'ฉันอยากซื้ออะไรกลับบ้านค่ะ', 'Chăn yàak séu à-rai glàp bâan khâ', 'I - want - buy - something - return - home - polite particle', '', 'f10_28'),
(289, 10, 'He doesn''t want to go anywhere.', 'เขาไม่อยากไปไหนค่ะ', 'Khăo mâi yàak bpai năi khâ', 'he - not - want - go - anywhere - polite particle', '', 'f10_29'),
(290, 10, 'Is there somewhere we can play soccer?', 'มีที่ไหนที่เราสามารถเล่นฟุตบอลได้คะ', 'Mii thîi năi thîi rao săa-mâat lên fút-baawn dâi khá? ', 'is there - place - which - that - we - can - play - football - can - polite particle?', '', 'f10_30'),
(291, 11, 'I only have 10 baht.', 'มีแค่สิบบาทค่ะ', 'Mii khâae sìp bàat khâ', 'have - to the extent of - ten - baht - polite particle', '', 'f11_1'),
(292, 11, 'We don''t have any rice.', 'เราไม่มีข้าวค่ะ', 'Rao mâi mii khâao khâ', 'we - not - have - rice - polite particle', 'The word ''khâao'' means rice but can also be used to refer to food in general.', 'f11_2'),
(293, 11, 'Do you have any other colours?', 'มีสีอื่นอีกไหมคะ', 'Mii sĭi èuun èek mái khá?', 'have - color - other - another - or not - polite particle?', '', 'f11_3'),
(294, 11, 'There''s no hot water', 'ไม่มีน้ำร้อนค่ะ', 'Mâi mii náam rórn khâ', 'not - there is - water - hot - polite particle', 'The word ''mii'' is used in ''there is'' type expressions.', 'f11_4'),
(295, 11, 'There is a temple behind the market', 'มีวัดอยู่หลังตลาดค่ะ', 'Mii wát yùu lăng dtà-làad khâ', 'there is - temple - situated - behind - market - polite particle', '', 'f11_5'),
(296, 11, 'He''s my friend.', 'เขาเป็นเพื่อนของฉันค่ะ', 'Khăo bpen phêuuan kăwng chăn khâ', 'he - is - friend - belonging to - me - polite particle', 'The word ''bpen'' is the most common equivalent of the verb ''to be''. ', 'f11_6'),
(297, 11, 'My mother is kind', 'แม่เป็นคนดี', 'Mâe bpen khon dii', 'mother - is - person - good', '', 'f11_7'),
(298, 11, 'Joom is his girlfriend.', 'จุ๋มเป็นแฟนเขาค่ะ', 'Jŏom bpen faen khăo khâ', 'Joom - is - girlfriend - him - polite particle', '', 'f11_8'),
(299, 11, 'Do you know how to swim?', 'คุณว่ายน้ำเป็นไหมคะ', 'Khun wâi náam bpen mái khá?', 'you - swim - water - know how to - or not - polite particle?', 'We use ''bpen'' to express the idea of ''knowing how to do something''.', 'f11_9'),
(300, 11, 'To have the flu', 'เป็นไข้หวัด', 'Bpen khâi wàt', 'suffer from - fever - cold', 'We use ''bpen'' to mean ''suffer from'' in the case of health issues.', 'f11_10'),
(301, 11, 'Come and eat!', 'มากินข้าวกันค่ะ', 'Maa gin khâao gan khâ', 'come - eat - rice - together - polite particle', '', 'f11_11'),
(302, 11, 'The bus is coming.', 'รถเมล์มาแล้วค่ะ', 'Rót maeh maa láew khâ', 'vehicle - bus - come - already/now - polite particle', '', 'f11_12'),
(303, 11, 'Come round for a visit', 'มาเยี่ยม', 'Maa yîiam', 'come - visit', 'As well as meaning ''visit'', ''yîiam'' also means ''very good''.', 'f11_13'),
(304, 11, 'There''s a call coming.', 'มีสายโทรศัพท์เข้ามาค่ะ', 'Mii săai thoh-rá-sàp khâo maa khâ', 'there is - call - phone - enter - come - polite particle', 'As well as meaning ''come'' and ''go'', ''maa'' and ''bpai'' are used with some verbs to indicate the direction of an action.', 'f11_14'),
(305, 11, 'Are you ready to go?', 'คุณพร้อมที่จะไปหรือยังคะ', 'Khun phráawm thîi jà bpai rĕuu yang khá?', 'you - ready - to - future marker - go - or - not yet - polite particle?', '', 'f11_15'),
(306, 11, 'Let''s go shopping.', 'ไปซื้อของกันค่ะ', 'Bpai séu kăwng gan khâ', 'go - buy - stuff - together - polite particle', '', 'f11_16'),
(307, 11, 'Go out/around for pleasure', 'ไปเที่ยว', 'Bpai thîaao', 'go - trip', '', 'f11_17'),
(308, 11, 'I''m going to the market.', 'ฉันกำลังจะไปตลาดค่ะ', 'Chăn gamlang-jà bpai dtà-làad khâ', 'I - about to - go - market - polite particle', '', 'f11_18'),
(309, 11, 'He left already.', 'เขาไปแล้วค่ะ', 'Khăo bpai láew khâ', 'he - go - already - polite particle', '', 'f11_19'),
(310, 11, 'These things are too expensive', 'พวกนี้แพงเกินไป', 'Phûak níi phaaeng gern bpai', 'a group of - this - expensive - exceed - go', '', 'f11_20'),
(311, 11, 'I can come back tomorrow', 'ฉันกลับมาพรุ่งนี้ได้ค่ะ', 'Chăn glùp maa phrôong-níi dâi khâ', 'I - return - come - tomorrow - can - polite particle', 'We use ''dai'' to talk about whether something is possible or not.', 'f11_21'),
(312, 11, 'Can I borrow your car?', 'ขอยืมรถคุณได้ไหมคะ', 'Kŏr yeuum rót khun dâi mái khá?', 'request - borrow - car - you - can - or not - polite particle?', '', 'f11_22'),
(313, 11, 'I can''t eat mushrooms at all', 'ฉันกินเห็ดไม่ได้เลย', 'Chăn gin hèt mâi dâi leeuy', 'I - eat - mushroom - not - can - at all', 'Placing ''mâi dâi'' after a verb means that an action is not possible.', 'f11_23'),
(314, 11, 'I can''t lift it.', 'ฉันยกไม่ได้ค่ะ', 'Chăn yóhk mâi dâi khâ', 'I - lift - not - can - polite particle', '', 'f11_24'),
(315, 11, 'He did not go to Laos', 'เขาไม่ได้ไปประเทศลาวค่ะ', 'Khăo mâi dâi bpai bprà-thêt Lao khâ', 'he - not - did - go - country - Laos - polite particle', 'Placing ''mâi dâi'' before a verb means that the action did not happen.', 'f11_25'),
(316, 11, 'Do you want to go shopping? / Yes, I want to go.', 'ไปช้อปปิ้งกันไหม  ไปไป', 'Bpai chop-pîng gan mái? Bpai bpai!', 'go - shopping - together - or not? go - go!', '', 'f11_26'),
(317, 11, 'Do you want to go to the market? / Yes, I''ll go if you want.', 'ไปตลาดกันไหม  ไปก็ได้', 'Bpai dtà-làad gan mái? Bpai gôr-dâi', 'go - market - together - or not? go - as you like', '', 'f11_27'),
(318, 11, 'Whatever you like', 'อะไรก็ได้ค่ะ', 'À-rai gôr-dâi khâ', 'anything - ok - polite particle', '', 'f11_28'),
(319, 11, 'You don''t need to bring anything.', 'คุณไม่ต้องเอาอะไรไปเลยค่ะ', 'Khun mâi dtôrng ao à-rai bpai leeuy khâ', 'you - not - need to - bring - anything - outgoing direction - at all - polite particle', 'The word ''dtôrng'' is similar to ''have to'' or ''must''', 'f11_29'),
(320, 11, 'I have to go to work.', 'ฉันต้องไปทำงานแล้วค่ะ', 'Chăn dtôrng bpai tham-ngaan láew khâ', 'I  - have to - go - work - now - polite particle', '', 'f11_30'),
(321, 11, 'When do we have to finish?', 'เราต้องทำงานให้เสร็จเมื่อไหร่คะ', 'Rao dtôrng tham-ngaan hâi sèt mêuua-rai khá?', 'we - have to - work - give - finish - when - polite particle?', '', 'f11_31'),
(322, 11, 'You should go to the doctor.', 'คุณควรจะไปหาหมอนะคะ', 'Khun khuaan jà bpai hăa mŏr ná khâ ', 'you - should - future marker - go - visit - doctor - softening particle - polite particle ', '', 'f11_32'),
(323, 11, 'We should get there early.', 'เราควรจะถึงเร็วหน่อยนะคะ', 'Rao khuaan jà thĕung reo nòy ná khâ', 'we - should - future marker - arrive - early - particle used to soften a request - softening particle - polite particle', '', 'f11_33'),
(324, 11, 'Do you want to eat out?', 'คุณอยากจะไปทานข้าวนอกบ้านไหมคะ', 'Khun yàak jà bpai thaan khâao nâawk bâan mái khá?', 'you - want to - future marker - eat - rice - outside - home - or not - polite particle?', '', 'f11_34'),
(325, 11, 'He doesn''t want to play.', 'เขาไม่อยากเล่นค่ะ', 'Khăo mâi yàak lên khâ', 'he - not - want to - play - polite particle', '', 'f11_35'),
(326, 11, 'I gave the money to my mother.', 'ฉันให้เงินแม่ไปแล้วค่ะ', 'Chăn hâi ngern mâe bpai láew khâ', 'I - give - money - mother - outgoing direction - past action marker - polite particle', '', 'f11_36'),
(327, 11, 'The boss let me go home early.', 'เจ้านายให้ฉันกลับบ้านเร็วค่ะ', 'Jâo-naai hâi chăn glàp bâan reo khâ', 'boss - allow - me - return - home - early - polite particle', 'As well as meaning ''give'', ''hâi'' can also mean ''allow/let''', 'f11_37'),
(328, 11, 'Let me see it.', 'ขอฉันดูหน่อยค่ะ', 'Kŏr chăn duu nòy khâ', 'request - me - see - particle used to soften a request - polite particle', '', 'f11_38'),
(329, 11, 'Please bring the book to school tomorrow.', 'ช่วยเอาหนังสือมาโรงเรียนพรุ่งนี้ด้วยนะคะ', 'Chûay ao năng-sĕu maa rohng-rian phrûng-níi dûay ná khâ', 'help - bring - book - come - school - tomorrow - particle used at the end of a request - softening particle - khâ', 'The word ''ao'' can mean ''take'', ''accept'' or ''bring''.', 'f11_39'),
(330, 11, 'I''ll have a green tea.', 'ฉันเอาชาเขียวค่ะ', 'Chăn ao chaa kiăao khâ', 'I - take/want - tea - green - polite particle', '', 'f11_40'),
(331, 11, 'Who broke the glass?', 'ใครทำแก้วแตกคะ', 'Khrai tum gâaeo dtàaek khá?', 'who - cause - drinking glass - break - polite particle', 'The word ''tum'' expresses the idea of causation. It is similar to ''do''.', 'f11_41'),
(332, 11, 'He works at the hospital.', 'เขาทำงานที่โรงพยาบาลค่ะ', 'Khăo tum-ngaan thîi rohng-phá-yaa-baan khâ', 'he - work - at - hospital - polite particle', '', 'f11_42'),
(333, 11, 'How do I use this thing?', 'อันนี้ใช้ยังไงคะ', 'An-níi chái yang-ngai khá?', 'this one - use - how - polite particle?', '', 'f11_43'),
(334, 12, 'Did you like the movie? Yes.', 'คุณชอบหนังเรื่องนี้ไหมคะ? ชอบค่ะ', 'Khun chôrp năng rêuuang níi mái khá? Chôrp khâ', 'you - like - movie - classifier - this - or not - polite particle? like - polite particle', 'Adding ''mái'' to the end of a statement turns it into a question.', 'f12_1');