INSERT INTO `phrasesM` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(332, 12, 'Did you like the movie? Yes.', 'คุณชอบหนังเรื่องนี้ไหมครับ ชอบครับ', 'Khun chôrp năng rêuuang níi mái khráp? Chôrp khráp', 'you - like - movie - classifier - this - or not - polite particle? like - polite particle', 'Adding ''mái'' to the end of a statement turns it into a question.', 'm12_1'),
(333, 12, 'Is it raining? No.', 'ฝนตกไหมครับ ไม่ตกครับ', 'Fŏhn dtòk mái khráp? Mâi dtòk khráp', 'rain - fall - or not - polite particle? not - fall - polite particle', '', 'm12_2'),
(334, 12, 'Is it tasty? Yes.', 'อร่อยไหมครับ อร่อยครับ', 'À-ròy mái khráp? À-ròy khráp', 'tasty - or not - polite particle? tasty - polite particle', '', 'm12_3'),
(335, 12, 'Was it expensive? No.', 'แพงไหมครับ ไม่แพงครับ', 'Phaaeng mái khráp? Mâi phaaeng khráp', 'expensive - or not - polite particle? not - expensive - polite particle', '', 'm12_4'),
(336, 12, 'You''re going shopping, right? Yes.', 'คุณกำลังจะไปซื้อของใช่ไหมครับ ใช่ครับ', 'Khun gamlang-jà bpai séu kăwng châi mái khráp? Châi khráp', 'you - about to - go - buy - stuff - yes - or no - polite particle? yes - polite particle', 'We use ''châi mái'' when there is an assumption which needs confirmation. ', 'm12_5'),
(337, 12, 'Your mother is Thai, right? No.', 'แม่เป็นคนไทยใช่ไหมครับ ไม่ใช่ครับ', 'Mâe bpen khon Thai châi mái khráp? Mâi-châi khráp', 'mother - is - person - Thai - yes - or no - polite particle? no - polite particle', '', 'm12_6'),
(338, 12, 'Mook is your girlfriend, isn''t she? No.', 'มุกเป็นแฟนคุณไม่ใช่หรอครับ ไม่ใช่ครับ!', 'Móok bpen faen khun mâi-châi răw khráp? Mâi-châi khráp', 'Mook - is - girlfriend - you - no - question word - polite particle? no - polite particle', 'The expression ''mâi châi răw'' is similar to ''châi mái''.', 'm12_7'),
(339, 12, 'You didn''t tell him, did you? Yes (I did).', 'คุณไม่ได้บอกเขาใช่ไหมครับ ผมบอกแล้วครับ', 'Khun mâi dâi bòrk khăo châi mái khráp? Phŏhm bòrk láew khráp', 'you - not - did - tell - him - yes - or no polite particle? I - tell - past action marker - polite particle', '', 'm12_8'),
(340, 12, 'Are you going or not? Yes.', 'คุณจะไปหรือเปล่า ไปครับ', 'Khun jà bpai rĕuu bplàao? Bpai khráp', 'you - future marker - go - or -  not? go - polite particle', 'The term ''rĕuuu bplàao'' expects a straight answer.', 'm12_9'),
(341, 12, 'Is that enough? No.', 'พอแล้วหรือยังครับ ยังครับ', 'Phaaw láew rĕuu yang khráp? Yang khráp', 'enough - already - or - not yet - polite particle? not yet - polite particle', 'The term ''láew rĕuu yang'' means something like ''already or not yet?''. ''Láew'' is often omitted.', 'm12_10'),
(342, 12, 'Has your older sister come home yet? Yes.', 'พี่สาวคุณมาถึงบ้านหรือยังครับ ถึงแล้วครับ', 'Phîi săo khun maa thĕung bâan (láew) rĕuu yang khráp? Thĕung láew khráp', 'older sibling - girl - you - come - arrive - home - (already) - or - not yet - polite particle? arrive - already - polite particle', '', 'm12_11'),
(343, 12, 'What''s the time?', 'กี่โมงแล้วครับ', 'Gìi mohng láew khráp?', 'how many - hour - already - polite particle', '', 'm12_12'),
(344, 12, 'What''s this?', 'อันนี้คืออะไรครับ', 'An níi kheu à-rai khráp?', 'item - this - is - what - polite particle?', '', 'm12_13'),
(345, 12, 'What''s his name?', 'เขาชื่ออะไรครับ', 'Khăo chêu à-rai khráp?', 'he - called - what - polite particle', '', 'm12_14'),
(346, 12, 'Who are you going with?', 'คุณจะไปกับใครครับ', 'Khun jà bpai gùp krai khráp?', 'you - future marker - go - with - who - polite particle?', '', 'm12_15'),
(347, 12, 'Who am I speaking with? (On the phone)', 'ใครกำลังพูดอยู่ครับ', 'Khrai gamlang phôot yùu khráp?', 'who - currently - speak - currently - polite particle?', '', 'm12_16'),
(348, 12, 'Whose is this? It''s mine.', 'นี้ของใครครับ? ของผมครับ', 'Níi kăwng krai khráp? Kăwng phŏhm khráp', 'this - belonging to - who - polite particle? belonging to - me - polite particle', '', 'm12_17'),
(349, 12, 'Which one do you want?', 'คุณอยากได้อันไหนครับ', 'Khun yàak dâi an năi khráp?', 'you - want - receive - piece - which - polite particle?', 'The word ''dâi'' has various uses. In this case it means ''get'' or ''receive''.', 'm12_18'),
(350, 12, 'Where is the nearest sky train station?', 'สถานีรถไฟฟ้าไหนที่ใกล้ที่สุดครับ', 'Sà-thăa-nii rót fai fáa năi thîi glâi thîi-sùt khráp? ', 'station - vehicle - fire - sky - which - that - near - most - polite particle?', '', 'm12_19'),
(351, 12, 'Where were you born?', 'คุณเกิดที่ไหนครับ', 'Khun gèrt thîi năi khráp?', 'you - born - place - which - polite particle', '', 'm12_20'),
(352, 12, 'Where''s my phone?', 'โทรศัพท์ผมอยู่ไหนครับ', 'Thoh-rá-sàp phŏhm yùu năi khráp?', 'phone - me - situated - where - polite particle?', '', 'm12_21'),
(353, 12, 'When is he coming?', 'เขาจะมากี่โมงครับ', 'Khăo jà maa gìi mohng khráp?', 'he - future marker - come - how many - hour - polite particle?', '', 'm12_22'),
(354, 12, 'When did you arrive?', 'คุณมาถึงกี่โมงครับ', 'Khun maa thĕung gìi mohng khráp?', 'you - come - arrive - how many - hour - polite particle?', '', 'm12_23'),
(355, 12, 'What day does school start?', 'เปิดเทอมวันไหนครับ', 'Bpѐrt theerm wan năi khráp?', 'open - term - day - which - polite particle?', '', 'm12_24'),
(356, 12, 'When are you going to tell him?', 'คุณจะบอกเขาเมื่อไรครับ', 'Khun jà bòrk khăo mêuua-rai khráp?', 'you - future marker - tell - him - when - polite particle?', 'The term ''mêuua-rai'' is common when not requesting a specific time or date.', 'm12_25'),
(357, 12, 'Why did you come late?', 'ทำไมมาสายครับ', 'Tham-mai maa săai khráp?', 'why - come - late - polite particle?', '', 'm12_26'),
(358, 12, 'Why didn''t you tell me?', 'ทำไมคุณไม่บอกผมครับ', 'Tham-mai khun mâi bòrk phŏhm khráp?', 'why - you - not - tell - me - polite particle?', '', 'm12_27'),
(359, 12, 'How did you get here?', 'คุณมายังไงครับ', 'Khun maa yang-ngai khráp?', 'you - come - how - polite particle?', 'The term ''yang-ngai'' is an informal pronunciation of ''yang-rai'', meaning ''how'' or ''in what way''.', 'm12_28'),
(360, 12, 'What do you think?', 'คุณคิดว่ายังไงครับ / คุณคิดยังไงครับ', 'Khun khít wâh yang-ngai khráp? / Khun khít yang-ngai khráp?', 'you - think - that - how - polite particle? / you - think - how - polite particle?', '', 'm12_29'),
(361, 12, 'How many people are coming for dinner?', 'มีคนมาทานข้าวเย็นด้วยกันทั้งหมดกี่คนครับ', 'Mii khon maa thaan khâao-yen dûay gan tháng-mòht gìi khon khráp?', 'have - person - come - eat - dinner - together  - with each other - altogether - how many - person - polite particle?', '', 'm12_30'),
(362, 12, 'How many children do you have?', 'คุณมีลูกกี่คนครับ', 'Khun mii lûuk gìi khon khráp?', 'you - have - child - how many - classifier for people - polite particle?', '', 'm12_31'),
(363, 12, 'How much is this?', 'อันนี้เท่าไหร่ครับ', 'An níi thâo rai khráp?', 'item - this - equal to - what - polite particle?', 'How much? questions for which the answer may be numerically quantified may be formed with ''thâo rai'' or ''gìi ...''.', 'm12_32'),
(364, 12, 'How heavy is it?', 'หนักเท่าไหร่ครับ', 'Nák thâo rai khráp?', 'heavy - equal to - what - polite particle?', '', 'm12_33'),
(365, 12, 'How far is Chiang Mai from Bangkok?', 'เชียงใหม่ไกลจากกรุงเทพฯแค่ไหน', 'Chiiang-mài glai jàak groong-thâehp khâae năi? ', 'chiang mai - far - from - bangkok - to the extent of - which?', 'How much? questions which do not necessarily expect a numerical response can be formed with ''khâae năi''.', 'm12_34'),
(366, 12, 'How well do you know him?', 'คุณรู้จักเขาดีแค่ไหนครับ', 'Khun rúu-jàk khăo dii khâae năi khráp?', 'you - know - him - good - to the extent of - which - polite particle?', '', 'm12_35'),
(367, 13, 'I''m not going.', 'ผมไม่ไปครับ', 'Phŏhm mâi bpai khráp', 'I - not - go - polite particle', 'Verbs and adjectives are generally negated by being preceded with ''mâi''.', 'm13_1'),
(368, 13, 'I don''t want it.', 'ผมไม่อยากได้', 'Phŏhm mâi yàak dâi', 'I - not - want - get', 'The verb ''yàak'' must be followed by another verb.  When directed towards a thing, the verb ''dâi'' is used to mean ''get''.', 'm13_2'),
(369, 13, 'We don''t have a bathroom.', 'เราไม่มีห้องน้ำครับ', 'Rao mâi mii hâwng-náam khráp', 'we - not - have - bathroom - polite particle', '', 'm13_3'),
(370, 13, 'He doesn''t have a job.', 'เขาไม่มีงานทำครับ', 'Khăo mâi mii ngaan tum khráp', 'he - not - have - work - do - polite particle', '', 'm13_4'),
(371, 13, 'I''m not American.', 'ผมไม่ได้เป็นคนอเมริกันครับ', 'Phŏhm mâi-dâi bpen khon À-meh-ríi-gan khráp', 'I - not - am - person - American - polite particle', 'The verb ''bpen'' is negated with ''mâi dâi''. Sometimes ''mâi châi'' is used instead of ''mâi dâi bpen''.', 'm13_5'),
(372, 13, 'She is not my friend.', 'ผู้หญิงคนนั้นไม่ใช่เพื่อนผมครับ', 'Phûu-yĭng khon nán mâi-châi phêuuan phŏhm khráp', 'woman - person classifier - that - not  - friend - I -  polite particle', '', 'm13_6'),
(373, 13, 'That''s wrong.', 'ไม่ถูกครับ / ไม่ใช่ครับ', 'Mâi thùuk khráp', 'not - correct - polite particle', '', 'm13_7'),
(374, 13, 'It''s not easy.', 'ไม่ง่ายครับ', 'Mâi ngâai khráp', 'not - easy - polite particle', '', 'm13_8'),
(375, 13, 'It''s not enough.', 'ไม่พอครับ', 'Mâi phaaw khráp', 'not - enough - polite particle', '', 'm13_9'),
(376, 13, 'The house isn''t very big.', 'บ้านไม่ค่อยใหญ่เท่าไหร่ครับ', 'Bâan mâi khâawy yài thâo-rai khráp', 'house - not - very much - big - very much - polite particle', '', 'm13_10'),
(377, 13, 'I don''t look after him', 'ผมไม่ดูแลเขาครับ', 'Phŏhm mâi doo-lae khăo khráp', 'I - not - look after - him - polite particle', 'In the case of multiple verbs, usually the first verb is negated.', 'm13_11'),
(378, 13, 'I''m not making any comparisons.', 'ผมไม่เปรียบเทียบครับ', 'Phŏhm mâi brìiap thîiap khráp', 'I - not - compare - compare - polite particle', '', 'm13_12'),
(379, 13, 'I can''t find it.', 'ผมหาไม่เจอครับ', 'Phŏhm hăa mâi juuhr khráp', 'I - look for - not - find - polite particle', 'Where the second verb occurs as a result of the first, the second verb is negated.', 'm13_13'),
(380, 13, 'They haven''t arrived.', 'พวกเขายังมาไม่ถึงครับ', 'Phûak khăo yang maa mâi thĕung khráp', 'group of - him - still - come - not - arrive - polite particle', '', 'm13_14'),
(381, 13, 'We don''t have enough time.', 'เรามีเวลาไม่พอครับ', 'Rao mii wae-laah mâi phaaw khráp', 'we - have - time - not - enough - polite particle', '', 'm13_15'),
(382, 13, 'Nok didn''t watch the movie.', 'นกไม่ได้ดูหนังครับ', 'Nók mâi dâi doo năng khráp', 'Nok - not - did - see - film - polite particle', 'For most verbs, to form a past negative ''mâi dâi'' is placed before the verb.', 'm13_16'),
(383, 13, 'We didn''t buy the car.', 'เราไม่ได้ซื้อรถครับ', 'Rao mâi dâi séu rot khráp', 'we - not - did - buy - car - polite particle', '', 'm13_17'),
(384, 13, 'You don''t have to go.', 'ไม่ต้องไปก็ได้ครับ', 'Mâi dtôrng bpai gôr-dâi khráp', 'not - have to - go - ok - polite particle', '', 'm13_18'),
(385, 13, 'You must not go.', 'ห้ามไปครับ', 'Hâam bpai khráp', 'prohibited - go - polite particle', '', 'm13_19'),
(386, 13, 'You haven''t finished.', 'คุณยังทำไม่เสร็จนะครับ', 'Khun yang tham mâi sèt ná khráp', 'you - still - do - not - finish - softening particle - polite particle', '', 'm13_20'),
(387, 13, 'I haven''t eaten yet.', 'ผมยังไม่ได้ทานข้าวครับ', 'Phŏhm yang mâi dâi thaan khâao khráp', 'I - still - not - did - eat - rice - polite particle', '', 'm13_21'),
(388, 13, 'I haven''t got my visa yet.', 'ผมยังไม่ได้รับวีซ่าเลยครับ', 'Phŏhm yang mâi dâi ráp wii-sâa leeuy khráp', 'I - still - not - did - get - visa - at all - polite particle', '', 'm13_22'),
(389, 13, 'Bua has never seen snow.', 'บัวยังไม่เคยเห็นหิมะมาก่อนเลยครับ', 'Buaa yang mâi ker-ee hĕn hì-má maa-gòrn leeuy khráp', 'Buaa - still - not - ever - see - snow - before - at all - polite particle', 'The word ''ker-ee'' has two uses. It can be used to talk about whether something has ever happened or not, and to talk about habitual actions in the past.', 'm13_23'),
(390, 13, 'Don''t touch it!', 'ห้ามจับ!', 'Hâam jàp!', 'prohibited - touch', '', 'm13_24'),
(391, 13, 'It''s impossible!', 'เป็นไปไม่ได้!', 'Bpen bpai mâi dâi!', 'to be able - go - not - can', '', 'm13_25'),
(392, 15, 'We''re going on holiday at the end of the year.', 'เราจะไปเที่ยวสิ้นปีนี้ครับ', 'Rao jà bpai thîaao sîn bpii níi khráp', 'we - future marker - go - trip - end - year - this - polite particle', 'The word ''jà'' implies a future action.', 'm15_1'),
(393, 15, 'When are you going to get a haircut?', 'คุณจะไปตัดผมเมื่อไหร่ครับ', 'Khun jà bpai dtàt phŏhm mêuua-rai khráp?', 'you - future marker - go - cut - hair - when - polite particle?', '', 'm15_2'),
(394, 15, 'Ning''s not coming to school tomorrow.', 'หนิงจะไม่มาโรงเรียนพรุ่งนี้ครับ', 'Nĭng jà mâi maa rohng-riian phrûng-níi khráp', 'Ning - future marker - not - come - school - tomorrow - polite particle', '', 'm15_3'),
(395, 15, 'I''ll go to the market on the way home tomorrow.', 'ผมจะไปตลาดพรุ่งนี้ก่อนกลับบ้านครับ', 'Phŏhm jà bpai dtà-làat phrûng-níi gòrn glàp bâan khráp', 'I - future marker - go - market - tomorrow - before - return - home - polite particle', '', 'm15_4'),
(396, 15, 'Mother is about to prepare food.', 'แม่กำลังจะทำอาหาร', 'Mâe gamlang-jà tham aa-hăan', 'mother - about to - make - food', 'The construction ''gamlang-jà'' is used to indicate that something is just about to happen.', 'm15_5'),
(397, 15, 'He''s just leaving/He''s already left.', 'เขาไปแล้วครับ', 'Khăo bpai láew khráp', 'he - go - past action marker - polite particle', 'The word ''láew'' indicates a past action, or something that is just happening.', 'm15_6'),
(398, 15, 'The restaurant''s shut.', 'ร้านอาหารปิดเเล้วครับ', 'Raan aa-hăan bpìt láew khráp.', 'shop - food - close - past action marker - polite particle', '', 'm15_7'),
(399, 15, 'Chompoo was not well this morning.', 'เมื่อเช้านี้ชมพูไม่สบายครับ', 'Mêuua cháao níi Chohm-phuu mâi sà-baai khráp', 'point in time - morning - this - Chompoo - not - well - polite particle', 'A past action may be implied by the context, such as when using a time or date.', 'm15_8'),
(400, 15, 'I went to Phuket last month.', 'ผมไป เกาะภูเก็ต เมื่อเดือนที่แล้วครับ', 'Phŏhm bpai gàw phuu-gèt mêuua deuan thîi-láew khráp', 'I - go - island - Phuket - point in time - month - last - polite particle', '', 'm15_9'),
(401, 15, 'I didn''t buy it.', 'ผมไม่ได้ซื้อครับ', 'Phŏhm mâi dâi séu khráp', 'I - not - did - buy - polite particle', 'Placing ''mâi dâi'' before a verb indicates a past action that did not happen.', 'm15_10'),
(402, 15, 'He didn''t tell me.', 'เขาไม่ได้บอกผมนะครับ', 'Khăo mâi dâi bòrk phŏhm ná khráp', 'he - not - did - tell - me - softening particle - polite particle', '', 'm15_11'),
(403, 15, 'It''s used up.', 'หมดแล้วครับ', 'Mòht láew khráp', 'used up - already - polite particle', '', 'm15_12'),
(404, 15, 'They left a moment ago.', 'พวกเขาไปเมื่อสักครู่นี้เองครับ', 'Phûak-khăo bpai mêuua-sàk-khrûu níi aehng khráp', 'they - go - a moment ago - this - only - polite particle', '', 'm15_13'),
(405, 15, 'Have you finished your homework yet? Yes.', 'การบ้านเสร็จหรือยังครับ เสร็จแล้วครับ', 'Gaan bâan sèt (láew) rĕuu yang khráp? Sèt láew khráp', 'task - home - finish - (already) - or - not yet - polite particle? finish - already - polite particle', '', 'm15_14'),
(406, 15, 'Has father come home yet? Not yet.', 'พ่อกลับมาบ้านหรือยังครับ ยังครับ', 'Phâaw glàp maa bâan rĕuu yang khráp? Yang khráp', 'father - return - come - home - or - not yet - polite particle? not yet - polite particle', '', 'm15_15'),
(407, 15, 'Have you been to the doctor already? Yes.', 'ไปหาหมอมาหรือยังครับ ไปมาแล้วครับ', 'Bpai hăa mŏr maa rĕuu yang khráp? Bpai maa láew khráp', 'go - visit - doctor - come back - or - not yet - polite particle? go - come back - already - polite particle', 'Using ''bpai'' and ''maa'' together in a sentence can imply a trip which has finished.', 'm15_16'),
(408, 15, 'Have you eaten yet? Yes.', 'ทานข้าวหรือยังครับ ทานแล้วครับ', 'Thaan khâao yang khráp? Than láew khráp', 'eat - rice - (or) not yet - polite particle? eat - already - polite particle', '', 'm15_17'),
(409, 15, 'It''s still raining.', 'ฝนยังตกอยู่เลยครับ', 'Fŏhn yang dtòk yùu leuuy khráp', 'rain - still - fall - currently - exclamation - polite particle', '', 'm15_18'),
(410, 15, 'He''s still here.', 'เขายังอยู่ที่นี่ครับ', 'Khăo yang yùu thîi-nîi khráp', 'he - still - situated - here - polite particle', '', 'm15_19'),
(411, 15, 'Waan is in a meeting now.', 'หวานกำลังประชุมอยู่ครับ', 'Wăan gamlang bprà-choom yùu khráp', 'Waan - currently - meeting - currently - polite particle', 'The construction ''gamlang .... yùu'' is used to talk about something that is currently happening or was happening. Either ''gamlang'' or yùu'' may be dropped.', 'm15_20'),
(412, 15, 'Older sister is watching TV.', 'พี่สาวกำลังดูทีวีอยู่ครับ', 'Phîi săo gamlang doo tee-wee yùu khráp', 'older sibling - girl - currently - watch - tv - currently - polite particle', '', 'm15_21'),
(413, 15, 'The dog is sleeping.', 'หมากำลังนอนอยู่ครับ', 'Măa gamlang norn yùu khráp', 'dog - currently - sleep - currently - polite particle', '', 'm15_22'),
(414, 15, 'He is waiting for the bus.', 'เขากำลังรอรถเมล์อยู่ครับ', 'Khăo gamlang raaw rót-maeh yùu khráp', 'he - currently - wait - bus - currently - polite particle', '', 'm15_23'),
(415, 15, 'We just returned from Japan.', 'เราเพิ่งกลับมาจากญี่ปุ่นมาครับ', 'Rao phêerng glàp maa jàak Yîi-bpun maa khráp', 'we - just - return - come - from - Japan - come - polite particle', 'The word ''phêerng'' can be used to indicate that something just happened.', 'm15_24'),
(416, 15, 'I only just found out.', 'ผมเพิ่งรู้ครับ', 'Phŏhm phêerng róo khráp', 'I - recently - know - polite particle', '', 'm15_25'),
(417, 15, 'We used to go to the temple every week.', 'เราเคยไปวัดทุกอาทิตย์ครับ', 'Rao ker-ee bpai wát thúk aa-thít khráp', 'we - used to - go - temple - every - week - polite particle', 'The word ''ker-ee'' has two uses. It can be used to talk about whether something has ever happened or not, and to talk about habitual actions in the past.', 'm15_26'),
(418, 15, 'I''ve already seen it. (the movie)', 'ผมเคยดูแล้วครับ', 'Phŏhm ker-ee doo láew khráp', 'I - already - watch - past action marker - polite particle', '', 'm15_27'),
(419, 15, 'Have you ever been to the Temple of the Emerald Buddha? Yes.', 'เคยไปวัดพระแก้วหรือยังครับ เคยแล้วครับ', 'Ker-ee bpai Wát Pra-Gâew rĕuu yang khráp? Ker-ee láew khráp', 'ever - go - temple - emerald buddha - or - not yet? already - past action marker - polite particle', '', 'm15_28'),
(420, 15, 'I went there when I was a child', 'ผมเคยไปตอนเด็กๆครับ', 'Phŏhm ker-ee bpai dtàawn dèk-dèk khráp', 'I - have already - go - at time period - children - polite particle', '', 'm15_29'),
(421, 15, 'I have been playing soccer since I was five.', 'ผมเล่นฟุตบอลตั้งแต่อายุห้าขวบครับ', 'Phŏhm lên fút-baawn dtâng-dtàae aa-yúu hâa khùaap khráp', 'I - play - football - since - age - five - classifier for years of age - polite particle', '', 'm15_30'),
(422, 15, 'We stayed there for two months.', 'เราอยู่ที่นั่นมาสองเดือนแล้วครับ', 'Rao yùu thîi nán maa săawng deuan láew khráp', 'we - stay - at place - that - come - two - month - past action marker - polite particle ', '', 'm15_31'),
(423, 16, 'How much is this?', 'นี่ราคาเท่าไหร่ครับ', 'Nîi raa-khaa thâo rai khráp?', 'this - price - equal to - what - polite particle?', '', 'm16_1'),
(424, 16, 'How many baht?', 'กี่บาทครับ', 'Gìi bàht khráp?', 'how many - baht - polite particle?', '', 'm16_2'),
(425, 16, 'How much per piece?', 'ชิ้นละเท่าไหร่ครับ', 'Chín lá thâo rai khráp?', 'piece - each - equal to - what - polite particle?', '', 'm16_3'),
(426, 16, 'How much per kilo?', 'โลละเท่าไหร่ครับ', 'Loh lá thâo rai khráp?', 'kilo - each - equal to - what - polite particle?', 'Thai uses many words from English with a Thai pronunciation. The English word ''kilo'' becomes ''gì-loh'' or just ''loh''.', 'm16_4'),
(427, 16, 'How much per metre?', 'เมตรละเท่าไหร่ครับ', 'Mét lá thâo rai khráp?', 'metre - each - equal to - what - polite particle?', '', 'm16_5'),
(428, 16, 'How much per day?', 'วันละเท่าไหร่ครับ', 'Wan lá thâo rai khráp?', 'day - each - equal to - what - polite particle?', '', 'm16_6'),
(429, 16, 'What do you want to buy?', 'คุณจะซื้ออะไรครับ', 'Khun jà séu à-rai khráp?', 'you - want to - buy - what - polite particle?', 'The future marker ''jà'' in this case means ''want to''.', 'm16_7'),
(430, 16, 'I want to buy a T-shirt.', 'ผมจะซื้อเสื้อยืด', 'Phŏhm jà séu sêuua-yêuut', 'I - want to -  buy - T-shirt', '', 'm16_8'),
(431, 16, 'Very expensive.', 'แพงมากเลยครับ', 'Phaaeng mâhk leeuy khráp', 'expensive - very - exclamation - polite particle', '', 'm16_9'),
(432, 16, 'Cheap.', 'ถูก', 'Thùuk.', '', '', 'm16_10'),
(433, 16, 'Can you reduce the price a bit? No!', 'ลดหน่อยได้ไหมครับ ไม่ได้!', 'Lóht nòy dâi mái khráp? Mâi dâi!', 'reduce - a little - can - or not - polite particle? not - can!', '', 'm16_11'),
(434, 16, 'Do you have anything cheaper?', 'คุณมีอะไรถูกกว่านี้ไหมครับ', 'Khun mii à-rai thùuk gwàa níi mái khráp?', 'you - have - anything - cheap - more than - this - or not - polite particle? ', '', 'm16_12'),
(435, 16, 'Do you have any more of these?', 'คุณมีแบบนี้อีกไหมครับ', 'Khun mii bàaep níi èek mái khráp?', 'you - have - kind - this - more - or not - polite particle?', '', 'm16_13'),
(436, 16, 'Do you have sim cards?', 'คุณมีซิมโทรศัพท์ไหมครับ', 'Khun mii sim thoh-rá-sàp mái khráp?', 'you - have - sim - phone - or not - polite particle?', '', 'm16_14'),
(437, 16, 'I''ll come back tomorrow.', 'ผมจะกลับมาพรุ่งนี้ครับ', 'Phŏhm jà glàp maa phrûng-níi khráp', 'I - future marker - return - come - tomorrow - polite particle', '', 'm16_15'),
(438, 16, 'Do you take credit card?', 'คุณรับบัตรเครดิตไหมครับ', 'Khun ráp bàt khraeh-dìt mái khráp?', 'you - accept - card - credit - or not - polite particle?', '', 'm16_16'),
(439, 16, 'I''ll take this one.', 'ผมเอาอันนี้ครับ', 'Phŏhm ao an níi khráp', 'I - take - piece - this - polite particle', '', 'm16_17'),
(440, 16, 'I don''t like that one.', 'ผมไม่ชอบอันนั้นเลยครับ', 'Phŏhm mâi chôrp an nán leeuy khráp', 'I - not - like - item - that - at all - polite particle', '', 'm16_18'),
(441, 16, 'I''ll take half a kilo.', 'ผมเอาครึ่งกิโลครับ', 'Phŏhm ao khrêung gì-loh khráp', 'I - take - half - kilo - polite particle', '', 'm16_19'),
(442, 16, 'Two kilos of mandarins.', 'ส้มสองกิโล', 'Sôhm săawng gì-loh', 'orange - two - kilo', 'Thais tend to use the word ''sôhm'' for both oranges and mandarins.', 'm16_20'),
(443, 16, 'A metre of silk.', 'ผ้าไหมหนึ่งเมตร', 'Phâa-măi nèung mét', 'silk fabric - one - metre', '', 'm16_21'),
(444, 16, 'Classifier for items of clothing.', 'ตัว', 'Dtua', '', 'Thai has many classifiers or ''counting words'' which have no equivalent in English. When talking about a number of items we can use the construction ''item name + number + classifier''.', 'm16_22'),
(445, 16, 'Classifier for shoes and socks.', 'คู่', 'Khôu', '', '', 'm16_23'),
(446, 16, 'Classifier for books.', 'เล่ม', 'Lêm', '', '', 'm16_24'),
(447, 16, 'Classifier for pens.', 'ด้าม', 'Dâam', '', '', 'm16_25'),
(448, 16, 'Classifier for bottles', 'ขวด', 'Khùat', '', '', 'm16_26'),
(449, 16, 'Four pens', 'ปากกาสี่ด้าม', 'Bpàak-gaa sìi dâam', 'pen - four - classifier', '', 'm16_27'),
(450, 16, 'Two T-shirts.', 'เสื้อทีเชิร์ตสองตัว', 'Sêuua thii-chúrt săawng dtua', 'shirt - T-shirt - two - classifier', '', 'm16_28'),
(451, 16, 'Two books', 'หนังสือสองเล่ม', 'Năng-sĕu săawng lêm', 'book - two - classifier', '', 'm16_29'),
(452, 16, 'Can I have a receipt?', 'ผมขอใบเสร็จด้วยนะครับ', 'Phŏhm kŏr bai-sèt dûay ná khráp', 'I - request - receipt - particle following a request - softening particle - polite particle', '', 'm16_30'),
(453, 16, 'I don''t want a bag.', 'ไม่เอาถุงครับ', 'Mâi ao thŏong khráp', 'not - take - bag - polite particle', 'This statement is very useful in Thailand since even single items and drinks will often be put in plastic bags by default.', 'm16_31'),
(454, 16, 'Do I pay now?', 'ให้ผมจ่ายเงินเลยไหมครับ', 'Hâi phŏhm jàai ngern leeuy mái khráp?', 'give - I - pay - money - at once - or not - polite particle?', '', 'm16_32'),
(455, 16, 'Where do I pay?', 'จ่ายเงินที่ไหนครับ', 'Jàai ngern thîi năi khráp?', 'pay - money - at (place) - which - polite particle?', '', 'm16_33'),
(456, 16, 'I paid already.', 'ผมจ่ายเงินแล้วครับ', 'Phŏhm jàai ngern láew khráp', 'I - pay - money - already - polite particle', '', 'm16_34'),
(457, 16, 'Are you still open?', 'ยังเปิดอยู่ไหมครับ', 'Yang bpèrt yùu mái khráp? ', 'still - open - currently - or not - polite particle?', '', 'm16_35'),
(458, 16, 'What time do you close?', 'คุณปิดกี่โมงครับ', 'Khun bpìt gìi mohng khráp?', 'you - close - how many - hour - polite particle?', '', 'm16_36'),
(459, 16, 'Where can I change money?', 'ผมแลกเงินได้ที่ไหนครับ', 'Phŏhm lâaek ngern dâi thîi năi khráp?', 'I - exchange - money - can - at (place) - which - polite particle?', '', 'm16_37'),
(460, 16, 'Do you change Vietnamese dong?', 'คุณรับแลกเงินเวียดนามไหมครับ', 'Khun ráp lâaek ngern Wîiat-naam mái khráp?', 'you - accept - exchange - money - Vietnam - or not - polite particle?', '', 'm16_38'),
(461, 17, 'Retail shop', 'ร้านค้า', 'Ráan kháa', 'shop - trade', '', 'm17_1'),
(462, 17, 'Bookstore', 'ร้านหนังสือ', 'Ráan năng-sĕu', 'shop - book', '', 'm17_2'),
(463, 17, 'Restaurant', 'ร้านอาหาร', 'Ráan a-hăan', 'shop - food', '', 'm17_3'),
(464, 17, 'Department store', 'ห้างสรรพสินค้า', 'Hâang sàp-phá-sĭn-kháa', '', '', 'm17_4'),
(465, 17, 'Market', 'ตลาด', 'Dtà-làat', '', '', 'm17_5'),
(466, 17, 'Night market', 'ตลาดโต้รุ่ง', 'Dtà-làat dtôh-rôong', 'market - until dawn', 'Not all night markets will go all night, but this phrase is still used.', 'm17_6'),
(467, 17, 'Supermarket', 'ซุปเปอร์มาร์เก็ต', 'Sóop-bpuuhr-maa-get', '', '', 'm17_7'),
(468, 17, 'Shopping mall', 'ห้างสรรพสินค้า', 'Hâang sàp-phá-sĭn-kháa', '', '', 'm17_8'),
(469, 17, 'Bank', 'ธนาคาร', 'Thá-naa-kaan', '', '', 'm17_9'),
(470, 17, 'Post office', 'ไปรษณีย์', 'Bprai-sà-nii', '', '', 'm17_10'),
(471, 17, 'Pharmacy', 'ร้านขายยา', 'Ráan khăai yaa', 'shop - sell - medicine', '', 'm17_11'),
(472, 17, 'Soap', 'สบู่', 'Sà-bùu', '', '', 'm17_12'),
(473, 17, 'Laundry detergent / powder', 'น้ำยาซักผ้า / ผงซักฟอก', 'Nám yaa sák phâa / Phŏhng sák fâawk ', 'water - medicine - wash - clothes / powder - wash - purify', '', 'm17_13'),
(474, 17, 'Toothbrush', 'แปรงสีฟัน', 'Bpraaeng sĕe fan', 'brush - rub against - teeth', '', 'm17_14'),
(475, 17, 'Toothpaste', 'ยาสีฟัน', 'Yaa sĕe fan', 'medicine - rub against - teeth', '', 'm17_15'),
(476, 17, 'Shampoo', 'แชมพู', 'Chaem-phuu', '', '', 'm17_16'),
(477, 17, 'Mosquito repellent', 'ยากันยุง', 'Yaa gan yoong', 'medicine - prevent - mosquito', '', 'm17_17'),
(478, 17, 'Paper', 'กระดาษ', 'Gra-dàat', '', '', 'm17_18'),
(479, 17, 'Envelope, package', 'ซอง', 'Saawng', '', '', 'm17_19'),
(480, 17, 'Postage stamp', 'ไปรษณียากร', 'Bprai-sà-nii-yaa-gaawn', '', '', 'm17_20'),
(481, 17, 'Sunblock', 'ครีมกันแดด', 'Khreem gan dàaet', 'cream - protect against - sunshine', '', 'm17_21'),
(482, 17, 'Toilet paper', 'ทิชชู่', 'Thít-chûu', '', '', 'm17_22'),
(483, 17, 'Batteries', 'แบตเตอรี่ / ถ่าน', 'Bàaet-dtuuhr-rêe / thàan', '', '', 'm17_23'),
(484, 17, 'Band aids', 'พลาสเตอร์', 'Phlaas-dtûuhr', '', '', 'm17_24'),
(485, 17, 'Mobile phone', 'โทรศัพท์มือถือ', 'Thoh-rá-sàp meuu thĕuu', 'phone - hand - hold', '', 'm17_25'),
(486, 17, 'Laptop', 'แลปทอป / โน้ตบุ๊ก', 'Láaep-thaawp / Nóat-bóok', '', '', 'm17_26'),
(487, 17, 'Camera', 'กล้องถ่ายรูป', 'Glâawng thàai rûup', 'optical viewing device - take photo - image', '', 'm17_27'),
(488, 19, 'Cloth, fabric', 'ผ้า', 'Phâa', '', '', 'm19_1'),
(489, 19, 'Silk', 'ผ้าไหม', 'Phâa măi', 'material - silk', '', 'm19_2'),
(490, 19, 'Cotton', 'ผ้าฝ้าย', 'Phâa fâai', 'material - raw cotton', '', 'm19_3'),
(491, 19, 'Wood', 'ไม้', 'Máai', '', '', 'm19_4'),
(492, 19, 'Teak', 'ไม้สัก', 'Máai-sàk', '', '', 'm19_5'),
(493, 19, 'Precious stone', 'มณี', 'Má-nee', '', '', 'm19_6'),
(494, 19, 'Gold-leaf', 'แผ่นทอง', 'Phàen thaawng', 'sheet - gold', '', 'm19_7'),
(495, 19, 'Leather', 'หนัง', 'Năng', '', '', 'm19_8'),
(496, 19, 'Clothing', 'เสื้อผ้า', 'Sêuua phâa', 'shirt, blouse, jacket - cloth, clothing', '', 'm19_9'),
(497, 19, 'T-shirt', 'เสื้อยืด', 'Sêuua yêuut', 'shirt - elastic', '', 'm19_10'),
(498, 19, 'Shirt, blouse', 'เสื้อ', 'Sêuua', '', '', 'm19_11'),
(499, 19, 'Skirt, dress', 'กระโปรง', 'Grà-bprohng', '', '', 'm19_12'),
(500, 19, 'Trousers', 'กางเกง', 'Gaang-gaeng', '', '', 'm19_13'),
(501, 19, 'Shorts', 'กางเกงขาสั้น', 'Gaang-gaeng khăa sân', 'trousers - leg - short', '', 'm19_14'),
(502, 19, 'Sweater', 'เสื้อกันหนาว', 'Sêuua gan năao', 'upper garment - prevent - cold', '', 'm19_15'),
(503, 19, 'Socks', 'ถุงเท้า', 'Thŏong tháao', 'bag - foot', '', 'm19_16'),
(504, 19, 'Hat', 'หมวก ', 'Mùaak', '', '', 'm19_17'),
(505, 19, 'Jacket', 'เสื้อแจ็กเก็ต', 'Sêuua jàek-gêt', 'upper garment - jacket', '', 'm19_18'),
(506, 19, 'Shoes, footwear', 'รองเท้า', 'Raawng tháao', 'support - foot', '', 'm19_19'),
(507, 19, 'Sandals', 'รองเท้าแตะ', 'Raawng tháao dtàe', 'support - foot - touch, feel', '', 'm19_20'),
(508, 19, 'Tailor', 'ช่างตัดเสื้อ', 'Châng dtàt sêuua', 'artisan - cut - garment', '', 'm19_21'),
(509, 19, 'What size?', 'ขนาดไหน / ไซส์ไหนครับ', 'Kha-nàat năi? / Sai năi khráp?', 'size - which? / size - which - polite particle?', '', 'm19_22'),
(510, 19, 'Can I try it on?', 'ผมขอลองได้ไหมครับ', 'Phŏhm kŏr laawng dâi mái khráp?', ' I - request - try - can - or not - polite particle?', '', 'm19_23'),
(511, 19, 'It''s too big.', 'ใหญ่ไปครับ', 'Yài bpai khráp', 'big - go - polite particle', '', 'm19_24'),
(512, 19, 'It''s too small.', 'เล็กไปครับ', 'Lék bpai khráp', 'small - go - polite particle', '', 'm19_25'),
(513, 19, 'It''s too long.', 'ยาวไปครับ', 'Yaao bpai khráp', 'long - go - polite particle', '', 'm19_26'),
(514, 19, 'It''s too short.', 'สั้นไปครับ', 'Sún bpai khráp', 'short - go - polite particle', '', 'm19_27'),
(515, 19, 'Do you have anything bigger?', 'คุณมีไซส์ใหญ่กว่านี้ไหมครับ', 'Khun mii sai yài gwàa níi mái khráp?', 'you - have - size - big - more than - this - or not - polite particle?', '', 'm19_28'),
(516, 19, 'Do you have any other colours?', 'คุณมีสีอื่นไหมครับ', 'Khun mii sĭi èuun mái khráp?', 'you - have - colour - other - or not - polite particle?', '', 'm19_29'),
(517, 19, 'Will the colour fade/run?', 'สีจะตกไหมครับ', 'Sĭi jà dtòk mái khráp?', 'colour - future marker - run/fade - or not - polite particle?', '', 'm19_30'),
(518, 22, 'Fruit', 'ผลไม้', 'Phŏn-lá-mái', '', '', 'm22_1'),
(519, 22, 'Apple', 'แอปเปิ้ล', 'Aàep-bpûn', '', '', 'm22_2'),
(520, 22, 'Banana', 'กล้วย', 'Glûay', '', '', 'm22_3'),
(521, 22, 'Orange', 'ส้ม', 'Sôhm', '', '', 'm22_4'),
(522, 22, 'Mandarin', 'ส้มจีน', 'Sôhm-jiin', 'orange - China', '', 'm22_5'),
(523, 22, 'Tamarind', 'มะขาม', 'Má-khăam', '', '', 'm22_6'),
(524, 22, 'Musk melon', 'แตงไทย', 'Dtaaeng thai', '', '', 'm22_7'),
(525, 22, 'Pomelo', 'ส้มโอ', 'Sôhm oh', '', '', 'm22_8'),
(526, 22, 'Mango', 'มะม่วง', 'Má-mûaang', '', '', 'm22_9'),
(527, 22, 'Papaya', 'มะละกอ', 'Má-lá-gaaw', '', '', 'm22_10'),
(528, 22, 'Guava', 'ฝรั่ง', 'Fà-ràng', '', '', 'm22_11'),
(529, 22, 'Coconut', 'มะพร้าว', 'Má-phráao', '', '', 'm22_12'),
(530, 22, 'Pineapple', 'สับปะรด', 'Sàp-bpà-róht', '', '', 'm22_13'),
(531, 22, 'Durian', 'ทุเรียน', 'Thú-rian', '', '', 'm22_14'),
(532, 22, 'Jackfruit', 'ขนุน', 'Khà-nŏon', '', '', 'm22_15'),
(533, 22, 'Lime', 'มะนาว', 'Má-naao', '', '', 'm22_16'),
(534, 22, 'Vegetables', 'ผัก', 'Phàk', '', '', 'm22_17'),
(535, 22, 'Pumpkin', 'ฟักทอง', 'Fák-thaawng', '', '', 'm22_18'),
(536, 22, 'Mushroom', 'เห็ด', 'Hèt', '', '', 'm22_19'),
(537, 22, 'Chili', 'พริก', 'Phrík', '', '', 'm22_20'),
(538, 22, 'Red pepper', 'พริกแดง', 'Phrík daaeng', 'pepper - red', '', 'm22_21'),
(539, 22, 'Corn', 'ข้าวโพด', 'Khâao-phôht', '', '', 'm22_22'),
(540, 22, 'Pak-choy', 'ผักกวางตุ้ง', 'Phàk-gwaang-dtôong', '', '', 'm22_23'),
(541, 22, 'Holy basil', 'กระเพรา', 'Grà-phrao', '', 'Often shortened to ''gà-phrao''.', 'm22_24'),
(542, 22, 'Sweet basil / Thai basil', 'โหระพา', 'Hŏhr-rá-phaa', '', '', 'm22_25'),
(543, 22, 'Lemon basil', 'แมงลัก', 'Maaeng-lák', '', '', 'm22_26'),
(544, 22, 'Mint', 'สะระแหน่', 'Sà-rá-nàae', '', '', 'm22_27'),
(545, 22, 'Purple eggplant', 'มะเขือม่วง', 'Má-khĕuua mûaang', 'eggplant - purple', '', 'm22_28'),
(546, 22, 'Long eggplant', 'มะเขือยาว', 'Má-khĕuua yaao', 'eggplant - long', '', 'm22_29'),
(547, 22, 'Sweet potato', 'มันเทศ', 'Man thâet', 'potato - foreign', '', 'm22_30'),
(548, 22, 'Garlic', 'กระเทียม', 'Grà-thiiam', '', '', 'm22_31'),
(549, 22, 'Ginger', 'ขิง', 'Khĭing', '', '', 'm22_32'),
(550, 22, 'Lemongrass', 'ตะไคร้', 'Dtà-khrái', '', '', 'm22_33'),
(551, 23, 'Fish', 'ปลา', 'Bplaa', '', '', 'm23_1'),
(552, 23, 'Beef', 'เนื้อ', 'Neúua', '', '', 'm23_2'),
(553, 23, 'Chicken', 'ไก่', 'Gài', '', '', 'm23_3'),
(554, 23, 'Pork', 'หมู', 'Mŭu', '', '', 'm23_4'),
(555, 23, 'Mutton', 'แกะ', 'Gàe', '', '', 'm23_5'),
(556, 23, 'Shrimp/prawn', 'กุ้ง', 'Gôong', '', '', 'm23_6'),
(557, 23, 'Rice', 'ข้าว', 'Khâao', '', '', 'm23_7'),
(558, 23, 'Sticky rice', 'ข้าวเหนียว', 'Khâao niăao', 'rice - sticky', '', 'm23_8'),
(559, 23, 'Nuts/beans', 'ถั่ว', 'Thùaa', '', '', 'm23_9'),
(560, 23, 'Egg', 'ไข่', 'Khài', '', '', 'm23_10'),
(561, 23, 'Peanut', 'ถั่วลิสง', 'Thùaa-lí-sŏhng', '', '', 'm23_11'),
(562, 23, 'Tofu', 'เต้าหู้', 'Dtâo-hûu', '', '', 'm23_12'),
(563, 23, 'Coconut milk', 'กะทิ', 'Gà-thí', '', '', 'm23_13'),
(564, 23, 'Stir fry', 'ผัด', 'Phàt', '', '', 'm23_14'),
(565, 23, 'Boiled', 'ต้ม', 'Dtôhm', '', '', 'm23_15'),
(566, 23, 'Deep fried', 'ทอด', 'Thâawt', '', '', 'm23_16'),
(567, 23, 'Steamed', 'นึ่ง', 'Nêung', '', '', 'm23_17'),
(568, 23, 'Fish sauce', 'น้ำปลา', 'Náam bplaa', 'liquid - fish', '', 'm23_19'),
(569, 23, 'Shrimp paste', 'กะปิ', 'Gà-bpì', '', '', 'm23_20'),
(570, 23, 'A mix of lemongrass, chilli, galangal and Kaffir lime', 'ต้มยำ', 'Dtôhm yum', 'boil - mix', '', 'm23_18'),
(571, 23, 'Tom yum soup with prawn or shrimp', 'ต้มยำกุ้ง', 'Dtôhm yum gôong', 'boil - mix - shrimp / prawn', '', 'm23_37'),
(572, 23, 'Soup with chicken, coconut milk and galangal', 'ต้มข่าไก่', 'Dtôhm khàa gài', 'boil - galangal - chicken', '', 'm23_38'),
(573, 23, 'Green papaya salad', 'ส้มตำ', 'Sôhm-dtam', 'sour - pound with pestle', '', 'm23_21'),
(574, 23, 'Fried rice', 'ข้าวผัด', 'Khâao phàt', 'rice - fry', '', 'm23_22'),
(575, 23, 'Fried egg', 'ไข่ดาว', 'Khài daao', 'egg - star', '', 'm23_23'),
(576, 23, 'Steamed fish', 'ปลานึ่ง', 'Bplaa nêung', 'fish - steam', '', 'm23_24'),
(577, 23, 'Curry', 'แกง', 'Gaeng', '', '', 'm23_25'),
(578, 23, 'Green curry', 'แกงเขียวหวาน', 'Gaeng khĭaao wăan', 'curry - green - sweet', '', 'm23_26'),
(579, 23, 'Red curry', 'แกงเผ็ด', 'Gaeng phèt', 'curry - spicy hot', '', 'm23_27'),
(580, 23, 'Fish entrail soup', 'แกงไตปลา', 'Gaeng dtai bplaa', 'curry - kidney - fish', '', 'm23_35'),
(581, 23, 'Sour soup', 'แกงส้ม', 'Gaeng sôhm', 'curry - sour', 'Made with tamarind.', 'm23_36'),
(582, 23, 'Rice noodle soup', 'ก๋วยเตี๋ยวน้ำ', 'Gŭay-dtĕow náam', 'rice noodles - liquid', '', 'm23_28'),
(583, 23, 'Rice noodles without soup', 'ก๋วยเตี๋ยวแห้ง', 'Gŭay-dtĕow hâaeng', 'rice noodles - dry', '', 'm23_29'),
(584, 23, 'Soup with wide flat rice noodles', 'ก๋วยเตี๋ยวเส้นใหญ่', 'Gŭay-dtĕow sên yài', 'rice noodles - noodles - big', '', 'm23_30'),
(585, 23, 'Soup with medium size rice noodles', 'ก๋วยเตี๋ยวเส้นเล็ก', 'Gŭay-dtĕow sên lék', 'rice noodles - noodles - small', '', 'm23_31'),
(586, 23, 'Soup with vermicelli rice noodles', 'ก๋วยเตี๋ยวเส้นหมี่', 'Gŭay-dtĕow sên mèe', 'rice noodles - noodles - vermicelli', '', 'm23_32'),
(587, 23, 'Egg noodles', 'บะหมี่', 'Bà-mèe', '', '', 'm23_33'),
(588, 23, 'Thin rice noodles served with various toppings', 'ขนมจีน', 'Khà-nŏhm jiin', 'dessert - Chinese', '', 'm23_34'),
(589, 23, 'Chicken stir-fried in red curry paste', 'ไก่ผัดพริกแกง', 'Gài phàt prík gaeng', 'chicken - fried - chilli - curry', '', 'm23_39'),
(590, 23, 'Fried wide rice noodles with pak kana and soy sauce', 'ผัดซีอิ๊ว', 'Phàt see-íu', 'stir fried - soy sauce', '', 'm23_40'),
(591, 23, 'Spicy salad made with ground meat and herbs', 'ลาบ', 'Lâap', '', '', 'm23_41'),
(592, 23, 'Basil chicken topped with fried egg', 'ผัดกระเพราไก่ไข่ดาว', 'Phàt grà-phrao gài khài daao', 'stir fried - basil - chicken - egg - star', '', 'm23_42'),
(593, 23, 'Dessert / sweet item', 'ขนมหวาน', 'Khà-nŏhm wăan', 'dessert - sweet', '', 'm23_43'),
(594, 24, 'Drinking water', 'น้ำดื่ม', 'Náam dèum', 'water - drink', '', 'm24_1'),
(595, 24, 'Glass', 'แก้ว', 'Gâeo', '', '', 'm24_2'),
(596, 24, 'Cup', 'ถ้วย', 'Thûay', '', '', 'm24_3'),
(597, 24, 'Coffee', 'กาแฟ', 'Gaa-fae', '', '', 'm24_4'),
(598, 24, 'Black coffee', 'กาแฟดำ', 'Gaa-fae dam', 'coffee - black', '', 'm24_5'),
(599, 24, 'Ancient coffee', 'กาแฟโบราณ', 'Gaa-fae boh-raan', 'coffee - ancient', 'Strong filter coffee mixed with condensed milk and ice.', 'm24_6'),
(600, 24, 'Iced coffee with condensed milk and sugar', 'กาแฟเย็น', 'Gaa-fae yen', 'coffee - cold', '', 'm24_7'),
(601, 24, 'Cappuccino', 'คาปูชิโน่', 'Kha-pu-chi-nô', '', '', 'm24_8'),
(602, 24, 'Tea', 'น้ำชา', 'Náam chaa', 'liquid - tea', '', 'm24_9'),
(603, 24, 'Green Tea', 'ชาเขียว', 'Chaa kiăao', 'tea - green', '', 'm24_10'),
(604, 24, 'Iced green tea', 'ชาเขียวเย็น', 'Chaa kiăao yen', 'tea - green - cold', '', 'm24_11'),
(605, 24, 'Milk', 'น้ำนม', 'Náam nohm', 'liquid - milk', '', 'm24_12'),
(606, 24, 'Sugarcane juice', 'น้ำอ้อย', 'Náam âawy', 'liquid - sugarcane', '', 'm24_13'),
(607, 24, 'Fruit juice', 'น้ำผลไม้', 'Náam phŏn-lá-mái', 'liquid - fruit', '', 'm24_14'),
(608, 24, 'Smoothie', 'น้ำปั่น', 'Náam bpàn', 'liquid - spin / churn', '', 'm24_15'),
(609, 24, 'Fruit smoothie', 'น้ำผลไม้ปั่น', 'Náam phŏn-lá-mái bpàn', 'liquid - fruit - spin / churn', '', 'm24_16'),
(610, 24, 'Orange smoothie', 'ส้มปั่น', 'Sôhm bpàn', 'orange - spin / churn', '', 'm24_17'),
(611, 24, 'Ice', 'น้ำแข็ง', 'Náam khăeng', 'water - hard', '', 'm24_18'),
(612, 24, 'Alcohol', 'เหล้า', 'Lâo', '', '', 'm24_19'),
(613, 24, 'Beer', 'เบียร์', 'Bia', '', '', 'm24_20'),
(614, 24, 'Elephant beer', 'เบียร์ช้าง ', 'Bia cháang', 'beer - elephant', '', 'm24_21'),
(615, 24, 'Whiskey', 'วิสกี้', 'Whís-gêe', '', '', 'm24_22'),
(616, 25, 'Can I see a menu?', 'ผมขอดูเมนูหน่อยได้ไหมครับ', 'Phŏhm kŏr duu menu nòy dâi mái khráp?', 'I - request - see - menu - softening particle - can - or not - polite particle? ', '', 'm25_1'),
(617, 25, 'Can I sit here?', 'ขอนั่งที่นี่ได้ไหมครับ', 'Kŏr nâng thîi-nîi dâi mái khráp?', 'request - sit - here - can - or not - polite particle?', '', 'm25_2'),
(618, 25, 'Not spicy thanks.', 'ไม่เผ็ด', 'Mâi phèt', 'not - spicy', '', 'm25_3'),
(619, 25, 'Can you add some egg?', 'ขอเพิ่มไข่หน่อยได้ไหมครับ', 'Kŏr phêerm khài nòy dâi mái khráp?', 'request - add - egg - softening particle - can - or not - polite particle?', '', 'm25_4'),
(620, 25, 'Can I have another bowl of rice?', 'ขอข้าวเพิ่มอีกถ้วยได้ไหมครับ', 'Kŏr khâao phêerm èek thûuay dâi mái khráp?', 'request - rice - more - another - cup - can - or not - polite particle', '', 'm25_5'),
(621, 25, 'Can we have some water please?', 'ขอน้ำหน่อยได้ไหมครับ', 'Kŏr náam nòy dâi mái khráp?', 'request - water - softening particle - can - or not - polite particle?', '', 'm25_6'),
(622, 25, 'Can we have five coffees?', 'ขอกาแฟห้าแก้วได้ไหมครับ', 'Kŏr gaa-fae hâa gâeo dâi mái khráp?', 'request - coffee - five - cup - can - or not - polite particle?', '', 'm25_7'),
(623, 25, 'Can we have two plates of fish laap and one green papaya salad.', 'ขอลาบปลา 2 จานกับส้มตำ 1 จานได้ไหมครับ', 'Kŏr lâap bplaa sŏng jaan gàp sôhm-dtam nèung jaan dâi mái khráp?', 'request - laap - fish - two - plate - with - papaya salad - one - plate - can - or not - polite particle?', '', 'm25_8'),
(624, 25, 'Without sugar.', 'ไม่ใส่น้ำตาล', 'Mâi sài náam-dtaan', 'not - put - sugar', '', 'm25_9'),
(625, 25, 'Without ice.', 'ไม่ใส่น้ำแข็ง', 'Mâi sài náam khăeng', 'not - put - water - hard', '', 'm25_10'),
(626, 25, 'That''s enough.', 'พอแล้ว', 'Phaaw láew.', 'enough - already', '', 'm25_11'),
(627, 25, 'Just a little.', 'นิดเดียว', 'Nít diaao', 'little - alone', '', 'm25_12'),
(628, 25, 'Can I have the bill please?', 'เช็คบิลด้วยครับ', 'Chek-bin dûay khráp', 'bill - particle used at the end of a request - polite particle', '', 'm25_13'),
(629, 25, 'Can we pay separately?', 'เราจะแบ่งกันจ่ายได้ไหมครับ', 'Rao jà bàeng gan jàai dâi mái khráp?', 'we - want to - divide - separate - pay - can - or not - polite particle?', '', 'm25_14'),
(630, 25, 'Takeaway', 'ใส่กล่อง', 'Sài glàawng', 'put - takeaway container', '', 'm25_15'),
(631, 25, 'Eat here', 'ทานที่นี้', 'Thaan thîi-nîi', 'eat - here', '', 'm25_16'),
(632, 25, 'What''s good here?', 'ที่นี่อะไรอร่อยครับ', 'Thîi-nîi à-rai à-ròi khráp?', 'here - what - tasty - polite particle?', '', 'm25_17'),
(633, 25, 'Do you have any vegetarian food?', 'มีอาหารเจไหมครับ', 'Mii aa-hăan jaeh mái khráp?', 'have - food - vegetarian - or not - polite particle?', 'The word ''jaeh'' means free from animal products, including eggs and milk. It is the most commonly understood word for ''vegetarian'' since many Thais eat this way during the vegetarian festival in October. Dairy products are uncommon in Thailand, but you can ask for egg to be added if you wish.', 'm25_18');