
INSERT INTO `phrasesM` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(1, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'เกา เก่า เก้า เก๊า เก๋า', 'Gao gào gâo gáo găo', 'scratch - old - nine - gout - excellent', 'The mid-tone is spoken at in the middle of your vocal range. It may fall slightly at the end. The low tone is spoken at a constant or slightly falling pitch starting lower than normal speech. The falling tone starts high and then falls to a low pitch. The high tone is spoken at the top of your vocal range, rising slightly and then falling slightly. The rising tone starts low, falls slightly and then rises to a high pitch.', 'm1_1'),
(2, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'ตู ตู่ ตู้ ตู๊ ตู๋', 'Dtuu dtùu dtûu dtúu dtŭu', 'myself - assume or feign ownership - cabinet / compartment - timbered - alternate spelling of ตู้', '', 'm1_2'),
(3, 1, 'Mid tone - low tone - falling tone - high tone - rising tone', 'อา อ่า อ้า อ๊า อ๋า', 'Aa àa âa áa ăa', 'younger sibling of father - decorate - word used as interjection - no meaning - no meaning', '', 'm1_3'),
(4, 1, 'Rising tone - low tone - falling tone', 'ขา ข่า ข้า', 'Khăa khàa khâa', 'leg - galangal - attendant', '', 'm1_4'),
(5, 1, 'Mid tone - falling tone - high tone', 'ไร ไร่ ไร้', 'Rai râi rái', 'suffix indicating a question about quantity - unit of land - devoid of', '', 'm1_5'),
(6, 1, 'Mid tone - falling tone - high tone', 'นา น่า น้า', 'Naa nâa náa', 'rice field - various meanings - younger brother or sister of mother', '', 'm1_6'),
(7, 1, 'Mid tone - falling tone - high tone', 'ไช ใช่ ใช้', 'Chai châi chái', 'pierce a hole - yes - to use', '', 'm1_7'),
(8, 1, 'He eats rice', 'เขากินข้าว', 'Khăo gin khâao', 'he - eat - rice', '', 'm1_8'),
(9, 1, 'Grandmother takes medicine', 'คุณย่ากินยา', 'Khun yâa gin yaa', 'title of respect - maternal grandmother - eat - medicine', '', 'm1_9'),
(10, 1, 'Grandfather collects crabs', 'คุณปู่จับปู', 'Khun bpùu jàp bpuu', 'title of respect - paternal grandfather - catch - crab', '', 'm1_10'),
(11, 1, 'Take aunt to the forest', 'พาป้าไปป่า', 'Phaa bpâa bpai bpàa', 'take - aunt - go - forest', '', 'm1_11'),
(12, 1, 'A dog and a horse are coming', 'หมาและม้าจะมา', 'Măa lae máa jà maa', 'dog - and - horse - future marker - come', '', 'm1_12'),
(13, 1, 'I bought a tiger shirt that has four colours', 'ซื้อเสื้อลายเสือมีสี่สี', 'Séu sêua laai sĕua mii sìi sĭi', 'buy - shirt - pattern - tiger - have - four - colour', '', 'm1_13'),
(14, 2, 'Female polite particle', 'ค่ะ', 'Khâ', '', 'Particle used by female speakers at the end of a sentence for politeness, as a response when their name is called, and during a conversation to indicate agreement. Pronounced with different tones depending on the context. Thai has many particles which have no equivalent in English. They are generally used to indicate politeness or imply a question.', 'm2_1'),
(15, 2, 'Male polite particle', 'ครับ', 'Khráp/khráp', '', 'Particle used by male speakers at the end of a sentence for politeness, as a reponse when their name is called, and during conversation to indicate agreement. ''Kr'' sounds are often shortened to ''K'' in Bangkok speech.', 'm2_2'),
(16, 2, 'General greeting', 'สวัสดีครับ', 'Sà-wàt-dìi khráp', '', 'Can be used at any time of day. Can also be used for goodbye.', 'm2_3'),
(17, 2, 'Are you well?', 'สบายดีไหมครับ', 'Sà-baai dii mái khráp?', 'well - good - or not - polite particle', '', 'm2_4'),
(18, 2, 'Yes, I''m well', 'สบายดีครับ', 'Sà-baai dii khráp', 'well - good - polite particle', '', 'm2_5'),
(19, 2, 'I''m not well', 'ผมไม่ค่อยสบายครับ', 'Phŏhm mâi khôi sà-baai khráp', 'I - not - quite - well - polite particle', '', 'm2_6'),
(20, 2, 'And you?', 'คุณล่ะครับ', 'Kun lâ khráp?', 'you - question particle - polite particle', '', 'm2_7'),
(21, 2, 'Good luck', 'โชคดีนะครับ', 'Chôhk dii ná khráp', 'luck - good - softening particle - polite particle', '', 'm2_8'),
(22, 2, 'What''s your name?', 'คุณชื่ออะไรครับ', 'Khun chêu à-rai khráp?', 'you - name - what - polite particle?', '', 'm2_9'),
(23, 2, 'Do you have a nickname?', 'คุณมีชื่อเล่นไหมครับ', 'Khun mii chêu-lên mái khráp?', 'you - have - nickname - or not - polite particle?', 'Thai people often have long names but the nick name is always short and is used by most people in everyday life.', 'm2_10'),
(24, 2, 'Nice to meet you.', 'ยินดีที่ได้รู้จักครับ', 'Yin dii thîi dâi rúu-jàk khráp', 'feel pleased - good - to - can - know - polite particle', '', 'm2_11'),
(25, 2, 'See you later', 'พบกันใหม่ครับ', 'Phóp gan mài khráp', 'meet - together - again - polite particle', '', 'm2_12'),
(26, 2, 'Where are you from?', 'คุณมาจากที่ไหนครับ', 'Khun maa jàak thîi năi khráp?', 'you - come - from - place - which - polite particle', '', 'm2_13'),
(27, 2, 'Where are you going?', 'คุณจะไปไหนครับ', 'Khun jà bpai năi khráp?', 'you - future marker - go - where - polite particle?', '', 'm2_14'),
(28, 2, 'Excuse me, sorry', 'ขอโทษครับ', 'Kŏr thôt khráp', 'request - punishment / blame - polite particle', '', 'm2_15'),
(29, 2, 'Have you eaten?', 'กินข้าวหรือยังครับ', 'Gin khâao (láew) rĕuu yang khráp?', 'eat - rice - (already) - or - not yet - polite particle?', 'Thais take great care to ensure that everyone has eaten, so this question is very common.', 'm2_16'),
(30, 2, 'No problem/You''re welcome/it''s alright', 'ไม่เป็นไรครับ', 'Mâi bpen rai khráp', 'not - is - anything - polite particle', '', 'm2_17'),
(31, 2, 'That''s fine.', 'ดีแล้วครับ', 'Dii láew khráp', 'good - already - polite particle', '', 'm2_18'),
(32, 2, 'That''s correct.', 'ถูกต้องครับ', 'Thùuk dtông khráp', 'correct - must - polite particle', '', 'm2_19'),
(33, 2, 'Come and eat!', 'มากินข้าวกัน', 'Maa gin khâao gan', 'come - eat - rice - together', 'Thai people always invite you to join their meal if you’re visiting their home.', 'm2_20'),
(34, 2, 'Thank you', 'ขอบคุณครับ', 'Khàwp khun khráp', 'thank - you - polite particle', '', 'm2_21'),
(35, 2, 'Please', 'กรุณา', 'Gàa-róo-naa', '', '', 'm2_22'),
(36, 2, 'Just a moment.', 'สักครู่', 'Sàk khrûu', 'just - a short moment', '', 'm2_23'),
(37, 2, 'Do you understand?', 'เข้าใจไหมครับ', 'Khâo jai mái khráp?', 'enter - heart/mind - or not - polite particle', '', 'm2_24'),
(38, 2, 'I understand.', 'ผมเข้าใจ', 'Phŏhm khâo jai', ' I - enter - heart/mind', '', 'm2_25'),
(39, 2, 'I don''t understand.', 'ผมไม่เข้าใจ', 'Phŏhm mâi khâo jai', 'I - not - enter - heart/mind', '', 'm2_26'),
(40, 2, 'Pardon? (please repeat)', 'อะไรนะครับ', 'À-rai ná khráp?', 'what - softening particle - polite particle', 'The particle ''ná'' is added to the end of a sentence to soften it.', 'm2_27'),
(41, 2, 'Can you please speak more slowly', 'ช่วยพูดช้าๆหน่อยนะครับ', 'Chûay phût chá chá nòi ná khráp', 'help - speak - slow - slow - a little - softening particle - polite particle', '', 'm2_28'),
(42, 2, 'Can you please say that again.', 'ช่วยพูดอีกครั้งได้ไหมครับ', 'Chûay phût èek khráng dâi mái khráp?', 'help - speak - another - instance - can - or not - polite particle?', '', 'm2_29'),
(43, 2, 'You can speak Thai!', 'คุณพูดไทยได้!', 'Khun phût Thai dâi!', 'you - speak - Thai - can!', '', 'm2_30'),
(44, 2, 'I can speak a little Thai.', 'ผมพูดไทยได้นิดหน่อยครับ', 'Phŏhm phût Thai dâi nít-nòy khráp', 'I - speak - Thai - can - a little bit - polite particle', '', 'm2_31'),
(45, 2, 'I can''t speak Thai.', 'ผมพูดไทยไม่ได้', 'Phŏhm phût Thai mâi dâi.', 'I - speak - Thai - not - can - polite particle', '', 'm2_32'),
(46, 2, 'What is this?', 'นี่คืออะไรครับ', 'Nîi kheu à-rai khráp?', 'this - is - what - polite particle?', '', 'm2_33'),
(47, 2, 'What do you call this in Thai?', 'อันนี้ภาษาไทยเรียกว่าอะไรครับ', 'An níi pha-săa Thai rîak wâa à-rai khráp?', 'item - this - language - Thai - called - that - what - polite particle', '', 'm2_34'),
(48, 2, 'I like it', 'ผมชอบ', 'Phŏhm chôrp', 'I - like', '', 'm2_35'),
(49, 2, 'I don''t like it', 'ผมไม่ชอบ', 'Phŏhm mâi chôrp', 'I - not - like', '', 'm2_36'),
(50, 2, 'I don''t know.', 'ผมไม่รู้', 'Phŏhm mâi róo.', 'I - not - know', '', 'm2_37'),
(51, 2, 'That''s great!', 'ดีมาก', 'Dii mâak!', 'good - very', '', 'm2_38'),
(52, 2, 'What are you doing?', 'คุณทำอะไรอยู่ครับ', 'Khun tham à-rai yùu khráp?', 'you - do - what - currently - polite particle?', '', 'm2_39'),
(53, 2, 'How old are you?', 'คุณอายุเท่าไหร่ครับ', 'Khun aa-yúu thâo rai khráp?', 'you - age - equal to - what - polite particle?', '', 'm2_40'),
(54, 2, 'No thanks', 'ไม่ครับ ขอบคุณนะครับ', 'Mâi khráp, khop khun ná khráp', 'no - polite particle - thank - you - softening particle - polite particle', '', 'm2_41'),
(55, 2, 'Help me!', 'ช่วยด้วย!', 'Chûay dûai!', 'help - particle used at the end of a request', '', 'm2_42'),
(56, 2, 'Do you have a bathroom?', 'มีห้องน้ำไหมครับ', 'Mii hâwng náam mái khráp?', 'have - room - water - or not - polite particle?', '', 'm2_43'),
(57, 3, 'Wake up', 'ตื่น', 'Dtèuun', '', '', 'm3_1'),
(58, 3, 'Take a bath/shower', 'อาบน้ำ', 'Àap náam', 'bathe - water', '', 'm3_2'),
(59, 3, 'Brush teeth', 'แปรงฟัน', 'Bpraaeng fan', 'brush - tooth', '', 'm3_3'),
(60, 3, 'Comb hair', 'หวีผม', 'Wĭi phŏm', 'comb - hair', '', 'm3_4'),
(61, 3, 'Get dressed', 'แต่งตัว', 'Dtàeng dtua', 'dress - oneself', '', 'm3_5'),
(62, 3, 'Wash clothes', 'ซักผ้า', 'Sák phâa', 'wash - clothes', '', 'm3_6'),
(63, 3, 'Work', 'ทำงาน', 'Tham ngaan', 'do - work', '', 'm3_7'),
(64, 3, 'Prepare food', 'ทำอาหาร', 'Tham a-hăan', 'make - food', '', 'm3_8'),
(65, 3, 'Eat', 'กิน / ทาน', 'Gin / thaan', '', '', 'm3_9'),
(66, 3, 'Drink', 'ดื่ม / กิน', 'Dèum / gin', '', '', 'm3_10'),
(67, 3, 'Go home', 'กลับบ้าน', 'Glàp bâan', 'return - home', '', 'm3_11'),
(68, 3, 'Do the housework', 'ทำงานบ้าน', 'Tham ngaan bâan', 'do - work - home', '', 'm3_12'),
(69, 3, 'Play sport', 'เล่นกีฬา', 'Lên gi-laa', 'play - sport', '', 'm3_13'),
(70, 3, 'Watch TV', 'ดูทีวี', 'Doo thii-wii', 'look at - tv', '', 'm3_14'),
(71, 3, 'Go to sleep', 'ไปนอน', 'Bpai norn', 'go - sleep', '', 'm3_15'),
(72, 4, 'Sunny', 'แดดออก', 'Dàaet àawk', 'sunshine - go out (from the sun)', '', 'm4_1'),
(73, 4, 'Raining', 'ฝนตก', 'Fŏhn dtòk', 'rain - fall', '', 'm4_2'),
(74, 4, 'Cloudy', 'มีเมฆ', 'Mii mâehk', 'have - cloud', '', 'm4_3'),
(75, 4, 'Overcast, might rain', 'ครึ้มฟ้าครึ้มฝน', 'Khréum fáa khréum fŏhn', 'dark, dense - sky - dark, dense - rain', '', 'm4_4'),
(76, 4, 'Windy', 'ลมแรง', 'Lohm raaeng', 'wind - strong', '', 'm4_5'),
(77, 4, 'Hot', 'ร้อน', 'Rórn', '', '', 'm4_6'),
(78, 4, 'Cold', 'หนาว', 'Năao', '', '', 'm4_7'),
(79, 4, 'Humid', 'ชื้น', 'Chéuun', '', '', 'm4_8'),
(80, 4, 'Flood', 'น้ำท่วม', 'Náam thûaam', 'water - flood', '', 'm4_9'),
(81, 4, 'Storm', 'พายุ', 'Phaa-yúu', '', '', 'm4_10'),
(82, 4, 'Thunderstorm', 'พายุฟ้าคะนอง', 'Phaa-yúu fáa khá-nawng', 'storm - sky - thunder', '', 'm4_11'),
(83, 4, 'Drought', 'แห้งแล้ง', 'Hâaeng láaeng', 'dry - dry', '', 'm4_12'),
(84, 4, 'What''s the weather like?', 'อากาศเป็นอย่างไรบ้างครับ', 'Aa-gàat bpen yàang-rai bâang khráp?', 'weather - is - how - some - polite particle?', '', 'm4_13'),
(85, 4, 'It''s hot and humid.', 'ร้อนชื้น', 'Rórn chéuun', 'hot - humid', '', 'm4_14'),
(86, 4, 'Is it going to rain?', 'ฝนกำลังจะตกใช่ไหมครับ', 'Fŏhn gamlang-jà dtòk châi-mái khráp?', 'rain - about to - fall - yes or no - polite particle', '', 'm4_15'),
(87, 4, 'It might rain in the afternoon.', 'ฝนน่าจะตกตอนบ่ายนี้นะครับ', 'Fŏhn nâa jà dtòk dtaawn bàai níi ná khráp', 'rain - prefix indicating probability - future marker - fall - during - afternoon - this - softening particle - polite particle', '', 'm4_16'),
(88, 4, 'It''s too hot to play soccer.', 'อากาศร้อนเกินไปที่จะเล่นฟุตบอล', 'Aa-gàat rórn gern-bpai thîi jà lên fút-baawn', 'weather - hot - excessive - to - future marker - play - football', 'The expression ''gern bpai'' is similar to ''too''. Thai has a limited number of final consonant sounds. The letter ''L'' (ล) is pronounced ''N'' at the end of a syllable, hence ''foot-baawn''.', 'm4_17'),
(89, 4, 'It''s cold today.', 'วันนี้อากาศหนาวครับ', 'Wan níi aa-gàat năao khráp.', 'day - this - weather - cold - polite particle', '', 'm4_18'),
(90, 4, 'It''s hot, isn''t it?', 'อากาศร้อนเนอะ', 'Aa-gàat rórn núh?', 'weather - hot - particle requesting confirmation', '', 'm4_19'),
(91, 4, 'It''s raining hard.', 'ฝนตกหนัก', 'Fŏhn dtòk nàk', 'rain - fall - heavy', '', 'm4_20'),
(92, 4, 'Cool season', 'ฤดูหนาว', 'Réu-doo năao', 'season - cold', 'The word ''หน้า'' (nâa) can also be used for ''season''.', 'm4_21'),
(93, 4, 'Rainy season', 'ฤดูฝน', 'Réu-doo fŏhn', 'season - rain', '', 'm4_22'),
(94, 4, 'Hot season', 'ฤดูร้อน', 'Réu-doo rórn', 'season - hot', '', 'm4_23'),
(95, 4, 'We will plant the rice in the rainy season', 'เราจะปลูกข้าวในฤดูฝน', 'Rao jà bplùuk khâao nai réu-doo fŏhn', 'we - future marker - plant - rice - in - season - rain', '', 'm4_24'),
(96, 5, 'Chiang Rai', 'เชียงราย', 'Chiiang Raai', '', '', 'm5_1'),
(97, 5, 'Mae Hong Son', 'แม่ฮ่องสอน', 'Mâae Hâawng Săawn', '', '', 'm5_2'),
(98, 5, 'Chiang Mai', 'เชียงใหม่', 'Chiiang Mài', '', '', 'm5_3'),
(99, 5, 'Sukhothai', 'สุโขทัย', 'Sòo-khŏh-thai', '', '', 'm5_4'),
(100, 5, 'Ayuthaya', 'อยุธยา', 'À-yóot-thá-yaa', '', '', 'm5_5'),
(101, 5, 'Kanchanaburi', 'กาญจนบุรี', 'Gaan-jà-na-bòo-ree', '', '', 'm5_6'),
(102, 5, 'Bangkok', 'กรุงเทพฯ', 'Grung-thâep', 'The actual name of Bangkok is extremely long and many people cannot remember it. The character ''ฯ'' is called ''pai yan noi'' and indicates an abbreviation. ', '', 'm5_7'),
(103, 5, 'Hua Hin', 'หัวหิน', 'Hŭaa Hĭn', '', '', 'm5_8'),
(104, 5, 'Chumphon', 'ชุมพร', 'Choom-phaawn', '', '', 'm5_9'),
(105, 5, 'Koh Tao', 'เกาะเต่า', 'Gàw Dtào', 'island - turtle', '', 'm5_10'),
(106, 5, 'Koh Pha Ngan', 'เกาะพะงัน', 'Gàw Phá Ngan', '', '', 'm5_11'),
(107, 5, 'Koh Samui', 'เกาะสมุย', 'Gàw Sà-mŭi', '', '', 'm5_12'),
(108, 5, 'Surat Thani', 'สุราษฎร์ธานี', 'Sòo-râat-tha-nee', '', '', 'm5_13'),
(109, 5, 'Khao Sok National Park', 'อุทยานแห่งชาติเขาสก', 'Òot-thá-yaan hàeng-châat Khăo Sòhk', 'park - national - khao sok', '', 'm5_14'),
(110, 5, 'Krabi', 'กระบี่', 'Grà-bèe', '', 'May be shortened to ''Gà-bèe''.', 'm5_15'),
(111, 5, 'Phuket', 'ภูเก็ต', 'Phuu-gèt', '', '', 'm5_16'),
(112, 5, 'Satun', 'สตูล', 'Sà-dtuun', '', '', 'm5_17'),
(113, 5, 'Country', 'ประเทศ', 'Bprà-thêt', '', 'It is common to use this word before the country name when referring to a country.', 'm5_18'),
(114, 5, 'Australia', 'ออสเตรเลีย', 'Aús-tre-lia', '', '', 'm5_19'),
(115, 5, 'Canada', 'แคนาดา', 'Khae-naa-daa', '', '', 'm5_20'),
(116, 5, 'China', 'จีน', 'Jiin', '', '', 'm5_21'),
(117, 5, 'France', 'ฝรั่งเศส', 'Fà-ràng-sèt', '', 'The word ''fà-ràng'' is used to refer to any white foreigner.', 'm5_22'),
(118, 5, 'Germany', 'เยอรมัน', 'Ye-ra-man', '', '', 'm5_23'),
(119, 5, 'India', 'อินเดีย', 'In-diia', '', '', 'm5_24'),
(120, 5, 'Japan', 'ญี่ปุ่น', 'Yîi-bpùn', '', '', 'm5_25'),
(121, 5, 'Laos', 'ลาว', 'Laao', '', '', 'm5_26'),
(122, 5, 'Malaysia', 'มาเลเซีย', 'Maa-laeh-siia', '', '', 'm5_27'),
(123, 5, 'Myanmar', 'พม่า', 'Phá-mâa', '', '', 'm5_28'),
(124, 5, 'New Zealand', 'นิวซีแลนด์', 'Niu-see-laen', '', '', 'm5_29'),
(125, 5, 'Russia', 'รัสเซีย', 'Rát-siia', '', '', 'm5_30'),
(126, 5, 'Spain', 'สเปน', 'Sà-pen', '', '', 'm5_31'),
(127, 5, 'United Kingdom', 'อังกฤษ', 'Ang-krìt', '', '', 'm5_32'),
(128, 5, 'USA', 'อเมริกา', 'Àa-meh-ríi-gaa', '', '', 'm5_33'),
(129, 5, 'Vietnam', 'เวียดนาม', 'Wîiat-naam', '', '', 'm5_34'),
(130, 5, 'I''m Australian', 'ผมเป็นคนออสเตรเลียครับ', 'Phŏhm bpen khon Aús-tre-lia khráp', 'I - am - person - Australia - polite particle', '', 'm5_35'),
(131, 5, 'She''s French', 'เธอเป็นคนฝรั่งเศสครับ', 'Thuuhr bpen khon Fà-ràng-sèt khráp', 'she - is - person - France - polite particle', '', 'm5_36'),
(132, 5, 'I''ve just come from Laos.', 'ผมเพิ่งกลับมาจากประเทศลาวครับ', 'Phŏhm phêerng glàp maa jàak bprà-thêt Laao khráp', 'I - just - return - come - from - Laos - polite particle', '', 'm5_37'),
(133, 5, 'Language', 'ภาษา', 'Pha-săa', '', '', 'm5_38'),
(134, 5, 'I speak Japanese.', 'ผมพูดภาษาญี่ปุ่นครับ', 'Phŏhm phût pha-săa Yîi-bpùn khráp', 'I - speak - language - Japan - polite particle', '', 'm5_39'),
(135, 6, 'Black', 'สีดำ', 'Sĭi dam', '', '', 'm6_1'),
(136, 6, 'White', 'สีขาว', 'Sĭi khăao', '', '', 'm6_2'),
(137, 6, 'Sky blue', 'สีฟ้า', 'Sĭi fáa', 'colour - sky', '', 'm6_3'),
(138, 6, 'Navy blue', 'สีน้ำเงิน', 'Sĭi nám ngern', 'colour - water - silver', '', 'm6_4'),
(139, 6, 'Green', 'สีเขียว', 'Sĭi khiăao', '', '', 'm6_5'),
(140, 6, 'Red', 'สีแดง', 'Sĭi daaeng', '', '', 'm6_6'),
(141, 6, 'Orange', 'สีส้ม', 'Sĭi sôhm', '', '', 'm6_7'),
(142, 6, 'Pink', 'สีชมพู', 'Sĭi chom-pou', '', '', 'm6_8'),
(143, 6, 'Brown', 'สีน้ำตาล', 'Sĭi náam-dtaan', 'colour - sugar', '', 'm6_9'),
(144, 6, 'Purple', 'สีม่วง', 'Sĭi mûang', '', '', 'm6_10'),
(145, 6, 'Yellow', 'สีเหลือง', 'Sĭi lĕuang', '', '', 'm6_11'),
(146, 6, 'Dark colour', 'สีเข้ม / สีแก่', 'Sĭi khêm / Sĭi gàae', '', '', 'm6_12'),
(147, 6, 'Dark green', 'สีเขียวเข้ม / สีเขียวแก่', 'Sĭi khiăao khêm / Sĭi khiăao gàae', '', '', 'm6_13'),
(148, 6, 'Light colour', 'สีอ่อน', 'Sĭi àawn', '', '', 'm6_14'),
(149, 6, 'A white car', 'รถยนต์สีขาว', 'Róht-yohn sĭi khăao', 'car - white', '', 'm6_15'),
(150, 6, 'Yellow Shirt', 'เสื้อเหลือง', 'Sêuua lĕuang', 'shirt - yellow', '', 'm6_16'),
(151, 6, 'Do you have this in red?', 'คุณมีแบบนี้แต่เป็นสีแดงไหมครับ', 'Khun mii bàaep níi dtàae bpen sĭi daaeng mái khráp?', 'you - have - style - this - but - be - colour - red - or not - polite particle?', '', 'm6_17'),
(152, 6, 'Today it''s lucky to wear green.', 'วันนี้โชคดีที่ใส่สีเขียวครับ', 'Wan níi chôhk dii thîi sài sĭi khiăao khráp', 'day - this - luck - good - to - put on - colour - green - polite particle', 'The word ''thîi'' can have a variety of meanings including  ''at'', ''that'', ''which'' and ''for''. In Thailand each day of the week has a lucky and unlucky colour, a tradition based on Hindu mythology.', 'm6_18'),
(153, 7, 'Dog', 'หมา', 'Măa', '', '', 'm7_1'),
(154, 7, 'Cat', 'แมว', 'Maeo', '', '', 'm7_2'),
(155, 7, 'Elephant', 'ช้าง', 'Cháang', '', 'The elephant is a symbol of Thailand as they were used historically to fight against invaders. It is believed that elephants saved Thailand from colonisation.', 'm7_3'),
(156, 7, 'Monkey', 'ลิง', 'Ling', '', '', 'm7_4'),
(157, 7, 'Tiger', 'เสือ', 'Sĕua', '', '', 'm7_5'),
(158, 7, 'Snake', 'งู', 'Nguu', '', '', 'm7_6'),
(159, 7, 'Mosquito', 'ยุง', 'Yung', '', '', 'm7_7'),
(160, 7, 'Insect, bug', 'แมลง', 'Máa-laaeng', '', '', 'm7_8'),
(161, 7, 'Ant', 'มด', 'Móht', '', '', 'm7_9'),
(162, 7, 'Red ant', 'มดแดง', 'Móht daaeng', 'ant - red', '', 'm7_10'),
(163, 7, 'Fire ant', 'มดคันไฟ', 'Móht khan fai', 'ant - itch - fire', '', 'm7_11'),
(164, 7, 'Frog', 'กบ ', 'Gòhp', '', 'It is common in Thailand for people to eat frogs. Live frogs are sold at many fresh markets.', 'm7_12'),
(165, 7, 'Mouse / Rat', 'หนู ', 'Nŭu', '', 'Rats are sometimes grilled and eaten with rice, especially in rural Isan.', 'm7_13'),
(166, 7, 'Fish', 'ปลา', 'Bplaa', '', '', 'm7_14'),
(167, 7, 'Pig', 'หมู', 'Mŭu', '', '', 'm7_15'),
(168, 7, 'Water buffalo', 'ควาย ', 'Khwaai', '', 'Buffaloes were traditionally used for rice farming, a practice which is still common in poorer areas. The buffalo is associated with lack of intelligence when used to describe a person.', 'm7_16'),
(169, 7, 'Bird', 'นก ', 'Nók', '', '', 'm7_17'),
(170, 7, 'Chicken', 'ไก่', 'Gài', '', '', 'm7_18'),
(171, 7, 'Duck', 'เป็ด ', 'Bpèt', '', '', 'm7_19'),
(172, 7, 'Pet', 'สัตว์เลี้ยง', 'Sàt líiang', 'animal - look after', '', 'm7_20'),
(173, 7, 'There are snakes in the rice fields.', 'มีงูหลายตัวอยู่ในนาข้าวครับ', 'Mii nguu yùu nai naa khâao khráp', 'there are - snake - situated - in - field - rice - polite particle', '', 'm7_21'),
(174, 7, 'There are a lot of elephants in Surin.', 'ที่สุรินทร์มีช้างเยอะ', 'Thîi Sòo-rin mii cháang yúh', 'at - Surin - exists - elephant - many', '', 'm7_22'),
(175, 7, 'We have a dog for security.', 'เรามีหมาเพื่อรักษาความปลอดภัยครับ', 'Rao mii măa phêuua rák-săa khwaam bplàawt phai khráp', 'we - have - dog - for the purpose of - take care - prefix which converts adjective or verb into a noun - free from - harm - polite particle', '', 'm7_23'),
(176, 7, 'There are a lot of mosquitoes in the rainy season.', 'ยุงเยอะในช่วงฤดูฝน', 'Yung yúh nai chûaang réu-doo fŏhn', 'mosquito - many - in - period - season - rain', '', 'm7_24'),
(177, 8, '0', 'ศูนย์', 'Sǔun', '', 'Thai has its own characters for numbers but they are rarely used in everyday writing. They can be found on Thai bank notes. The character for ''zero'' is ''๐''.', 'm8_1'),
(178, 8, '1, 2, 3, 4,5 ', 'หนึ่ง, สอง, สาม, สี่, ห้า', 'Nèung, săawng, săam, sìi, hâa', '', 'Thai characters ๑, ๒, ๓, ๔, ๕', 'm8_2'),
(179, 8, '6, 7, 8, 9, 10', 'หก, เจ็ด, แปด, เก้า, สิบ', 'Hòk, jèt, bpàet, gâao, sìp', '', 'Thai characters ๖, ๗, ๘, ๙, ๑๐', 'm8_3'),
(180, 8, '11', 'สิบเอ็ด', 'Sìp-èt', '', '', 'm8_4'),
(181, 8, '12', 'สิบสอง', 'Sìp-săawng', '', '', 'm8_5'),
(182, 8, '13', 'สิบสาม', 'Sìp-săam', '', '', 'm8_6'),
(183, 8, '14', 'สิบสี่', 'Sìp-sìi', '', '', 'm8_7'),
(184, 8, '15', 'สิบห้า', 'Sìp-hâa', '', '', 'm8_8'),
(185, 8, '16', 'สิบหก', 'Sìp-hòk', '', '', 'm8_9'),
(186, 8, '17', 'สิบเจ็ด', 'Sìp-jèt', '', '', 'm8_10'),
(187, 8, '18', 'สิบแปด', 'Sìp-bpàet', '', '', 'm8_11'),
(188, 8, '19', 'สิบเก้า', 'Sìp-gâao', '', '', 'm8_12'),
(189, 8, '20', 'ยี่สิบ', 'Yîi-sìp', '', '', 'm8_13'),
(190, 8, '21', 'ยี่สิบเอ็ด', 'Yîi-sìp-èt', '', '', 'm8_14'),
(191, 8, '22', 'ยี่สิบสอง', 'Yîi-sìp-săawng', '', '', 'm8_15'),
(192, 8, '30', 'สามสิบ', 'Săam-sìp', '', '', 'm8_16'),
(193, 8, '40', 'สี่สิบ', 'Sìi-sìp', '', '', 'm8_17'),
(194, 8, '80', 'แปดสิบ', 'Bàet-sìp', '', '', 'm8_18'),
(195, 8, '100', 'หนึ่งร้อย / ร้อยหนึ่ง', 'Nèung-róoi / Róoi-nèung', '', 'Sometimes pronounced ''lóoi''', 'm8_19'),
(196, 8, '134', 'หนึ่งร้อยสามสิบสี่', 'Nèung-róoi săam-sìp-sìi', '', '', 'm8_20'),
(197, 8, '300', 'สามร้อย', 'Săam róoi', '', '', 'm8_21'),
(198, 8, '1000', 'หนึ่งพัน', 'Nèung-phan', '', '', 'm8_22'),
(199, 8, '2000', 'สองพัน', 'Săawng-phan', '', '', 'm8_23'),
(200, 8, '10,000', 'หนึ่งหมื่น', 'Nèung-mèun', '', '', 'm8_24'),
(201, 8, '50,000', 'ห้าหมื่น', 'Hâa-mèun', '', '', 'm8_25'),
(202, 8, '100,000', 'หนึ่งแสน', 'Nèung-săen', '', '', 'm8_26'),
(203, 8, '600,000', 'หกแสน', 'Hòk-săen', '', '', 'm8_27'),
(204, 8, '1,000,000', 'หนึ่งล้าน', 'Nèung-láan', '', '', 'm8_28'),
(205, 9, 'Minute', 'นาที', 'Naa-thii', '', '', 'm9_1'),
(206, 9, 'Hour', 'ชั่วโมง', 'Chûaa-mohng', '', '', 'm9_2'),
(207, 9, 'Day', 'วัน', 'Wan', '', '', 'm9_3'),
(208, 9, 'Week', 'อาทิตย์ / สัปดาห์', 'Aa-thít / Sàp-daa', '', '', 'm9_4'),
(209, 9, 'Month', 'เดือน', 'Deuan', '', '', 'm9_5'),
(210, 9, 'Year', 'ปี', 'Bpii', '', '', 'm9_6'),
(211, 9, 'Today', 'วันนี้', 'Wan níi', '', '', 'm9_7'),
(212, 9, 'Tomorrow', 'พรุ่งนี้', 'Phrûng-níi', '', '', 'm9_8'),
(213, 9, 'Yesterday', 'เมื่อวาน', 'Mêua wan', '', '', 'm9_9'),
(214, 9, 'This week', 'อาทิตย์นี้ / สัปดาห์นี้', 'Aa-thít níi / Sàp-daa níi', 'week - this', '', 'm9_10'),
(215, 9, 'Next week', 'อาทิตย์หน้า / สัปดาห์หน้า', 'Aa-thít nâa / Sàp-daa nâa', 'week - next', '', 'm9_11'),
(216, 9, 'Last week', 'อาทิตย์ที่แล้ว / สัปดาห์ที่แล้ว', 'Aa-thít thîi-láew / Sàp-daa thîi-láew', 'week - previous', '', 'm9_12'),
(217, 9, 'Next month', 'เดือนหน้า', 'Deuan nâa', 'month - next', '', 'm9_13'),
(218, 9, 'Last month', 'เดือนที่แล้ว', 'Deuan thîi-láew', 'month - previous', '', 'm9_14'),
(219, 9, 'Last year', 'ปีที่แล้ว', 'Bpii thîi-láew', 'year - previous', '', 'm9_15'),
(220, 9, 'Right now', 'เดี๋ยวนี้', 'Dĭiao níi', 'moment - this', '', 'm9_16'),
(221, 9, 'In a moment', 'อีกสักครู่', 'Èek dĭiao', 'another/more - moment', '', 'm9_17'),
(222, 9, 'Just a moment ago', 'เมื่อครู่นี้', 'Mêua khrûu níi', 'point in time - a short moment - this', '', 'm9_18'),
(223, 9, 'You''re early', 'คุณมาเร็วจัง', 'Khun maa reo jang', 'you - come - fast - really', '', 'm9_19'),
(224, 9, 'He came late', 'เขามาช้าครับ', 'Khăo maa cháa khráp', 'he - come - slow/late - polite particle', '', 'm9_20'),
(225, 9, 'Come home late', 'กลับบ้านช้า', 'Glàp bâan cháa', 'return - home - slow/late', '', 'm9_21'),
(226, 9, 'Later on, afterwards', 'หลังจาก', 'Lăng jàak', 'behind - from', '', 'm9_22'),
(227, 9, 'Morning', 'เช้า', 'Cháao', '', '', 'm9_23'),
(228, 9, 'Afternoon', 'บ่าย', 'Bàai', '', '', 'm9_24'),
(229, 9, 'Evening', 'เย็น', 'Yen', '', '', 'm9_25'),
(230, 9, 'Night', 'กลางคืน', 'Glaang kheun', 'in the centre of - night', '', 'm9_26'),
(231, 9, 'In the early evening', 'ตอนเย็น', 'Dtawn yen', 'at (time of day) - early evening', '', 'm9_27'),
(232, 9, 'At night', 'ในเวลากลางคืน', 'Nai waeh-lah glaang-kheun', 'in - time - night', '', 'm9_28'),
(233, 9, 'This morning', 'เช้านี้', 'Cháao níi', 'morning - this', '', 'm9_29'),
(234, 9, 'Last night', 'เมื่อคืน', 'Mêua kheun', 'point in time - night', '', 'm9_30'),
(235, 9, 'All day', 'ตลอดวัน', 'Dtà-làwt wan', 'throughout - day', '', 'm9_31'),
(236, 9, 'What''s the time?', 'ตอนนี้กี่โมงครับ', 'Dtàwn níi gìi mohng khráp?', 'moment - this - how many - hour - polite particle?', '', 'm9_32'),
(237, 9, '12am midnight', 'เที่ยงคืน', 'Thîiang kheun', '12:00 - night', '', 'm9_33'),
(238, 9, '2am', 'ตีสอง', 'Dtee săawng', 'after midnight - two', 'From 1AM to 5AM, use the word “dtee” followed by the hour.', 'm9_34'),
(239, 9, '4:30am', 'ตีสี่ครึ่ง', 'Dtee sìi khrêung', 'after midnight - four - half', '', 'm9_35'),
(240, 9, '5am', 'ตีห้า', 'Dtee hâa', 'after midnight - five', '', 'm9_36'),
(241, 9, '6am', 'หกโมงเช้า', 'Hòhk mohng cháao', 'six - hour - morning', 'From 6AM to 11AM, use the hour followed by “mohng cháao”. ', 'm9_37'),
(242, 9, '7am', 'เจ็ดโมงเช้า / หนึ่งโมงเช้า', 'Jèt mohng cháao / Nèung mohng cháao', 'seven - hour - morning / one - hour - morning', 'From 7AM to 11AM, some people count 7AM as 1, 8AM as 2 and so on. This comes from the tradition of the temples sounding a drum once at 7AM, twice at 8AM etc.', 'm9_38'),
(243, 9, '8am', 'แปดโมงเช้า / สองโมงเช้า ', 'Bpàet mohng cháao / Săawng mohng cháao', 'eight - hour - morning / two - hour - morning', '', 'm9_39'),
(244, 9, '10:15am', 'สิบโมงสิบห้า(นาที) / สี่โมงสิบห้า(นาที)', 'Sìp mohng sìp-hâa / Sìi mohng sìp-hâa', 'ten - hour - fifteen / four - hour - fifteen', 'You do not say ''cháao'' when including minutes past the hour.', 'm9_40'),
(245, 9, '12pm', 'เที่ยง', 'Thîiang', 'noon', '', 'm9_41'),
(246, 9, '12:45pm', 'เที่ยงสี่สิบห้า', 'Thîiang sìi sìp hâa', 'noon - forty-five', '', 'm9_42'),
(247, 9, '1pm', 'บ่ายโมง', 'Bàai mohng', 'afternoon - hour', '', 'm9_43'),
(248, 9, '2pm', 'บ่ายสองโมง', 'Bàai săawng mohng', 'afternoon - two - hours', 'From 1PM to 4PM, use the word “bàai” followed by the hour, then “mohng”.', 'm9_44'),
(249, 9, '4pm', 'สี่โมงเย็น / บ่ายสี่โมง', 'Sìi mohng yen / Bàai sìi mohng', 'four - hour - early evening / afternoon - four - hour', 'Late afternoon / early evening is known as ''yen''. 4PM may be ''bàai'' or ''yen''.', 'm9_45'),
(250, 9, '5:15pm', 'ห้าโมงเย็นสิบห้า', 'Hâa mohng yen sìp-hâa', 'five - hour - early evening - fifteen', 'For 5PM and 6PM use the hour followed by ''mohng yen''', 'm9_46'),
(251, 9, '7pm', 'หนึ่งทุ่ม / ทุ่มหนึ่ง ', 'Nèung thûm / Thûm nèung', 'one - evening / evening - one', 'ทุ่ม (Thûm) means ''evening''. The evening hours follow a similar convention to the morning, with 7PM being 1, 8PM being 2 and so on until 11PM. However, unlike the morning there tends to be just this one system.', 'm9_47'),
(252, 9, '7:30pm', 'ทุ่มครึ่ง / หนึ่งทุ่มครึ่ง', 'Thûm khrêung / Nèung thûm khrêung', 'evening - half / one - evening - half', '', 'm9_48'),
(253, 9, '8:20pm', 'สองทุ่มยี่สิบ', 'Săawng thûm yîi-sìp ', 'two - evening - twenty', '', 'm9_49'),
(254, 9, '9pm', 'สามทุ่ม ', 'Săam thûm', 'three - evening', '', 'm9_50'),
(255, 9, '11:25pm', 'ห้าทุ่มยี่สิบห้า', 'Hâa thûm yîi-sìp-hâa', 'five - evening - twenty-five', '', 'm9_51'),
(256, 9, 'How long have you been married?', 'คุณแต่งงานกี่ปีมาแล้วครับ', 'Khun dtàeng-ngaan gìi bpii maa láew khráp? ', 'you - married - how many - year - come - already - polite particle?', '', 'm9_52'),
(257, 9, 'I have been in Thailand a long time.', 'ผมอยู่เมืองไทยนานแล้วครับ', 'Phŏm yùu me-ung Thai nahn láew khráp', 'I - stay - country - Thai - long time - already - polite particle', 'We use ''bpen'' before an expression of duration.', 'm9_53'),
(258, 9, 'How long does it take to get to Ayutthaya by train?', 'ไปอยุธยาโดยรถไฟใช้เวลานานเท่าไหร่ครับ', 'Bpai À-yóot-thá-yaa dooy rót fai chái waeh-lah naan thâo-rai khráp?', 'go - Ayutthaya - by - train - use - time - long time - how much - polite particle?', '', 'm9_54'),
(259, 10, 'I/me (female speaker)', 'ฉัน', '(di-)chăn', '', 'The prefix ''di'' is used in formal speech and writing only. ''Chăn'' is also sometimes used by males in a personal setting. Thais will often use their nickname when referring to themselves. Parents will usually use the words for mother or father when referring to themselves in a family setting.', 'm10_1'),
(260, 10, 'I/me (male speaker)', 'ผม', 'Phŏhm', '', '', 'm10_2'),
(261, 10, 'We/us', 'เรา', 'Rao', '', 'Can also mean ''I/me'' in an informal setting.', 'm10_3'),
(262, 10, 'You (singular and plural)', 'คุณ', 'Kun', '', 'Thais often use names or kinship terms instead of ''kun''.', 'm10_4'),
(263, 10, 'You (familiar)', 'ตัวเอง', 'Dtuaa aeng', 'self - oneself', '', 'm10_5'),
(264, 10, 'He/him, she/her', 'เขา', 'Khăo', '', 'Often pronounced ''kháo''. This pronunciation is also used by young people to mean ''I/me''.', 'm10_6'),
(265, 10, 'You (informal), she/her', 'เธอ', 'Thuuhr', '', 'It is more common to use the person''s name when referring to a female.', 'm10_7'),
(266, 10, 'They/them (male/female)', 'พวกเขา', 'Phûak khăo', 'group of - him', '', 'm10_8'),
(267, 10, 'They/them (female)', 'พวกเธอ', 'Phûak thuuhr', 'group of - her', '', 'm10_9'),
(268, 10, 'You/him/her/they/them (for people of high status)', 'ท่าน', 'Tûn', '', '', 'm10_10'),
(269, 10, 'It', 'มัน', 'Mun', '', 'Used for animals as well as objects.', 'm10_11'),
(270, 10, 'Please give it to Mr Komgrit.', 'ช่วยเอามาให้คุณคมกริต', 'Chûay ao maa hâi khun Komgrit ', 'help - take to - give - title of respect - Komgrit', 'The words ''ao maa'' together mean ''take to''.', 'm10_12'),
(271, 10, 'Teacher, I have finished.', 'คุณครู เสร็จแล้วครับ', 'Khun khruu, sèt láew khráp.', 'title of respect - teacher - finish -  past tense marker - polite particle', 'It is common to omit pronouns if the context makes it obvious.', 'm10_13'),
(272, 10, 'Oneself / yourself / himself / herself', 'ตัว', 'Dtuaa', '', '', 'm10_14'),
(273, 10, 'Go and get dressed!', 'ไปแต่งตัว!', 'Bpai dtàeng dtuaa', 'go - dress - yourself', '', 'm10_15'),
(274, 10, 'Take care of yourself', 'ดูแลตัวเองด้วยนะครับ', 'Doo-lae dtua-eeng dûay ná khráp', 'look after - yourself - request particle - softening particle - polite particle', '', 'm10_16'),
(275, 10, 'Each other / one another / together', 'กัน', 'Gun', '', '', 'm10_17'),
(276, 10, 'Father and mother love each other.', 'พ่อแม่รักกันครับ', 'Phâaw mâe rúk gun khráp', 'father - mother - love - each other - polite particle', '', 'm10_18'),
(277, 10, 'Belonging to', 'เป็นของ', 'Bpen kăwng', '', '', 'm10_19'),
(278, 10, 'Whose car is that? It''s Mum''s.', 'นั่นรถของใครครับ ของแม่ครับ', 'Nân róht kăwng krai khráp? Kăwng mâe khráp', 'that - car - belonging to - who - polite particle? belonging to - mother - polite particle', '', 'm10_20'),
(279, 10, 'Your dress is pretty.', 'กระโปรงของคุณสวยครับ', 'Grà-bprohng kăwng khun sŭay khráp', 'dress - belonging to - you - pretty - polite particle', '', 'm10_21'),
(280, 10, 'How much is this?', 'นี่ราคาเท่าไหร่ครับ', 'Nîi raa-khaa thâo rai khráp?', 'this - price - equal to - what - polite particle?', '', 'm10_22'),
(281, 10, 'This table is bigger than that one.', 'โต๊ะตัวนี้ใหญ่กว่าโต๊ะตัวนั้น', 'Dtó dtuaa níi yài gwàa dtó dtuaa nán', 'table - classifier - this - big - more than - table - classifier - that', '', 'm10_23'),
(282, 10, 'Has anyone finished?', 'มีใครเสร็จยังครับ', 'Mii krai sèt yang khráp?', 'is there - anyone - finish - yet - polite particle?', '', 'm10_24'),
(283, 10, 'There''s no one here.', 'ไม่มีใครอยู่ที่นี่เลยครับ', 'Mâi mii krai yùu thîi nîi leuuy khráp', 'not - exist - anyone - situated - place - this - at all - polite particle', '', 'm10_25'),
(284, 10, 'Do you know anyone who can play the guitar?', 'คุณรู้จักใครที่เล่นกีต้าร์เป็นไหมครับ', 'Khun rúu-jàk krai thîi lên gii-dtâa bpen mái khráp?', 'you - know - anyone - that - play - guitar - know how to - or not - polite particle?', '', 'm10_26'),
(285, 10, 'There''s nothing good on TV.', 'ทีวีไม่มีอะไรดูเลย', 'Thii-wii mâi mii à-rai duu leuuy', 'tv - not - have - anything - watch - at all', '', 'm10_27'),
(286, 10, 'I want to buy something to take home.', 'ผมอยากซื้ออะไรกลับบ้านครับ', 'Phŏhm yàak séu à-rai glàp bâan khráp', 'I - want - buy - something - return - home - polite particle', '', 'm10_28'),
(287, 10, 'He doesn''t want to go anywhere.', 'เขาไม่อยากไปไหนครับ', 'Khăo mâi yàak bpai năi khráp', 'he - not - want - go - anywhere - polite particle', '', 'm10_29'),
(288, 10, 'Is there somewhere we can play soccer?', 'มีที่ไหนที่เราสามารถเล่นฟุตบอลได้ครับ', 'Mii thîi năi thîi rao săa-mâat lên fút-baawn dâi khráp? ', 'is there - place - which - that - we - can - play - football - can - polite particle?', '', 'm10_30'),
(289, 11, 'I only have 10 baht.', 'มีแค่สิบบาทครับ', 'Mii khâae sìp bàat khráp', 'have - to the extent of - ten - baht - polite particle', '', 'm11_1'),
(290, 11, 'We don''t have any rice.', 'เราไม่มีข้าวครับ', 'Rao mâi mii khâao khráp', 'we - not - have - rice - polite particle', 'The word ''khâao'' means rice but can also be used to refer to food in general.', 'm11_2'),
(291, 11, 'Do you have any other colours?', 'มีสีอื่นอีกไหมครับ', 'Mii sĭi èuun èek mái khráp?', 'have - color - other - another - or not - polite particle?', '', 'm11_3'),
(292, 11, 'There''s no hot water', 'ไม่มีน้ำร้อนครับ', 'Mâi mii náam rórn khráp', 'not - there is - water - hot - polite particle', 'The word ''mii'' is used in ''there is'' type expressions.', 'm11_4'),
(293, 11, 'There is a temple behind the market', 'มีวัดอยู่หลังตลาดครับ', 'Mii wát yùu lăng dtà-làad khráp', 'there is - temple - situated - behind - market - polite particle', '', 'm11_5'),
(294, 11, 'He''s my friend.', 'เขาเป็นเพื่อนของผมครับ', 'Khăo bpen phêuuan kăwng phŏhm khráp', 'he - is - friend - belonging to - me - polite particle', 'The word ''bpen'' is the most common equivalent of the verb ''to be''. ', 'm11_6'),
(295, 11, 'My mother is kind', 'แม่เป็นคนใจดี', 'Mâe bpen khon jai dii', 'mother - is - person - heart - good', '', 'm11_7'),
(296, 11, 'Joom is his girlfriend.', 'จุ๋มเป็นแฟนเขาครับ', 'Jŏom bpen faen khăo khráp', 'Joom - is - girlfriend - him - polite particle', '', 'm11_8'),
(297, 11, 'Do you know how to swim?', 'คุณว่ายน้ำเป็นไหมครับ', 'Khun wâi náam bpen mái khráp?', 'you - swim - water - know how to - or not - polite particle?', 'We use ''bpen'' to express the idea of ''knowing how to do something''.', 'm11_9'),
(298, 11, 'To have the flu', 'เป็นไข้หวัด', 'Bpen khâi wàt', 'suffer from - fever - cold', 'We use ''bpen'' to mean ''suffer from'' in the case of health issues.', 'm11_10'),
(299, 11, 'Come and eat!', 'มากินข้าวกันครับ', 'Maa gin khâao gan khráp', 'come - eat - rice - together - polite particle', '', 'm11_11'),
(300, 11, 'The bus is coming.', 'รถเมล์มาแล้วครับ', 'Rót maeh maa láew khráp', 'vehicle - bus - come - already/now - polite particle', '', 'm11_12'),
(301, 11, 'Come round for a visit', 'มาเยี่ยม', 'Maa yîiam', 'come - visit', 'As well as meaning ''visit'', ''yîiam'' also means ''very good''.', 'm11_13'),
(302, 11, 'There''s a call coming.', 'มีสายโทรศัพท์เข้ามาครับ', 'Mii săai thoh-rá-sàp khâo maa khráp', 'there is - call - phone - enter - come - polite particle', 'As well as meaning ''come'' and ''go'', ''maa'' and ''bpai'' are used with some verbs to indicate the direction of an action.', 'm11_14'),
(303, 11, 'Are you ready to go?', 'คุณพร้อมที่จะไปหรือยังครับ', 'Khun phráawm thîi jà bpai rĕuu yang khráp?', 'you - ready - to - future marker - go - or - not yet - polite particle?', '', 'm11_15'),
(304, 11, 'Let''s go shopping.', 'ไปซื้อของกันครับ', 'Bpai séu kăwng gan khráp', 'go - buy - stuff - together - polite particle', '', 'm11_16'),
(305, 11, 'Go out/around for pleasure', 'ไปเที่ยว', 'Bpai thîaao', 'go - trip', '', 'm11_17'),
(306, 11, 'I''m going to the market.', 'ผมกำลังจะไปตลาดครับ', 'Phŏhm gamlang-jà bpai dtà-làad khráp', 'I - about to - go - market - polite particle', '', 'm11_18'),
(307, 11, 'He left already.', 'เขาไปแล้วครับ', 'Khăo bpai láew khráp', 'he - go - already - polite particle', '', 'm11_19'),
(308, 11, 'These things are too expensive', 'พวกนี้แพงเกินไป', 'Phûak níi phaaeng gern bpai', 'a group of - this - expensive - exceed - go', '', 'm11_20'),
(309, 11, 'I can come back tomorrow', 'ผมกลับมาพรุ่งนี้ได้ครับ', 'Phŏhm glùp maa phrôong-níi dâi khráp', 'I - return - come - tomorrow - can - polite particle', 'We use ''dai'' to talk about whether something is possible or not.', 'm11_21'),
(310, 11, 'Can I borrow your car?', 'ขอยืมรถคุณได้ไหม', 'Kŏr yeuum rót khun dâi mái?', 'request - borrow - car - you - can - or not?', '', 'm11_22'),
(311, 11, 'I can''t eat mushrooms at all', 'ผมกินเห็ดไม่ได้เลย', 'Phŏhm gin hèt mâi dâi leeuy', 'I - eat - mushroom - not - can - at all', 'Placing ''mâi dâi'' after a verb means that an action is not possible.', 'm11_23'),
(312, 11, 'I can''t lift it.', 'ผมยกไม่ได้ครับ', 'Phŏhm yóhk mâi dâi khráp', 'I - lift - not - can - polite particle', '', 'm11_24'),
(313, 11, 'He did not go to Laos', 'เขาไม่ได้ไปประเทศลาวครับ', 'Khăo mâi dâi bpai bprà-thêt Lao khráp', 'he - not - did - go - country - Laos - polite particle', 'Placing ''mâi dâi'' before a verb means that the action did not happen.', 'm11_25'),
(314, 11, 'Do you want to go shopping?  Yes, I want to go.', 'ไปช้อปปิ้งกันไหม  ไปไป', 'Bpai chop-pîng gan mái? Bpai bpai!', 'go - shopping - together - or not? go - go!', '', 'm11_26'),
(315, 11, 'Do you want to go to the market?  I''ll go if you want.', 'ไปตลาดกันไหม / ไปก็ได้', 'Bpai dtà-làad gan mái? Bpai gôr-dâi', 'go - market - together - or not? go - as you like', '', 'm11_27'),
(316, 11, 'Whatever you like', 'อะไรก็ได้ครับ', 'À-rai gôr-dâi khráp', 'anything - ok - polite particle', '', 'm11_28'),
(317, 11, 'You don''t need to bring anything.', 'คุณไม่ต้องเอาอะไรไปเลยครับ', 'Khun mâi dtôrng ao à-rai bpai leeuy khráp', 'you - not - need to - bring - anything - outgoing direction - at all - polite particle', 'The word ''dtôrng'' is similar to ''have to'' or ''must''', 'm11_29'),
(318, 11, 'I have to go to work.', 'ผมต้องไปทำงานแล้วครับ', 'Phŏhm dtôrng bpai tham-ngaan láew khráp', 'I  - have to - go - work - now - polite particle', '', 'm11_30'),
(319, 11, 'When do we have to finish?', 'เราต้องทำงานให้เสร็จเมื่อไหร่ครับ', 'Rao dtôrng tham-ngaan hâi sèt mêuua-rai khráp?', 'we - have to - work - give - finish - when - polite particle?', '', 'm11_31'),
(320, 11, 'You should go to the doctor.', 'คุณควรจะไปหาหมอนะครับ', 'Khun khuaan jà bpai hăa mŏr ná khráp ', 'you - should - future marker - go - visit - doctor - softening particle - polite particle ', '', 'm11_32'),
(321, 11, 'We should get there early.', 'เราควรจะไปถึงเร็วหน่อยนะครับ', 'Rao khuaan jà bpai thĕung reo nòy ná khráp', 'we - should - future marker - go - arrive - early - particle used to soften a request - softening particle - polite particle', '', 'm11_33'),
(322, 11, 'Do you want to eat out?', 'คุณอยากจะไปทานข้าวนอกบ้านไหมครับ', 'Khun yàak jà bpai thaan khâao nâawk bâan mái khráp?', 'you - want to - future marker - eat - rice - outside - home - or not - polite particle?', '', 'm11_34'),
(323, 11, 'He doesn''t want to play.', 'เขาไม่อยากเล่นครับ', 'Khăo mâi yàak lên khráp', 'he - not - want to - play - polite particle', '', 'm11_35'),
(324, 11, 'I gave the money to my mother.', 'ผมให้เงินแม่ไปแล้วครับ', 'Phŏhm hâi ngern mâe bpai láew khráp', 'I - give - money - mother - outgoing direction - past action marker - polite particle', '', 'm11_36'),
(325, 11, 'The boss let me go home early.', 'เจ้านายให้ผมกลับบ้านเร็วครับ', 'Jâo-naai hâi phŏhm glàp bâan reo khráp', 'boss - allow - me - return - home - early - polite particle', 'As well as meaning ''give'', ''hâi'' can also mean ''allow/let''', 'm11_37'),
(326, 11, 'Let me see it.', 'ขอผมดูหน่อยครับ', 'Kŏr phŏhm duu nòy khráp', 'request - me - see - particle used to soften a request - polite particle', '', 'm11_38'),
(327, 11, 'Please bring the book to school tomorrow.', 'ช่วยเอาหนังสือมาโรงเรียนพรุ่งนี้ด้วยนะครับ', 'Chûay ao năng-seuu maa rohng-rian phrûng-níi dûay ná khráp', 'help - bring - book - come - school - tomorrow - particle used at the end of a request - softening particle - polite particle', 'The word ''ao'' can mean ''take'', ''accept'' or ''bring''.', 'm11_39'),
(328, 11, 'I''ll have a green tea.', 'ผมเอาชาเขียวครับ', 'Phŏhm ao chaa kiăao khráp', 'I - take/want - tea - green - polite particle', '', 'm11_40'),
(329, 11, 'Who broke the glass?', 'ใครทำแก้วแตกครับ', 'Khrai tum gâaeo dtàaek khráp?', 'who - cause - drinking glass - break - polite particle', 'The word ''tum'' expresses the idea of causation. It is similar to ''do''.', 'm11_41'),
(330, 11, 'He works at the hospital.', 'เขาทำงานที่โรงพยาบาลครับ', 'Khăo tum-ngaan thîi rohng-phá-yaa-baan khráp', 'he - work - at - hospital - polite particle', '', 'm11_42'),
(331, 11, 'How do I use this thing?', 'อันนี้ใช้ยังไงครับ', 'An-níi chái yang-ngai khráp?', 'item - this - use - how - polite particle?', '', 'm11_43');