INSERT INTO `phrasesF` (`pid`, `subCategoryId`, `firstLanguage`, `secondLanguage`, `romanisation`, `literalTranslation`, `notes`, `fileName`) VALUES
(642, 26, 'Are you hungry? Very hungry.', 'คุณหิวไหมคะ หิวมากค่ะ', 'Khun hĭu mái khá? Hĭu mâak khâ.', 'you - hungry - or not - polite particle? hungry - very - polite particle', '', 'f26_1'),
(643, 26, 'Thirsty', 'หิวน้ำ', 'Hĭu náam', 'hungry (for) - water / liquid', '', 'f26_2'),
(644, 26, 'It''s very delicious.', 'อร่อยมากเลยค่ะ', 'À-ròi mâak leeuy khâ', 'tasty - very - exclamation - polite particle', '', 'f26_3'),
(645, 26, 'I''m full.', 'ฉันอิ่มแล้วค่ะ', 'Chăn ìm láew khâ', 'I - full - already - polite particle', '', 'f26_4'),
(646, 26, 'I''m not full yet.', 'ฉันยังไม่อิ่มค่ะ', 'Chăn yang mâi ìm khâ', 'I - still - not - full - polite particle', '', 'f26_5'),
(647, 26, 'Do you like Thai food? I like some Thai food.', 'คุณชอบอาหารไทยไหมคะ ฉันชอบบางอย่างค่ะ', 'Kun chôrp aa-hăan Thai mái khá? Chăn chôrp baang yàang khâ', 'you - like - food - Thai - or not - polite particle? I - like - some - type - polite particle', '', 'f26_7'),
(648, 26, 'Breakfast', 'อาหารเช้า', 'Aa-hăan cháao', 'food - morning', '', 'f26_8'),
(649, 26, 'Lunch', 'อาหารเที่ยง', 'Aa-hăan thîang', 'food - noon', '', 'f26_9'),
(650, 26, 'Dinner', 'อาหารเย็น', 'Aa-hăan yen', 'food - early evening', '', 'f26_10'),
(651, 26, 'Have a snack', 'กินเล่น', 'Gin lên', 'eat - play', '', 'f26_11'),
(652, 26, 'Restaurant', 'ร้านอาหาร', 'Ráan aa-hăan', 'shop - food', '', 'f26_12'),
(653, 26, 'Classifier for cups', 'ถ้วย', 'Thûay', '', '', 'f26_13'),
(654, 26, 'Dish / plate', 'จาน', 'Jaan', '', '', 'f26_14'),
(655, 26, 'Spoon', 'ช้อน', 'Cháawn', '', '', 'f26_15'),
(656, 26, 'Is it spicy? A little.', 'อันนี้เผ็ดไหมคะ นิดหน่อยค่ะ', 'An níi phèt mái khá? Nít-nòy khâ', 'item - this - spicy - or not - polite particle? a little bit - polite particle', '', 'f26_6'),
(657, 26, 'Is it sweet?', 'อันนี้หวานไหมคะ', 'An níi wăan mái khá?', 'item - this - sweet - or not - polite particle?', '', 'f26_16'),
(658, 26, 'Sour', 'เปรี้ยว', 'Bprîaao', '', '', 'f26_18'),
(659, 26, 'Salty', 'เค็ม', 'Khem', '', '', 'f26_19'),
(660, 26, 'Hot (temperature)', 'ร้อน', 'Rórn', '', '', 'f26_20'),
(661, 26, 'Cold (food, drink)', 'เย็น', 'Yen', '', '', 'f26_21'),
(662, 27, 'Is there a guesthouse nearby?', 'มีเกสต์เฮาส์แถวนี้ไหมคะ', 'Mii gàeht-háao thăaeo níi mái khá?', 'is there - guesthouse - area - this - or not - polite particle?', '', 'f27_1'),
(663, 27, 'I''m looking for a cheap hotel.', 'ฉันกำลังหาโรงแรมถูกๆอยู่ค่ะ', 'Chăn gamlang hăa rohng-raem tòok tòok yùu khâ', 'I - currently - look for - hotel - cheap - cheap - currently - polite particle', '', 'f27_2'),
(664, 27, 'Can you recommend a good place to stay?', 'ช่วยแนะนำที่พักดีๆหน่อยได้ไหมคะ', 'Chûay náe-nam thîi-phák dii dii nòy dâi mái khá?', 'help - recommend - accommodation - good - good - softening particle - can - or not?', '', 'f27_3'),
(665, 27, 'Are there any home stays around here?', 'มีโฮมสเตย์แถวนี้ไหมคะ', 'Mii hohm-sa-tay thăaeo níi mái khá?', 'is there - homestay - area - this - or not - polite particle?', '', 'f27_4'),
(666, 27, 'Do you have any rooms available?', 'มีห้องว่างไหมคะ', 'Mii hâawng wâang mái khá?', 'have - room - available - or not - polite particle?', '', 'f27_5'),
(667, 27, 'We booked online.', 'เราจองผ่านอินเตอร์เน็ตแล้วค่ะ', 'Rao jaawng phàan in-thuuhr-nét láew khâ ', 'we - book - via - internet - already - polite particle', '', 'f27_6'),
(668, 27, 'Single room', 'ห้องเดี่ยว', 'Hâawng dìaao', 'room - single', '', 'f27_7'),
(669, 27, 'Double room', 'ห้องคู่', 'Hâawng khûu', 'room - couple', '', 'f27_8'),
(670, 27, 'Twin room', 'ห้องสองเตียง', 'Hâawng săwng dtiiang', 'room - two - bed', '', 'f27_9'),
(671, 27, 'Dorm', 'หอพัก', 'Hăaw phák', 'hall - rest', '', 'f27_10'),
(672, 27, 'How many people?', 'กี่คนคะ', 'Gìi khon khá?', 'how many - people - polite particle', '', 'f27_11'),
(673, 27, 'How many nights?', 'กี่คืนคะ', 'Gìi kheuun khá?', 'how many - night - polite particle?', '', 'f27_12'),
(674, 27, 'Two people, one night.', 'สองคน หนึ่งคืน', 'Săawng khon nèung kheuun', 'two - people - one - night', '', 'f27_13'),
(675, 27, 'How much per night?', 'คืนละกี่บาทคะ', 'Kheuun lá gìi bàat khá?', 'night - each - how many - baht - polite particle?', '', 'f27_14'),
(676, 27, 'How much per week?', 'อาทิตย์ละกี่บาทคะ', 'Aa-thít lá gìi bàat khá?', 'week - each - how many - baht - polite particle?', '', 'f27_15'),
(677, 27, 'Room with a fan', 'ห้องมีพัดลม', 'Hâawng mii phát-lohm', 'room - have - fan', '', 'f27_16'),
(678, 27, 'Room with air conditioning', 'ห้องมีแอร์', 'Hâawng mii aae', 'room - have - air conditioning', '', 'f27_17'),
(679, 0, 'Do you want air conditioning?', 'คุณต้องการห้องที่มีแอร์ไหมคะ', 'Khun dtâwng-gaan hâwng thîi mii aae mái khá?', 'you - want - room - that - have - air conditioning - or not - polite particle?', '', 'f27_18'),
(680, 27, 'Do you have wifi?', 'คุณมีWIFIไหมคะ', 'Khun mii wifi mái khá?', 'you - have - wifi - or not - polite particle?', '', 'f27_19'),
(681, 27, 'Wifi password', 'รหัสWIFI', 'Rá-hàt wifi', 'code - wifi', '', 'f27_20'),
(682, 27, 'Is there hot water (showers)?', 'มีเครื่องทำน้ำอุ่นไหมคะ', 'Mii khrêuuang tham náam òon mái khá?', 'is there - machine - do - water - heat - or not - polite particle?', '', 'f27_21'),
(683, 27, 'Can I see the room?', 'ฉันขอดูห้องหน่อยได้ไหมคะ', 'Chăn kŏr doo hâawng nòy dâi mái khâ?', 'I - request - see - room - softening particle - can - or not - polite particle?', '', 'f27_22'),
(684, 27, 'Can I see another room?', 'ฉันขอดูห้องอื่นหน่อยได้ไหมคะ', 'Chăn kŏr doo hâawng èuun nòy dâi mái khâ?', 'I - request - see - room - another - softening particle - can - or not - polite particle?', '', 'f27_23'),
(685, 27, 'I would like a cleaner room.', 'ฉันขอห้องที่สะอาดกว่านี้ได้ไหมคะ', 'Chăn kŏr hâawng thîi sà-àat gwàa níi dâi mái khâ?', 'I - request - room - that - clean - more than - this - can - or not - polite particle?', '', 'f27_24'),
(686, 27, 'Bigger', 'ใหญ่กว่า', 'Yài gwàa', 'big - more than', '', 'f27_25'),
(687, 27, 'Quiter', 'เงียบกว่า', 'Ngîiap gwàa', 'quiet - more than', '', 'f27_26'),
(688, 27, 'Cheaper', 'ถูกกว่า', 'Thùuk gwàa', 'cheap - more than', '', 'f27_27'),
(689, 27, 'Room with a bathroom', 'ห้องที่มีห้องน้ำ', 'Hâawng thîi mii hâawng-náam ', 'room - that - have - bathroom', '', 'f27_28'),
(690, 27, 'This room smells like smoke.', 'ห้องนี้มีกลิ่นควัน', 'Hâawng níi mii glìn khwan', 'room - this - have - smell - smoke', '', 'f27_29'),
(691, 27, 'Can I open the window?', 'ฉันเปิดหน้าต่างได้ไหมคะ', 'Chăn bpèrt nâa-dtàang dâi mái khá?', 'I - open - window - can - or not - polite particle?', '', 'f27_30'),
(692, 27, 'Can I move to another room?', 'ฉันขอย้ายไปห้องอื่นได้ไหมคะ', 'Chăn kŏr yáai bpai hâawng èuun dâi mái khá?', 'I - request - transfer - go - room - another - can - or not - polite particle', '', 'f27_31'),
(693, 27, 'Can I have another blanket?', 'ขอผ้าห่มเพิ่มได้ไหมคะ', 'Kŏr phâa-hòhm phêerm dâi mái khá?', 'request - blanket - add - can - or not - polite particle?', '', 'f27_32'),
(694, 27, 'Can we have an extra bed?', 'ขอเตียงเสริมได้ไหมคะ', 'Kŏr dtiiang sĕerm dâi mái khá?', 'request - bed - add - can - or not - polite particle?', '', 'f27_33'),
(695, 27, 'I''ll take it.', 'ฉันเอาอันนี้ค่ะ', 'Chăn ao an-níi khâ', 'I - take - this one - polite particle', '', 'f27_34'),
(696, 27, 'I want to go and look at some other places.', 'ฉันจะไปหาที่อื่น', 'Chăn jà bpai hăa thîi èuun', 'I - want to - go - look for - place - another', '', 'f27_35'),
(697, 27, 'I''d like to stay another night.', 'ฉันจะอยู่อีกคืน', 'Chăn jà yùu èek kheuun', 'I - want to - stay - another - night', '', 'f27_36'),
(698, 27, 'Can I leave my bags here?', 'ฉันขอฝากกระเป๋าไว้ที่นี้ได้ไหมคะ', 'Chăn kŏr fàak grà-bpăo wái thîi-níi dâi mái khá?', 'I - request - leave - bag - for future - here - can - or not - polite particle?', 'One usage of the word ''wái'' is to imply that something will happen in the future or is being done for the future. ', 'f27_37'),
(699, 27, 'Where can I change money?', 'ฉันจะแลกเงินได้ที่ไหนคะ', 'Chăn jà lâek ngern dâi thîi năi khá?', 'I - future marker - exchange - money - can - at (place) - which - polite particle?', '', 'f27_38'),
(700, 27, 'Is there a laundry service?', 'มีบริการซักรีดไหมคะ', 'Mii baaw-rí-gaan sák rêet mái khá', 'is there - service - wash (clothes) - iron - or not - polite particle?', '', 'f27_39'),
(701, 27, 'I left my key in the room.', 'ฉันลืมกุญแจไว้ในห้องค่ะ', 'Chăn leuum goon-jaae wái nai hâawng khâ', 'I - forget - key - put - in - room - polite particle', '', 'f27_40'),
(702, 28, 'Car', 'รถยนต์', 'Rót yohn', 'vehicle - motorised', '', 'f28_1'),
(703, 28, 'Drive', 'ขับ', 'Khàp', '', '', 'f28_2'),
(704, 28, 'Bicycle', 'จักรยาน', 'Jàk-grà-yaan', '', 'Usually pronouned ''jàk-gà-yaan''.', 'f28_3'),
(705, 28, 'Go by bicycle', 'ไปโดยจักรยาน', 'Bpai dooy jàk-grà-yaan', 'go - by means of - bicycle', '', 'f28_4'),
(706, 28, 'Walk', 'เดิน', 'Deun', '', '', 'f28_5'),
(707, 28, 'Taxi', 'แท็กซี่', 'Tháek-sîi', '', '', 'f28_6'),
(708, 28, 'How much to go to Victory Monument?', 'ไปอนุสาวรีย์ชัยสมรภูมิกี่บาทคะ', 'Bpai à-noo-săa-wá-ree chai sà-măaw-rá-phuum gìi bàat khá?', 'go - monument - victory - battlefield - how many - baht - polite particle?', '', 'f28_7'),
(709, 28, 'Take me to Hua Lumphong station, please.', 'ช่วยพาฉันไปสถานีหัวลำโพงหน่อยค่ะ', 'Chûay phaa chăn bpai sà-thăa-nii hŭaa lam-phong nòy khâ', 'help - take - me - go - station - Hua Lumphong - softening particle - polite particle', '', 'f28_8'),
(710, 28, 'Please put the meter on.', 'ช่วยกดมิเตอร์ด้วยคะ', 'Chûay gòht míi-dteu dûay khâ', 'help - press - meter - request particle  - polite particle', '', 'f28_9'),
(711, 28, 'How long will it take?', 'ใช้เวลานานแค่ไหนคะ', 'Chái waeh-laa naan khâe năi khá?', 'use - time - long time - to the extent of - which - polite particle?', '', 'f28_10'),
(712, 28, 'Stop here.', 'หยุดตรงนี้ค่ะ', 'Yòot dtrohng-níi khâ', 'stop - right here - polite particle', '', 'f28_11'),
(713, 28, 'I''ll be back in a moment.', 'เดี๋ยวมาค่ะ / แป๊บหนึ่งค่ะ', 'Dĭaao maa khâ / Bpáaep nèung khâ', 'a moment - come - polite particle / for a moment - one - polite particle', '', 'f28_12'),
(714, 28, 'My friend is coming.', 'เพื่อนฉันกำลังจะมาค่ะ', 'Phêuuan chăn gamlang-jà maa khâ ', 'friend - I - about to - come - polite particle', '', 'f28_13'),
(715, 28, 'Bus', 'รถเมล์', 'Rót-maey', '', '', 'f28_14'),
(716, 28, 'Two-row minibus', 'รถสองแถว', 'Rót săawng thăew', 'vehicle - two - row', '', 'f28_15'),
(717, 28, 'Coach', 'รถทัวร์', 'Rót thuaa', 'vehicle - tour', '', 'f28_16'),
(718, 28, 'Bus station', 'สถานีรถประจำทาง', 'Sà-thăa-nii rót bprà-jam thaang', 'station - vehicle - regular - way', '', 'f28_17'),
(719, 28, 'Bus stop', 'ป้ายรถเมล์', 'Bpâai rót-maey', 'vehicle stop - bus', '', 'f28_18'),
(720, 28, 'Bus number', 'สาย', 'Săai', '', '', 'f28_19'),
(721, 28, 'Go by bus', 'ไปโดยรถเมล์', 'Bpai dooy rót-maey', 'go - by means of - bus', '', 'f28_20'),
(722, 28, 'Take bus number 51.', 'ขึ้นรถเมล์สายห้าสิบเอ็ดค่ะ', 'Khêun rót-maey săai hâa-sìp-èt khâ', 'board - bus - number - fifty one - polite particle', '', 'f28_21'),
(723, 28, 'Ticket', 'ตั๋ว', 'Dtŭa', '', '', 'f28_22'),
(724, 28, 'One way', 'เที่ยวเดียว', 'Thîaao diaao', 'trip - single', '', 'f28_23'),
(725, 28, 'Return', 'ไป-กลับ', 'Bpai glàp', 'go - return', '', 'f28_24'),
(726, 28, 'Where can I buy a ticket?', 'ฉันซื้อตั๋วได้ที่ไหนคะ', 'Chăn séuu dtŭa dâi thîi năi khá?', 'I - buy - ticket - can - at place - which - polite particle?', '', 'f28_25'),
(727, 28, 'Do you go to Nonthaburi?', 'คุณไปนนทบุรีหรือคะ', 'Khun bpai Nohn-thá-bòo-ree rĕuu khá?', 'you - go - Nonthaburi - right - polite particle?', '', 'f28_26'),
(728, 28, 'What time will the next bus to Satun leave?', 'รถเมล์ไปสตูลคันต่อไปออกกี่โมงคะ', 'Rót-maey bpai Sà-dtuun khan dtàaw-bpai àawk gìi mohng khá?', 'bus - go - Satun - classifier - next - exit - how many - hour - polite particle?', '', 'f28_27'),
(729, 28, 'Does it stop for dinner?', 'รถจะหยุดสำหรับอาหารเย็นไหมคะ', 'Rót jà yòot săm-ràp aa-hăan-yen mái khá?', 'vehicle - future marker - stop - for the purpose of - dinner - or not - polite particle?', '', 'f28_28'),
(730, 28, 'How much will it cost to bring my bicycle?', 'เอารถจักรยานขึ้นคิดเงินเท่าไหร่คะ', 'Ao rót jàk-gàa-yaan khêun khít ngern thâo rai khá?', 'bring - vehicle - bicycle - board - calculate - money - equal to - what - polite particle?', '', 'f28_29'),
(731, 28, 'It hasn''t come yet.', 'มันยังไม่มาค่ะ', 'Mun yang mâi maa khâ', 'it - still - not - come - polite particle', '', 'f28_30'),
(732, 28, 'It''s going to arrive late.', 'มันจะมาสายค่ะ', 'Mun jà maa săai khâ', 'it - future marker - come - late - polite particle', '', 'f28_31'),
(733, 29, 'Boat', 'เรือ', 'Reuua', '', '', 'f29_1'),
(734, 29, 'Ferry', 'เรือเฟอร์รี่', 'Reuua fuh-rîi', 'boat - ferry', '', 'f29_2'),
(735, 29, 'Go by boat', 'ไปทางเรือ', 'Bpai thaang reuua', 'go - way - boat', '', 'f29_3'),
(736, 29, 'Book a seat on the boat', 'จองตั๋วขึ้นเรือ', 'Jaawng dtŭa khêun reuua', 'book - ticket - board - boat', '', 'f29_4'),
(737, 29, 'Jetty/harbor', 'ท่าเรือ', 'Thâa reuua', 'pier - boat', '', 'f29_5'),
(738, 29, 'Train', 'รถไฟ', 'Rót fai', 'vehicle - fire', '', 'f29_6'),
(739, 29, 'Sky train', 'รถไฟฟ้า', 'Rót-fai fáa', 'train - sky', '', 'f29_7'),
(740, 29, 'Train station', 'สถานีรถไฟ', 'Sà-thăa-nii rót-fai', 'station - train', '', 'f29_8'),
(741, 29, 'Is there a BTS station near here?', 'มีสถานีรถไฟฟ้าแถวนี้ไหมคะ', 'Mii sà-thăa-nii rót-fai fáa thăaeo níi mái khá?', 'is there - station - train - sky - area - this - or not - polite particle?', '', 'f29_9'),
(742, 29, 'Platform', 'ชานชาลา', 'Chaan-chaa-làa', '', '', 'f29_10'),
(743, 29, 'Carriage', 'ตู้โดยสาร', 'Dtûu dooy-săan', 'train compartment - travel as a passenger', '', 'f29_11'),
(744, 29, 'First class sleeper', 'เตียงนอนชั้นหนึ่ง', 'Dtiiang norn chán nèung', 'berth - sleep - class - one', '', 'f29_12'),
(745, 29, 'Second class sleeper', 'เตียงนอนชั้นสอง', 'Dtiiang norn chán săwng', 'berth - sleep - class -two', '', 'f29_13'),
(746, 29, 'Second class seat', 'ที่นั่งชั้นสอง', 'Thîi nâng chán săwng', 'place - sit - class - two', '', 'f29_14'),
(747, 29, 'Upper bunk', 'เตียงบน', 'Dtiiang bohn', 'berth - top', '', 'f29_15'),
(748, 29, 'Lower bunk', 'เตียงล่าง', 'Dtiiang lâang', 'berth - below', '', 'f29_16'),
(749, 29, 'Get on the train', 'ขึ้นรถไฟ', 'Khêun rót-fai', 'ascend - train', '', 'f29_17'),
(750, 29, 'Get off at Siam square', 'ลงที่สยามสแคว', 'Long thîi Sà-yăam Sà-khwaae', 'descend - at - Siam Square', '', 'f29_18'),
(751, 29, 'Which platform for the train to Chiang Mai?', 'รถไฟไปเชียงใหม่ขึ้นชานชาลาไหนคะ', 'Rót-fai bpai Chiiang Mài khêun chaan-chaa-làa năi khá?', 'train - go - Chiang Mai - get on - platform - which - polite particle?', '', 'f29_19'),
(752, 29, 'When is the next train to Ubon Ratchatani?', 'รถไฟขบวนต่อไปที่จะไปอุบลฯจะออกกี่โมงคะ', 'Rót-fai khà-buaan dtàaw-bpai thîi jà bpai Òo-bohn (Râat-chá-thaa-nee), jà àawk gìi mohng khá?', 'train - classifier - next - that - future marker - go - Ubon (Ratchatani) - future marker - leave - how many - hour - polite particle?', 'It is common to use only the first word of certain major cities.', 'f29_20'),
(753, 29, 'What time does it get to Sisaket?', 'ถึงศรีสะเกษกี่โมงคะ', 'Thĕung Sii-sàa-gèt gìi mohng khá?', 'arrive - Sisaket - how many - hour - polite particle?', '', 'f29_21'),
(754, 29, 'How long does it take?', 'ใช้เวลานานแค่ไหน', 'Chái waeh-laa naan khâae năi?', 'use - time - long time - to the extent of - which?', '', 'f29_22'),
(755, 29, 'Is there a luggage carriage?', 'มีตู้เก็บสัมภาระไหมคะ', 'Mii dtûu gèp săm-phaa-ráa mái khá?', 'is there - carriage - store - luggage - or not - polite particle?', '', 'f29_23'),
(756, 29, 'I want to go to Mo Chit station.', 'ฉันจะไปสถานีหมอชิตค่ะ', 'Chăn jà bpai sa-thăa-nii măaw-chít khâ', 'I - want to - go - station - mo chit - polite particle', '', 'f29_24'),
(757, 29, 'What station is this?', 'นี้สถานีอะไรคะ', 'Níi sà-thăa-nii à-rai khá?', 'this - station - what - polite particle?.', '', 'f29_25'),
(758, 29, 'Airplane', 'เครื่องบิน', 'Khrêuang bin', 'machine - fly', '', 'f29_26'),
(759, 29, 'Airport', 'สนามบิน', 'Sà-năam bin', 'field - fly', '', 'f29_27'),
(760, 29, 'Suvarnabhumi airport', 'สนามบินสุวรรณภูมิ', 'Sà-năam-bin Sòo-wan-ná-phum', 'airport - Suvarnabhumi', '', 'f29_28'),
(761, 29, 'Terminal', 'อาคาร', 'Aa-khaan', 'building', '', 'f29_29'),
(762, 29, 'Arrival', 'ขาเข้า', 'Khăa khâo', 'journey - enter', '', 'f29_30'),
(763, 29, 'Departure', 'ขาออก', 'Khăa àawk', 'journey - exit', '', 'f29_31'),
(764, 29, 'Gate 21', 'ประตูยี่สิบเอ็ด', 'Bprà-dtuu yîi-sìp-èt', 'gate - twenty one', '', 'f29_32'),
(765, 29, 'What time is your flight?', 'เที่ยวบินคุณกี่โมงคะ', 'Thîaao bin khun gìi mohng khá?', 'trip - fly - you - how many - hour - polite particle?', '', 'f29_33'),
(766, 30, 'Place of interest, place to visit', 'ที่เที่ยว', 'Thîi thîaao', 'place - trip', '', 'f30_1'),
(767, 30, 'Excuse me, where is the supermarket?''', 'ขอโทษนะคะ ซุปเปอร์มาเก็ตอยู่ไหนแถวไหนคะ', 'Kŏr-thôt ná khá, sóop-bpuuhr-maa-gèt yùu thăaeo năi khá?', 'excuse me - softening particle - polite particle - supermarket - situated - area - which - polite particle?', '', 'f30_2'),
(768, 30, 'Is there a post office around here?', 'มีไปรษณีย์แถวนี้ไหมคะ', 'Mii bprai-sà-nee thăaeo níi mái khá?', 'is there - post office - area - this - or not - polite particle?', '', 'f30_3'),
(769, 30, 'Which way to Sukhothai?', 'ไปสุโขทัยทางไหนคะ', 'Bpai Sòo-khŏh-thai thaang năi khá?', 'go - Sukhothai - way - which - polite particle?', '', 'f30_4'),
(770, 30, 'I''m looking for the ferry terminal', 'ฉันกำลังหาท่าเรืออยู่ค่ะ', 'Chăn gamlang hăa thâa-reuua yùu khá', 'I - currently - look for - jetty - currently - polite particle', '', 'f30_5'),
(771, 30, 'Can you show me on the map?', 'ชี้ให้ฉันดูบนแผนที่ได้ไหมคะ', 'Chée hâi chăn doo bon phăaen-thîi dâi mái khá?', 'indicate place - give - me - see - on - map - can - or not - polite particle?', 'The verbs ''hâi .... doo'' together mean ''show''.', 'f30_6'),
(772, 30, 'Go straight', 'ตรงไป', 'Dtrohng bpai', 'straight - go', '', 'f30_7'),
(773, 30, 'Go to the end of the road', 'ไปสุดถนน', 'Bpai sòot thà-nŏn', 'go - end - road', '', 'f30_8'),
(774, 30, 'Turn right', 'เลี้ยวขวา', 'Liáao khwăa', 'turn - right', '', 'f30_9'),
(775, 30, 'Turn left', 'เลี้ยวซ้าย', 'Liáao sáai', 'turn - left', '', 'f30_11'),
(776, 30, 'Turn left on Sukhumvit Road', 'เลี้ยวซ้ายที่ถนนสุขุมวิท', 'Liáao sáai thîi thà-nŏn sòo-khŏom-wít', 'turn - left - at - road - Sukhumvit', '', 'f30_12'),
(777, 30, 'Go through the intersection', 'ผ่านแยกไป', 'Phàan yâek bpai', 'pass by - intersection - go', '', 'f30_13'),
(778, 30, 'Go until you see the petrol station, then turn right', 'ตรงไปจนถึงปั๊มน้ำมันแล้วเลี้ยวขวา', 'Dtrohng bpai john thĕung bpám náam-man láew liáao khwăa', 'straight - go - until - arrive - pump - petrol - next - turn - right', '', 'f30_14'),
(779, 30, 'Go straight ahead, turn left at the traffic lights.', 'ตรงไป เลี้ยวซ้ายหลังผ่านไฟจราจร', 'Dtrohng bpai, liáao sáai lăng phàan fai jà-raa-jawn', 'straight - go, turn - left - behind - pass by - light - traffic', '', 'f30_15'),
(780, 30, 'Turn right after the temple.', 'เลี้ยวขวาหลังผ่านวัด', 'Liáao khwăa lăng phàan wát', 'turn - right - behind - pass by - temple', '', 'f30_16'),
(781, 30, 'Take sawng-thaew number 3', 'นั่งสองแถวเบอร์สาม', 'Nâng săawng thăew ber săam', 'sit - two - rows - number - three', '', 'f30_17'),
(782, 30, 'It''s over there.', 'อยู่ทางโน้น', 'Yùu thaang nóhn', 'situated - way - there', '', 'f30_18'),
(783, 30, 'Go back that way.', 'กลับไปทางโน้น', 'Glàp bpai thaang nóhn', 'return - go - way - there', '', 'f30_19'),
(784, 30, 'On the left', 'อยู่ด้านซ้าย', 'Yùu dtâan sáai', 'situated - side - left', '', 'f30_20'),
(785, 30, 'In front of', 'ข้างหน้า', 'Khâang nâa', 'in the direction of - in front of', '', 'f30_21'),
(786, 30, 'Behind', 'หลัง', 'Lăng', '', '', 'f30_22'),
(787, 30, 'Next to', 'ถัดจาก', 'Thàt jàak', 'next - from', '', 'f30_23'),
(788, 30, 'On the corner', 'อยู่ตรงหัวมุม', 'Yùu dtrohng hŭa-moom', 'situated - at - corner', '', 'f30_24'),
(789, 30, 'Opposite', 'ตรงข้าม', 'Dtrohng khâam', 'at - opposite', '', 'f30_25'),
(790, 30, 'Close', 'ใกล้', 'Glâi', '', '', 'f30_26'),
(791, 30, 'Far', 'ไกล', 'Glai', '', '', 'f30_27'),
(792, 30, 'Lane', 'ซอย', 'Soi', '', '', 'f30_28'),
(793, 30, 'Road', 'ถนน', 'Thà-nŏn', '', '', 'f30_29'),
(794, 30, 'Highway', 'ทางหลวง', 'Thaang lŭaang', 'way - royal', '', 'f30_30'),
(795, 30, 'Village', 'หมู่บ้าน', 'Mùu-bâan', '', '', 'f30_31'),
(796, 30, 'City', 'เมือง', 'Meuuang', '', '', 'f30_32'),
(797, 30, 'Area', 'พื้นที่', 'Phéuun thîi', '', '', 'f30_33'),
(798, 30, 'Province', 'จังหวัด', 'Jang-wàt', '', '', 'f30_34'),
(799, 30, 'What road is this?', 'นี่ถนนอะไรคะ', 'Nîi thà-nŏn à-rai khá?', 'this - road - what - polite particle?', '', 'f30_35'),
(800, 30, 'What village is this?', 'นี่หมู่บ้านอะไรคะ', 'Nîi mùu-bâan à-rai khá?', 'this - village - what - polite particle?', '', 'f30_36'),
(801, 30, 'How far is it?', 'ไกลแค่ไหนคะ', 'Glai khâae năi khá?', 'far - to the extent of - which - polite particle?', '', 'f30_37'),
(802, 30, 'Upstairs', 'ข้างบน', 'Khâang bon', 'in the direction of - above', '', 'f30_38'),
(803, 30, 'Downstairs', 'ข้างล่าง', 'Khâang lâang', 'in the direction of - below', '', 'f30_39'),
(804, 30, 'Entrance', 'ทางเข้า', 'Thaang khâo', 'way - enter', '', 'f30_40'),
(805, 30, 'Exit', 'ทางออก', 'Thaang àawk', 'way - exit', '', 'f30_41'),
(806, 30, 'It''s a ten minute walk.', 'ใช้เวลาเดินสิบนาที', 'Chái waeh-laa deun sìp naa-thii', 'use - time - walk - ten - minute', '', 'f30_42'),
(807, 30, 'It''s possible to walk.', 'สามารถเดินได้', 'Săa-mâat deun dâi', 'capable - walk - can', '', 'f30_43'),
(808, 30, 'Traffic jam', 'รถติด', 'Rót dtìt', 'vehicle - stuck', '', 'f30_44'),
(809, 30, 'Where can I rent a motorbike?', 'เช่ามอเตอร์ไซค์ได้ที่ไหน', 'Châo mor-dtuhr-sai dâi thîi năi?', 'rent - motorbike - can - place - where?', '', 'f30_45'),
(810, 31, 'Beach', 'ชายหาด', 'Chai hàat', 'edge - beach', '', 'f31_1'),
(811, 31, 'Sea', 'ทะเล', 'Thá-laeh', '', '', 'f31_2'),
(812, 31, 'Mountain, hill', 'ภูเขา', 'Phuu khăo', '', '', 'f31_3'),
(813, 31, 'Hill', 'เนินเขา', 'Neern khăo', '', '', 'f31_4'),
(814, 31, 'Forest/jungle', 'ป่า', 'Bpàa', '', '', 'f31_5'),
(815, 31, 'Trail', 'ทางดิน', 'Thaang din', 'way - dirt', '', 'f31_6'),
(816, 31, 'Rice field', 'นาข้าว', 'Naa khâao', 'rice paddy - rice', '', 'f31_7'),
(817, 31, 'Cave', 'ถ้ำ ', 'Thâm', '', '', 'f31_8'),
(818, 31, 'River', 'แม่น้ำ', 'Mâe náam', 'mother - water', '', 'f31_9'),
(819, 31, 'River mouth', 'ปากเเม่น้ำ', 'Bpàak mâe-náam', 'mouth - river', '', 'f31_10'),
(820, 31, 'Lake', 'ทะเลสาบ', 'Thá-laeh sàap', 'sea - lake', '', 'f31_11'),
(821, 31, 'Waterfall', 'น้ำตก', 'Náam dtòk', 'water - fall', '', 'f31_12'),
(822, 31, 'Fishing', 'ตกปลา', 'Dtòk bplaa', 'to fish - fish', '', 'f31_13'),
(823, 31, 'Scuba diving, diving', 'ดำน้ำ', 'Dam náam', 'dive, submerge - water', '', 'f31_14'),
(824, 31, 'Hiking - mountain', 'ปีนเขา', 'Bpeen khăo', 'climb - hill', '', 'f31_15'),
(825, 31, 'Hiking - forest', 'เดินป่า', 'Deun bpàa', 'walk - forest', '', 'f31_17'),
(826, 31, 'Guide', 'ไกด์', 'Gái', '', '', 'f31_18'),
(827, 31, 'Mosquito net', 'มุ้ง', 'Móong', '', '', 'f31_19'),
(828, 31, 'Cycling', 'ปั่นจักรยาน', 'Bpàn jàk-graa-yaan', 'spin - bicycle', '', 'f31_16'),
(829, 32, 'Family', 'ครอบครัว', 'Khrâawp khruaa', '', '', 'f32_1'),
(830, 32, 'Mother', 'แม่', 'Mâe', '', '', 'f32_2'),
(831, 32, 'Father', 'พ่อ', 'Phâaw', '', '', 'f32_3'),
(832, 32, 'Parents', 'พ่อแม่', 'Phâaw-mâe', '', '', 'f32_4'),
(833, 32, 'Son', 'ลูกชาย', 'Lûuk chaai', 'child - male', '', 'f32_5'),
(834, 32, 'Daughter', 'ลูกสาว', 'Lûuk săo', 'child - female', '', 'f32_6'),
(835, 32, 'Siblings', 'พี่น้อง', 'Phîi náwng', 'older sibling - younger sibling', 'These kinship terms are also commonly used to refer to others outside the scope of the family, usually preceding the name of the person.', 'f32_7'),
(836, 32, 'Older sister', 'พี่สาว', 'Phîi săo', 'older sibling - female', '', 'f32_8'),
(837, 32, 'Older brother', 'พี่ชาย', 'Phîi chaai', 'older sibling - male', '', 'f32_9'),
(838, 32, 'Younger sister', 'น้องสาว', 'Náwng săo', 'younger sibling - female', '', 'f32_10'),
(839, 32, 'Younger brother', 'น้องชาย', 'Náwng chaai', 'younger sibling - male', '', 'f32_11'),
(840, 32, 'Husband (formal)', 'สามี', 'Săa-mii', '', '', 'f32_12'),
(841, 32, 'Husband (informal)', 'ผัว', 'Phŭa', '', '', 'f32_13'),
(842, 32, 'Wife (formal)', 'ภรรยา', 'Phan-rá-yaa', '', '', 'f32_14'),
(843, 32, 'Wife (informal)', 'เมีย', 'Mia', '', '', 'f32_15'),
(844, 32, 'Paternal grandfather', 'ปู่', 'Bpùu', '', '', 'f32_16'),
(845, 32, 'Paternal grandmother', 'ย่า', 'Yâa', '', '', 'f32_17'),
(846, 32, 'Maternal grandfather', 'ตา', 'Dtaa', '', '', 'f32_18'),
(847, 32, 'Maternal grandmother', 'ยาย', 'Yaai', '', '', 'f32_19'),
(848, 32, 'Elder sister of parent', 'ป้า', 'Bpâa', '', '', 'f32_20'),
(849, 32, 'Elder brother of parent', 'ลุง', 'Loong', '', '', 'f32_21'),
(850, 32, 'Younger sister/brother of mother', 'น้า', 'Náa', '', '', 'f32_22'),
(851, 32, 'Elder sister/brother of father', 'อา', 'Aa', '', '', 'f32_23'),
(852, 32, 'How many children do you have?', 'คุณมีลูกกี่คนคะ', 'Khun mii lûuk gìi khon khá?', 'you - have - child - how many - person classifier - polite particle?', '', 'f32_24'),
(853, 32, 'One son and two daughters.', 'ลูกชายหนึ่งคนและลูกสาวสองคน', 'Lûuk chaai nèung khon láe lûuk săo săawng khon', 'son - one - person classifier - daughter - two - person classifier', '', 'f32_25'),
(854, 33, 'Female', 'หญิง', 'Yĭng', '', '', 'f33_1'),
(855, 33, 'Male', 'ชาย', 'Chaai', '', '', 'f33_2'),
(856, 33, 'Woman', 'ผู้หญิง', 'Phûu yĭng', 'person - female', '', 'f33_4'),
(857, 33, 'Man', 'ผู้ชาย', 'Phûu chaai', 'person - male', '', 'f33_3'),
(858, 33, 'Boy', 'เด็กชาย', 'Dèk phûu chaai', 'child - person - male', '', 'f33_32'),
(859, 33, 'Girl', 'เด็กหญิง', 'Dèk phûu yĭng', 'child - person - female', '', 'f33_33'),
(860, 33, 'Friend', 'เพื่อน', 'Phêuan', '', '', 'f33_5'),
(861, 33, 'Neighbour', 'เพื่อนบ้าน', 'Phêuan bâan', 'friend - house', '', 'f33_11'),
(862, 33, 'Boyfriend/girlfriend', 'แฟน', 'Faen', '', '', 'f33_6'),
(863, 33, 'Sweetheart', 'ที่รัก', 'Thîi rák', 'that - love', '', 'f33_7'),
(864, 33, 'Female friend', 'เพื่อนหญิง', 'Phêuan yĭng', 'friend - female', '', 'f33_8'),
(865, 33, 'Male friend', 'เพื่อนชาย', 'Phêuan chaai', 'friend - male', '', 'f33_9'),
(866, 33, 'Foreigner', 'ชาวต่างชาติ', 'Chaao dtàang châat', 'people - different - nation', '', 'f33_10'),
(867, 33, 'Caucasian foreigner', 'ฝรั่ง', 'Fà-ràng', '', 'The word ''fà-ràng'' is usually used to refer to white foreigners and ''chaao dtàang châat'' means foreigner in general', 'f33_12'),
(868, 33, 'Professional', 'มืออาชีพ', 'Meuu aa-chêep', 'hand - occupation', '', 'f33_13'),
(869, 33, 'University student', 'นักศึกษามหาวิทยาลัย', 'Nák sèuk-săa má-hăa-wít-thá-yaa-lai', 'person who - study (above school) - university', '', 'f33_14'),
(870, 33, 'School student', 'นักเรียน', 'Nák rian', 'person who - study (school level)', '', 'f33_15'),
(871, 33, 'Teacher', 'ครู', 'Khruu', '', '', 'f33_16'),
(872, 33, 'Business person', 'นักธุรกิจ', 'Nák thóo-ráa-gìt', 'person who - business', '', 'f33_17'),
(873, 33, 'Tourist', 'นักท่องเที่ยว', 'Nák thâawng thîaao', 'person who - wander - trip', '', 'f33_18'),
(874, 33, 'Doctor', 'หมอ', 'Mŏr', '', '', 'f33_19'),
(875, 33, 'Nurse', 'พยาบาล', 'Phá-yaa-baan', '', '', 'f33_20'),
(876, 33, 'Rice farmer', 'ชาวนา', 'Chaao naa', 'person - rice farm', '', 'f33_21'),
(877, 33, 'Vegetable farmer', 'ชาวไร่', 'Chaao râi', 'person - farm', '', 'f33_22'),
(878, 33, 'Mechanic', 'ช่างเครื่อง', 'Châng krêuuang', 'mechanic / engineer - machine', '', 'f33_23'),
(879, 33, 'Taxi driver', 'คนขับแท็กซี่', 'Khon khàp tháek-sîi', 'person classifier - drive - taxi', '', 'f33_24'),
(880, 33, 'Fisherman', 'ชาวประมง', 'Chaao bprà-mohng', 'person - to fish', '', 'f33_25'),
(881, 33, 'Police person', 'ตำรวจ', 'Dtam rùat', '', '', 'f33_26'),
(882, 33, 'Politician', 'นักการเมือง', 'Nák gaan-meuuang', 'professional - politics', '', 'f33_27'),
(883, 33, 'Sportsperson, athlete', 'นักกีฬา', 'Nák gi-laa', 'professional - sport', '', 'f33_28'),
(884, 33, 'Musician', 'นักดนตรี', 'Nák don-dtrii', 'professional - music', '', 'f33_29'),
(885, 33, 'Chef/cook', 'พ่อครัว / กุ๊กทำอาหาร', 'Phâaw khruaa / Góok tham aa-hăan', 'father - kitchen / cook - make - food', '', 'f33_30'),
(886, 33, 'Labourer', 'กรรมกร', 'Gam-má-gaawn', '', '', 'f33_31'),
(887, 34, 'Beautiful', 'สวย', 'Sŭay', '', '', 'f34_1'),
(888, 34, 'Handsome', 'หล่อ', 'Làw', '', '', 'f34_2'),
(889, 34, 'Thin', 'ผอม', 'Phăwm', '', '', 'f34_3'),
(890, 34, 'Fat, big', 'อ้วน', 'Oûan', '', '', 'f34_4'),
(891, 34, 'Tall', 'สูง', 'Sŏung', '', '', 'f34_5'),
(892, 34, 'Short', 'เตี้ย', 'Dtîia', '', '', 'f34_6'),
(893, 34, 'Cute', 'น่ารัก', 'Nâa-rák', 'loveable', '', 'f34_7'),
(894, 34, 'Lazy', 'ขี้เกียจ', 'Khîi-kìat', '', '', 'f34_8'),
(895, 34, 'Hardworking', 'ขยัน', 'Khà-yăn', '', '', 'f34_9'),
(896, 34, 'Shy', 'ขี้อาย', 'Khîi-ai', '', '', 'f34_10'),
(897, 34, 'Friendly', 'เป็นมิตร', 'Bpen mít', 'is - friend', '', 'f34_11'),
(898, 34, 'Naughty', 'ซน', 'Sohn', '', '', 'f34_12'),
(899, 34, 'Kindhearted', 'ใจดี', 'Jai dii', 'heart - good', '', 'f34_13'),
(900, 34, 'Unkind', 'ใจดำ', 'Jai dam', 'heart - black', '', 'f34_14'),
(901, 34, 'Single', 'โสด', 'Sòht', '', '', 'f34_15'),
(902, 34, 'Married', 'แต่งงานแล้ว', 'Dtàeng-ngaan láew', 'marry - past action marker', '', 'f34_16'),
(903, 34, 'Calm', 'ใจเย็น', 'Jai yen', 'heart - cool', '', 'f34_17'),
(904, 34, 'Smart', 'ฉลาด', 'Chà làat', '', '', 'f34_18'),
(905, 34, 'Crazy', 'บ้า', 'Bâa', '', '', 'f34_19'),
(906, 34, 'What sort of person is he?', 'เขาเป็นคนยังไงคะ', 'Khăo bpen khon yang-ngai khá?', 'he - is - person - how - polite particle?', '', 'f34_20'),
(907, 34, 'Kindhearted person', 'คนใจดี', 'Khon jai-dii', 'person - kind', '', 'f34_21'),
(908, 34, 'Is he kind? Yes, very.', 'เขาใจดีไหมคะ ใช่ เขาใจดีมากค่ะ', 'Khăo jai-dii mái khá? Châi, khăo jai-dii mâak khâ', 'he - kindhearted - or not - polite particle? - yes - he - kindhearted - very - polite particle', '', 'f34_22'),
(909, 34, 'She wears glasses.', 'เธอใส่แว่น', 'Thuuhr sài wâaen.', 'she - wear - glasses', '', 'f34_23'),
(910, 34, 'Your baby is cute.', 'ลูกของคุณน่ารัก', 'Lûuk kăwng khun nâa-rák', 'child - belonging to - you - cute', '', 'f34_24'),
(911, 34, 'I am more shy than you.', 'ฉันขี้อายมากกว่าคุณ', 'Chăn khîi-ai mâak gwàa khun', 'I - shy - very - more than - you', '', 'f34_25'),
(912, 34, 'He is taller than me.', 'เขาสูงกว่าฉัน', 'Khăo sŏung gwàa chăn.', 'he - tall - more than - me', '', 'f34_26'),
(913, 34, 'Who is the prettiest girl in your class?', 'ใครสวยที่สุดในห้องของคุณคะ', 'Khrai sŭay thîi-sòot nai hâawng kăwng khun khá?', 'who - beautiful - most - in - room - of - you - polite particle?', '', 'f34_27'),
(914, 35, 'Happy', 'ดีใจ', 'Dii jai', 'good - heart', '', 'f35_1'),
(915, 35, 'Sad / upset', 'เสียใจ', 'Sĭa jai', 'spoiled - heart', '', 'f35_2'),
(916, 35, 'Fine', 'สบายดี', 'Sà-baai-dii', '', '', 'f35_3'),
(917, 35, 'Tired', 'เหนื่อย', 'Nèuuay', '', '', 'f35_4'),
(918, 35, 'Bored', 'เบื่อ', 'Bùea', '', '', 'f35_5'),
(919, 35, 'Excited', 'ตื่นเต้น', 'Dtèuun dtên', 'scare - dance/throb', '', 'f35_6'),
(920, 35, 'Angry', 'โกรธ', 'Gròht', '', '', 'f35_7'),
(921, 35, 'Interested', 'สนใจ', 'Sŏn-jai', '', '', 'f35_8'),
(922, 35, 'Offended', 'เจ็บใจ', 'Jèp jai', 'hurt - heart', '', 'f35_9'),
(923, 35, 'How do you feel?', 'คุณรู้สึกอย่างไรคะ', 'Khun rúu-sèuk yaang-rai khá?', 'you - feel - how - polite particle?', '', 'f35_10'),
(924, 35, 'I''m tired.', 'ฉันเหนื่อย', 'Chăn nèuuay', 'I - tired', '', 'f35_11'),
(925, 35, 'You look sad.', 'คุณดูเสียใจ', 'Khun duu sĭa-jai', 'you - look - sad', '', 'f35_12'),
(926, 35, 'Why is he angry?', 'เขาโกรธเพราะอะไรเหรอคะ', 'Khăo gròht phráw à-rai rŭuhr khá?', 'he - angry - because - what - question particle - polite particle?', '', 'f35_13'),
(927, 35, 'She''s angry that Chalerm is drunk', 'เธอโกรธที่เฉลิมเมาเหล้า', 'Thuuhr gròht thîi Chà-lĕerm mao lâo', 'she - angry - that - Chalerm - intoxicated - alcohol', '', 'f35_14'),
(928, 35, 'What do you think?', 'คุณคิดอย่างไรคะ', 'Khun khít yaang-rai khá?', 'you - think - how - polite particle?', '', 'f35_15'),
(929, 35, 'I think it''s a good idea.', 'ฉันคิดว่ามันเป็นความคิดที่ดีนะคะ', 'Chăn khít wâh mun bpen khwaam khít thîi dii ná khâ', 'I - think - that - it - is - particle which converts a verb into a noun - think - that (is) - good - softening particle - polite particle', 'The word ''khwaam'' converts a verb or adjective into a noun. In this case ''khít'' (think) becomes ''idea''.', 'f35_16'),
(930, 35, 'I think you should apologise to Gaew because she looks upset.', 'ฉันคิดว่าคุณควรไปขอโทษแก้วนะคะ เพราะแก้วดูเสียใจมาก', 'Chăn khít wâh khun khuaan bpai kŏr-thôt Gâew ná khâ, phráw Gâew duu sĭa-jai mâak', 'I - think - that - you - should - go - apologise - Gaew - softening particle - polite particle - because - Gaew - look - upset - very', '', 'f35_17'),
(931, 35, 'He told me not to complain so that no one will lose face.', 'เขาบอกฉันว่าฉันไม่ควรบ่นเพราะจะได้ไม่มีใครเสียหน้า', 'Khăo bòrk chăn wâh chăn mâi khuaan bòhn phráw jà-dâi mâi mii khrai sĭa nâa', 'he - tell - me - that - I - not - should - complain - because - will be able to - not - have - anyone - spoil - face', '', 'f35_18'),
(932, 35, 'I think that he did a good job.', 'ฉันคิดว่าเขาทำงานดี', 'Chăn khít wâh khăo tum-ngaan dii', 'I - think - that - he - work - good', '', 'f35_19'),
(933, 35, 'When shall we go?', 'เราจะไปเมื่อไหร่ดีคะ', 'Rao jà bpai mêua-rai dii khá?', 'we - future marker - go - when - good - polite particle?', 'We can put the word ''dii'' after a question word to ask for advice or opinion.', 'f35_20'),
(934, 35, 'I agree.', 'ฉันเห็นด้วย', 'Chăn hĕn dûay', 'I - see - also', '', 'f35_21'),
(935, 35, 'I disagree.', 'ฉันไม่เห็นด้วย', 'Chăn mâi hĕn dûay', 'I - not - see - also', '', 'f35_22'),
(936, 35, 'It doesn''t matter.', 'มันไม่สำคัญ', 'Mun mâi săm-khan', 'it - not - important', '', 'f35_23'),
(937, 35, 'I don''t know', 'ฉันไม่รู้', 'Chăn mâi rúu', 'I - not - know', '', 'f35_24'),
(938, 35, 'I don''t mind', 'ฉันไม่คิดมาก', 'Chăn mâi khít mâak', 'I - not - think - much', '', 'f35_25'),
(939, 35, 'I hope that you will understand.', 'ฉันหวังว่าคุณจะเข้าใจ', 'Chăn wăng wâh khun jà khâo-jai', 'I - hope - that - you - will - understand', '', 'f35_26'),
(940, 37, 'Watch a movie', 'ดูหนัง', 'Duu năng', 'watch - film', '', 'f37_1'),
(941, 37, 'Listen to music', 'ฟังเพลง', 'Fang phleng', 'listen - song', '', 'f37_2'),
(942, 37, 'Watch a play', 'ดูการแสดง', 'Duu gaan-sà-daaeng', 'look at - performance', '', 'f37_3'),
(943, 37, 'Dance(verb)', 'เต้นรำ', 'Dtên-ram', '', '', 'f37_4'),
(944, 37, 'Lyrics', 'เนื้อเพลง', 'Néua plehng', 'lyrics - song', '', 'f37_6'),
(945, 37, 'Play guitar', 'เล่นกีต้าร์', 'Lên gii-dtâa', 'play - guitar', '', 'f37_7'),
(946, 37, 'Do you like singing?', 'คุณชอบร้องเพลงไหมคะ', 'Khun chôrp rórng phleng mái khá?', 'you - like - sing - song - or not - polite particle?', '', 'f37_8'),
(947, 37, 'Who is your favourite singer?', 'คุณชอบนักร้องคนไหนคะ', 'Khun chôrp nák-rórng khon năi khá?', 'you - like - singer - person classifier - which - polite particle?', '', 'f37_9'),
(948, 37, 'Traditional Thai music', 'เพลงไทยเดิม', 'Phleng Thai deerm', 'song - Thai - original', '', 'f37_10'),
(949, 37, 'Pop music', 'เพลงป๊อป', 'Phleng bpóp', 'song - pop', '', 'f37_11'),
(950, 37, 'Traditional dance', 'รำไทย', 'Ram Thai', '', '', 'f37_12'),
(951, 37, 'Play sport', 'เล่นกีฬา', 'Lên gi-laa', 'play - sport', '', 'f37_13'),
(952, 37, 'Play football', 'เล่นฟุตบอล', 'Lên fút-baawn', 'play - football', '', 'f37_14'),
(953, 37, 'Badminton', 'แบดมินตัน', 'Bàaet-min-dtan', '', '', 'f37_15'),
(954, 37, 'Volleyball', 'วอลเลย์บอล', 'Wah-lî-baawn', '', '', 'f37_16'),
(955, 37, 'Basketball', 'บาสเก็ตบอล', 'Bàas-gèt-baawn', '', '', 'f37_17'),
(956, 37, 'Handball', 'แฮนด์บอล', 'Haaen-baawn', '', '', 'f37_18'),
(957, 37, 'Thai boxing', 'มวยไทย', 'Muay Thai', '', '', 'f37_19'),
(958, 37, 'Kite flying', 'ว่าว', 'Wâao', 'kite', '', 'f37_20'),
(959, 37, 'Thai chess', 'หมากรุก', 'Màak-róok', '', '', 'f37_21'),
(960, 37, 'Sepak takraw', 'ตะกร้อ', 'Dta-grâw', '', '', 'f37_22'),
(961, 37, 'Watch a football match', 'ดูเกมส์ฟุตบอล', 'Duu gaehm fút-baawn', 'watch - game - football', '', 'f37_23'),
(962, 37, 'Do you like volleyball?', 'คุณชอบวอลเลย์บอลไหม', 'Khun chôrp wah-lî-baawn mái?', 'you - like - volleyball - or not?', '', 'f37_24'),
(963, 37, 'Do you know how to swim?', 'คุณว่ายน้ำเป็นไหม', 'Khun wâi náam bpen mái?', 'you - swim - water - know how to - or not?', '', 'f37_25'),
(964, 37, 'Do you want to play badminton?', 'คุณอยากเล่นแบดมินตันไหม', 'Khun yàak lên bàaet-min-dtan mái?', 'you - want - play - badminton - or not?', '', 'f37_26'),
(965, 37, 'Athlete/sports player', 'นักกีฬา', 'Nák gi-laa', 'professional - sport', '', 'f37_27'),
(966, 37, 'Sports team', 'ทีมกีฬา', 'Theem gi-laa', 'team - sport', '', 'f37_28'),
(967, 39, 'Temple', 'วัด', 'Wát', '', '', 'f39_1'),
(968, 39, 'Forest temple', 'วัดป่า', 'Wát bpàa', 'temple - forest', '', 'f39_2'),
(969, 39, 'Temple meeting hall', 'ศาลา', 'Săa-laa', '', '', 'f39_3'),
(970, 39, 'Monk', 'พระสงฆ์ ', 'Phrá'' sŏhng', '', '', 'f39_4'),
(971, 39, 'Novice monk', 'เณร / สามเณร', 'Naehn / Săam-má-naehn', '', '', 'f39_5'),
(972, 39, 'Nun', 'แม่ชี', 'Mâe chii', 'mother - nun', '', 'f39_6'),
(973, 39, 'Lord Buddha', 'พระพุทธองค์', 'Phrá'' phút-thá ohng', 'god - Buddha - classifier', '', 'f39_7'),
(974, 39, 'Buddhism', 'ศาสนาพุทธ', 'Sàat-sà-năa phút', 'religion - Buddha', '', 'f39_8'),
(975, 39, 'Buddhist person', 'ชาวพุทธ', 'Chaao phút', 'person - Buddhist', '', 'f39_9'),
(976, 39, 'Offering of food to a monk', 'ใส่บาตร', 'Sài bàat', 'put in - bowl carried by monks', '', 'f39_10'),
(977, 39, 'Buddhist precept', 'ศีล', 'Sĭin', '', '', 'f39_11'),
(978, 39, 'To observe Buddhist precepts', 'ถือศีล', 'Thĕuu sĭin', 'to hold a belief - religious precept', '', 'f39_12'),
(979, 39, 'Sacred', 'ศักดิ์สิทธิ์', 'Sàk-sìt', '', '', 'f39_13'),
(980, 39, 'Merit, moral goodness', 'คุณธรรม', 'Khoon-ná tham', 'merit - moral goodness', '', 'f39_14'),
(981, 39, 'Meditation', 'สมาธิ', 'Sà-maa-thí', '', '', 'f39_15'),
(982, 39, 'Forbidden', 'ต้องห้าม', 'Dtôrng hâam', 'must - to forbid', '', 'f39_16'),
(983, 39, 'Buddha image', 'พระพุทธรูป', 'Phrá'' phút-thá rûup', 'god - Buddha - shape / form', '', 'f39_17'),
(984, 39, 'Stupa', 'เจดีย์', 'Jaeh-dee', '', '', 'f39_18'),
(985, 39, 'Community of monks', 'สังฆมณฑล', 'Săng-khá mohn-tohn', 'religious - circle', '', 'f39_19'),
(986, 39, 'Sermon, moral discourse', 'ธรรมีกถา', 'Thum-mee-gà-thăa', '', '', 'f39_20'),
(987, 39, 'Make merit', 'ทำบุญ', 'Tham boon', 'do - merit', '', 'f39_25'),
(988, 39, 'Go around a stupa', 'เวียนเทียน', 'Wiian thiian', 'go around - candle', 'It is common practice to go around a stupa three times when visiting a temple.', 'f39_26'),
(989, 39, 'Mosque', 'มัสยิด', 'Mát-sà-yít', '', '', 'f39_21'),
(990, 39, 'Muslim worship', 'ละหมาด', 'Lá-màat', '', '', 'f39_22'),
(991, 39, 'The Koran', 'อัลกุระอ่าน', 'An-gòo-rá-aan', '', '', 'f39_23'),
(992, 39, 'Church', 'โบสถ์', 'Bòht', '', '', 'f39_24'),
(993, 40, 'Children''s Day', 'วันเด็ก', 'Wan dèk', 'day - child', 'Second Saturday in January.', 'f40_1'),
(994, 40, 'Makha Bucha', 'มาฆบูชา', 'Maa-khá Buu-chaa', 'third lunar month - worship', 'The day when 1250 of the Lord Buddha''s disciples spontaneously gathered to hear him preach. Usually falls in February or March.', 'f40_2'),
(995, 40, 'Water festival', 'สงกรานต์', 'Sŏhng-graan', '', 'Thai New Year, April 13-15, when everyone is doused with water.', 'f40_3'),
(996, 40, 'Rocket festival, Isan', 'ประเพณีบุญบั้งไฟ', 'Bprà-phaeh-nee boon bâng-fai', 'custom - merit - rocket', 'Held in May to encourage the Gods to send rain.', 'f40_4'),
(997, 40, 'Buddhist holy day', 'วันพระ', 'Wan phrá', '', '', 'f40_5'),
(998, 40, 'Visakha Bucha', 'วันวิสาขบูชา', 'Wan Wí-săa-khà Buu-chaa', 'day - full moon day - worship', 'Commemorates three important events in the life of the Lord Buddha - his birth, enlightenment and death - which all occurred on the full moon day of the sixth lunar month. Occurs in May/June.', 'f40_6'),
(999, 40, 'Asahna Bucha', 'วันอาสาฬหบูชา', 'Wan Aa-săan-hà Buu-chaa', 'day - full moon day of eighth lunar month - worship', 'The day when the Lord Buddha delivered his first sermon. Usually in July or August.', 'f40_7'),
(1000, 40, 'Khao Phansa', 'เข้าพรรษา', 'Khâo phan-săa', 'enter - rainy season', 'The day after Asahna Bucha. Marks the start of the three month Buddhist retreat period.', 'f40_8'),
(1001, 40, 'Candle Festival, Ubon Ratchatani', 'ประเพณีแห่เทียนพรรษา', 'Bprà-phaeh-nee hàae thiian phan-săa', 'custom - parade - candle - rainy season', 'Held in July.', 'f40_9'),
(1002, 100, 'Queen''s Birthday and Mother''s Day', 'วันแม่', 'Wan mâe', 'day - mother', 'Held on August 12', 'f40_10'),
(1003, 40, 'Awk Phansa', 'ออกพรรษา', 'Àawk phan-săa ', 'exit - rainy season', 'The end of the rainy season and Buddhist retreat period, occurring in September or October.', 'f40_11'),
(1004, 40, 'Loi Krathong', 'ลอยกระทง', 'Loi grà-thohng', 'set afloat - ceremonial basket', 'Wish making festival where candles are floated on water inside special baskets. Held in November.', 'f40_12'),
(1005, 100, 'King''s Birthday and Father''s Day', 'วันพ่อ', 'Wan phâaw', 'day - father', 'Held on December 5.', 'f40_13'),
(1006, 40, 'Birthday', 'วันเกิด', 'Wan gèut', 'day - birth', '', 'f40_14'),
(1007, 40, 'When is your birthday?', 'วันเกิดคุณวันไหนคะ', 'Wan gèut khun wan năi khá?', 'day - birth - you - day - which - polite particle?', '', 'f40_15'),
(1008, 41, 'Doctor', 'หมอ', 'Mŏr', '', '', 'f41_1'),
(1009, 41, 'Nurse', 'พยาบาล', 'Phá-ya-baan', '', '', 'f41_2'),
(1010, 41, 'Dentist', 'หมอฟัน', 'Mŏr fan', 'doctor - teeth', '', 'f41_3'),
(1011, 41, 'Medicine/drug', 'ยา', 'Yaa', '', '', 'f41_4'),
(1012, 41, 'Prescription', 'ใบสั่งยา', 'Bai sàng yaa', 'sheet - order - medicine', '', 'f41_5'),
(1013, 41, 'Inject', 'ฉีด', 'Chìit', '', '', 'f41_6'),
(1014, 41, 'Hospital', 'โรงพยาบาล', 'Rohng phá-ya-baan', 'building - administer treatment', 'The hospital is the first port of call in Thailand, whether it’s a small injury or a serious sickness. It’s rare to find a GP clinic in Thailand. Hospitals in Thailand accept both emergency and non-emergency patients.', 'f41_7'),
(1015, 41, 'Health centre', 'สถานีอนามัย', 'Sà-thăa-nii à-naa-mai', 'station - health', '', 'f41_8'),
(1016, 41, 'Disease', 'โรค', 'Rôhk', '', '', 'f41_9'),
(1017, 41, 'Infected', 'ติดเชื้อ', 'Dtìt chéuua', 'contract disease - germ', '', 'f41_10'),
(1018, 41, 'Wound, cut', 'แผล', 'Phlăe', '', '', 'f41_11'),
(1019, 41, 'Stomach ache', 'ปวดท้อง', 'Bpùat thórng', 'ache - stomach/belly', '', 'f41_12'),
(1020, 41, 'Headache', 'ปวดหัว', 'Bpùat hŭa', 'ache - head', '', 'f41_13'),
(1021, 41, 'Back ache', 'ปวดหลัง', 'Bpùat lăng', 'ache - back', '', 'f41_14'),
(1022, 41, 'Ear ache', 'ปวดหู', 'Bpùat hŭu', 'ache - ear', '', 'f41_15'),
(1023, 41, 'Sore foot', 'เจ็บเท้า', 'Jèp tháao', 'pain - foot', '', 'f41_17'),
(1024, 41, 'Sore hand', 'มือเจ็บ', 'Meuu jèp', 'hand - pain', '', 'f41_18'),
(1025, 41, 'Pregnant', 'ท้อง', 'Thórng', 'belly', '', 'f41_19'),
(1026, 41, 'Does that hurt?', 'เจ็บไหม', 'Jèp mái?', 'pain - or not?', '', 'f41_16'),
(1027, 41, 'It hurts a little.', 'เจ็บนิดหน่อย', 'Jèp nít nòy', 'pain - a little', '', 'f41_22'),
(1028, 41, 'It hurts a lot.', 'เจ็บมาก', 'Jèp mâak', 'pain - a lot', '', 'f41_23'),
(1029, 41, 'Where does it hurt?', 'เจ็บตรงไหน', 'Jèp dtrong năi?', 'pain - at - where', '', 'f41_20'),
(1030, 41, 'It hurts here.', 'เจ็บตรงนี้', 'Jèp dtrong níi ', 'pain - at - this', '', 'f41_21'),
(1031, 41, 'Symptom(s)', 'อาการ', 'Aa-gaan', '', '', 'f41_24'),
(1032, 41, 'Have a fever', 'เป็นไข้', 'Bpen khâi', 'suffer from - fever', '', 'f41_25'),
(1033, 41, 'Have a cold', 'เป็นหวัด', 'Bpen wàt', 'suffer from - cold', '', 'f41_26'),
(1034, 41, 'Have the flu', 'เป็นไข้หวัด', 'Bpen khâi wàt', 'suffer from - fever - cold', '', 'f41_27'),
(1035, 41, 'Dizzy', 'เวียนหัว', 'Wian hŭa', 'to circle around - head', '', 'f41_28'),
(1036, 41, 'Feel faint', 'เป็นลม', 'Bpen lom', 'to be afflicted with - air, wind', '', 'f41_29'),
(1037, 41, 'Vomit', 'อาเจียน', 'Aa-jian', '', '', 'f41_30'),
(1038, 41, 'Cough', 'ไอ', 'Ai', '', '', 'f41_31'),
(1039, 41, 'Diarrhoea', 'ท้องเสีย', 'Thórng sĭa', 'stomach - spoiled, not working', '', 'f41_32'),
(1040, 41, 'Traditional Thai massage', 'นวดไทย', 'Nûaat Thai', '', '', 'f41_33'),
(1041, 41, 'Go to see the doctor', 'ไปหาหมอ', 'Bpai hăa mŏr', 'go - visit - doctor', '', 'f41_34'),
(1042, 41, 'I need to see a doctor.', 'ฉันต้องไปหาหมอ', 'Chăn dtôrng bpai hăa mŏr', 'I - need to - go - visit - doctor', '', 'f41_35'),
(1043, 41, 'Where is the nearest health centre?', 'สถานีอนามัยใกล้ที่สุดอยู่ไหนคะ', 'Sà-thăa-nii à-naa-mai glâi thîi-sòot yùu năi khá?', 'station - health - close - most - situated - where - polite particle?', '', 'f41_36'),
(1044, 41, 'Are you feeling better?', 'รู้สึกดีขึ้นไหมคะ', 'Rúu sèuk dii khêun mái khá?', 'you - feel - good - increase - or not - polite particle?', '', 'f41_37'),
(1045, 41, 'The doctor gave me some medicine.', 'หมอให้ยาฉันมาค่ะ', 'Mŏr hâi yaa chăn maa khâ', 'doctor - give - medicine - me - marker to indicate continuity from the past - polite particle', '', 'f41_38'),
(1046, 41, 'I think you should get a massage.', 'ฉันคิดว่าคุณควรไปนวดนะคะ', 'Chăn khít wâh khun khuaan bpai nûaat ná khâ', 'I - think - that - you - should - go - massage - softening particle - polite particle', '', 'f41_39');
